### ISSUE TITLE
OTA: add filters/sort to datatables in GUI. Possible?

### ISSUE THREAD

**Issue by bartplessers** [nurikk/z2m-frontend#1016]
DEVICES
![2021-11-02_11-27-26](https://user-images.githubusercontent.com/10470708/139830209-612d51b5-91fc-46d9-b968-e8a8f00d4073.png)

OTA:
![2021-11-02_11-26-37](https://user-images.githubusercontent.com/10470708/139830257-cf09c2bb-d7be-4424-bdf1-0d8e50c6d210.png)

I would love to have same search/filter/sort capabilities on the OTA tab

see also
https://github.com/Koenkk/zigbee2mqtt/issues/9458

**Comment by nurikk** [comment]
Okay, done
