### ISSUE TITLE
[Bug]: Reporting tab set issue is back

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#1020]
### What happened?

When trying to change reporting configuration the old bug where it resets mid-typing or when moving over to the apply buttom.

https://user-images.githubusercontent.com/379665/140646543-9382c718-9b46-4602-853f-4882abc6416b.mov

Video cause it's hard to explain.

State file, not that it will be useful for this...
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7492308/state.json.zip)

### What browsers are you seeing the problem on?

Firefox, Safari

### Relevant stacktrace

```shell
N/a
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Should be fixed, can you help to verify?

**Comment by sjorge** [comment]
Is fixed on the latest z2m dev 👍
