### ISSUE TITLE
png icon sls Gateway

### ISSUE THREAD

**Issue by xrust83** [nurikk/z2m-frontend#1026]
Periodically, the icons on my server become in png format with transparency. They are cooler than the native ones but mostly for xiaomi devices. The device icons are replaced with a zigbee icon. They can be realized forever =)

**Comment by nurikk** [comment]
sls images are used as fallback source but I don't mind if someone will update images in main repo :)

https://github.com/Koenkk/zigbee2mqtt.io/tree/master/public/images/devices
