### ISSUE TITLE
[Bug]: log filter behaves odd after 3 characters

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#1032]
### What happened?

When typing in more than 3 characters in the filter by text field only debug entries are shown and other log levels are hidden.

This video shows it:
https://user-images.githubusercontent.com/379665/141134272-d9791004-5d77-4c99-a37f-2b304fca0971.mov

### What browsers are you seeing the problem on?

Firefox, Safari

### Relevant stacktrace

```shell
n/a
```

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
<img width="571" alt="Screenshot 2021-11-13 at 12 16 58 PM" src="https://user-images.githubusercontent.com/1525421/141605369-f4afb6d5-b345-4e40-baed-de61ae41a2de.png">

I can't reproduce this bug

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by sjorge** [comment]
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7531713/state.json.zip)

Just tried with `zigbee` and that worked fine, retried with `air` (still ok), `air_` it stopped showing a bunch of messages.

`air_` is both part of some friendly names AND of an state property name.

**Comment by nurikk** [comment]
fixed
