### ISSUE TITLE
Hide last_seen column if disable (or enable it by default?)

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#1049]
**Is your feature request related to a problem? Please describe.**
There have been a few issues/discussions like this one:
https://github.com/Koenkk/zigbee2mqtt/discussions/9703

I guess it's understandable, people expect the default columns to `just work`.

**Describe the solution you'd like**
I guess the easiest solution would be to just enable last_seen by default. But some people (like myself) like it disable to not clutter up the mqtt messages. A better solution would be to hide the column if we know it is disable. (It's known on the settings page so I guess the info is available somewhere).

**Describe alternatives you've considered**
Documenting somewhere that the column only works if last seen is configured, but that probably won't solve the occosianal tickets.

**Additional context**
n/a

**Comment by nurikk** [comment]
This is exactly how it's implemented, but last seen column also tried to fallback on **elapsed** property, which behaved a bit odd. I've removed elapsed fallback and now everything is nice and dandy
