### ISSUE TITLE
[Bug]: wrong manufacturer links in web UI

### ISSUE THREAD

**Issue by aaamoeder** [nurikk/z2m-frontend#1053]
### What happened?

When clicking the manufacturer link on the z2mqtt web UI
I went to the website but got redirected because of a wrong link url.
eg: for xiaomi the manufacturer link on the webUI is
"https://www.zigbee2mqtt.io/information/supported_devices.html#v=Xiaomi"

The correct url these links should be pointing at is
"https://www.zigbee2mqtt.io/supported-devices/#v=Xiaomi"

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi, this is fixed id dev
