### ISSUE TITLE
[Bug]: Slow to start/refresh rate 0.6.36

### ISSUE THREAD

**Issue by tteck** [nurikk/z2m-frontend#1064]
### What happened?

The frontend is extremely slow to load once loaded and trying to force remove a device the page refreshes too fast making it unusable
Sluggish and the refreshes make it unusable  

EDIT: If you go to the individual device page, it doesn't refresh allowing you to remove

EDIT2: Finally had to revert to a 11/14/21 backup with 0.6.32 to stabilize the frontend 

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by tteck** [comment]
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7576548/state.json.zip)

**Comment by nurikk** [comment]
Acknowledged, will take a look tomorrow

**Comment by nurikk** [comment]
Should be fixed now

**Comment by tteck** [comment]
Much better, still slower to load than 0.6.32 but usable. Thank you
I also noticed the headers are misaligned (nitpicking)
![Screenshot 2021-11-22 3 43 11 AM](https://user-images.githubusercontent.com/21342670/142830214-42d1ea7d-a0bd-402d-9964-9e13913f2835.png)
