### ISSUE TITLE
Definition of passive device wrong

### ISSUE THREAD

**Issue by tteck** [nurikk/z2m-frontend#1067]
### What happened?

![Screenshot 2021-11-22 12 01 40 PM](https://user-images.githubusercontent.com/21342670/142905621-21ad1925-583b-42bc-996c-ec9bf6057011.png)

should be "mostly battery powered devices"

also wether should be whether

**Comment by nurikk** [comment]
You can fix it in z2m repo
https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/util/settings.schema.json
