### ISSUE TITLE
Whether misspelled

### ISSUE THREAD

**Issue by tteck** [nurikk/z2m-frontend#1068]
### What happened?

![Screenshot 2021-11-12 10 04 09 PM](https://user-images.githubusercontent.com/21342670/142906611-9e33b31b-46a3-49ab-af21-0ebf1876ea0c.png)

wether should be whether

**Comment by nurikk** [comment]
It's fixed in z2m
https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/util/settings.schema.json
