### ISSUE TITLE
Innr Plug brightness confused with voltage!

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#109]
Hello, in the last version Innr Plug brightness confused with voltage!

![sshot-3](https://user-images.githubusercontent.com/32480002/97773744-abe34a80-1b52-11eb-9e7b-cb25caba3acf.jpg)
![sshot-4](https://user-images.githubusercontent.com/32480002/97773745-ac7be100-1b52-11eb-8227-0c8c38dcadfd.jpg)

**Comment by nurikk** [comment]
Might be wrong property name in exposes.
Can you have a look? @Koenkk

**Comment by Koenkk** [comment]
It doesn't show in the exposes tab, only state tab. @salopette was this device previously a device supporting brightness? (a light instead of switch)? Try to delete the entry of this device from `data/state.json`.

**Comment by salopette** [comment]
Thanks, that helped. I cleaned State.json!

![sshot-1](https://user-images.githubusercontent.com/32480002/97799891-d0155900-1c30-11eb-850a-8cab3ec3bb45.jpg)
