### ISSUE TITLE
last message

### ISSUE THREAD

**Issue by runningman84** [nurikk/z2m-frontend#1094]
**Is your feature request related to a problem? Please describe.**
In zigbee2mqtt there is no info when a device was last seen, in home assistant I see some devices with link quality "not available". 

**Describe the solution you'd like**
Please show the last seen/message attribute for each sensor.

**Describe alternatives you've considered**
na

**Additional context**
It is quite difficult to see which device might be offline or out of battery right now.

**Comment by nurikk** [comment]
Just enable last seen option in settings

**Comment by runningman84** [comment]
I have enabled the setting a few seconds ago. Now all devices are listed as last seen just now. This is definitely wrong because a few devices are offline and most of them are battery powered so they do send messages all the time…
