### ISSUE TITLE
Unable to add endpoint 2 from switch to a group using the frontend

### ISSUE THREAD

**Issue by rodriguezst** [nurikk/z2m-frontend#1099]
# Bug Report
## What happened
Adding a device endpoint to a group using the UI only works when adding the first endpoint. Choosing another endpoint sends "undefined/2" as device instead of "device_name/2". Adding the same endpoint via MQTT commands works fine.

## What did you expect to happen
Endpoint 2 being added to the group.

## How to reproduce it (minimal and precise)
Open /#/groups on the frontend and open the group page.
Choose the device to add.
Change the endpoint from 1 to 2. When doing this the endpoint select is emptied as shown in the following pictures:
![imagen](https://user-images.githubusercontent.com/2828844/143230504-2012a1ab-2ae8-476e-bbe9-decbed3f64cf.png)
![imagen](https://user-images.githubusercontent.com/2828844/143230606-54aca72f-6c99-4fa4-933c-55ac5462fa75.png)
Click on add.
The following payload gets sent (resulting in an error)
![imagen](https://user-images.githubusercontent.com/2828844/143230289-58ed0dd9-4c68-4fa2-9362-6ca1db626b6e.png)

The MQTT command zigbee2mqtt/bridge/request/group/members/add with payload {"group": "grupo test", "device": "Caja Dormitorio/2"} works fine.

## Debug Info
Zigbee2MQTT version: 1.22.0
Adapter hardware: CC2652P SMARTLIGHT
Adapter firmware version: zStack3x0 20210319
Web Browser: Mozilla Firefox on Linux (Fedora 34)

[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7597966/state.json.zip)

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by rodriguezst** [comment]
Edited initial comment to add state.json

**Comment by Danit2** [comment]
I have the same problem. 

The problem is on Chrome on Windows and on Safari on a Mac. 
And it doesn't matter if you have endpont 1 and 2 or 10 and 11. 

And there a other problem. 
When you add two endpoints from one device you see two times the same device on the list and you don't know which device is which endpoint. You have on both device both endpoints. 
![image](https://user-images.githubusercontent.com/71522810/143403839-c13e7318-ca74-4728-a86a-d19987f9ae93.jpeg)

**Comment by rodriguezst** [comment]
I was using Firefox on Linux (Fedora 34).

**Comment by nurikk** [comment]
> Edited initial comment to add state.json

Fixed, thanks
