### ISSUE TITLE
"Rename device" modal uses wrong index?

### ISSUE THREAD

**Issue by omerk** [nurikk/z2m-frontend#11]
Just started using this web frontend and it is pretty great, thanks for your work!

A minor bug report:

![image](https://user-images.githubusercontent.com/9847/93028096-78337c00-f609-11ea-82d0-4761812f248f.png)

The "Rename device" modal in the screenshot is what appears when the button for Device # 1 is clicked but it comes up with the label for Device # 2. Just as new devices being added breaks this, sorting columns also result in wrong labels being shown in that modal.

Seeing this on zigbee2mqtt dev branch, commit #b432f3693a68e882f4d418e028f7234b5928b363

**Comment by nurikk** [comment]
Good catch, fixed in https://github.com/nurikk/z2m-frontend/commit/cdb8155343589f2a375ee1ea8e2caa08a578539e
