### ISSUE TITLE
[exposes] occupancy_timeout slider always at 0

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#110]
![state](https://i.imgur.com/wDecTuh.png)
![exposes](https://i.imgur.com/Enxblw2.png)

**Comment by sjorge** [comment]
Oh... looks like it's not actually zero... but the range on that field is insane :( which makes a slider a bit unsable.

Maybe only use a slider when the range is 0-255 or smaller?

**Comment by nurikk** [comment]
I've added temporary solution with input field, but it looks ugly as hell... might need to ask my designer friend to help with ui/ux :)

**Comment by sjorge** [comment]
Does the library your using have something like the bottom right UI element here?

![](https://png.clipart.me/image_preview/42f/ui-elements-free-psd-47968.png)

**Comment by nurikk** [comment]
Currently ui is based on Twitter bootstrap 5
https://v5.getbootstrap.com/docs/5.0/getting-started/introduction/

**Comment by sjorge** [comment]
Going to close it for now, a it is usable enough with the fix.
