### ISSUE TITLE
add a availability column

### ISSUE THREAD

**Issue by Bascht74** [nurikk/z2m-frontend#1104]
**Is your feature request related to a problem? Please describe.**
Hi, I have some devices that get disconnected after some time (weeks, even month). I even spotted a Hue devices this week. 
If I look in the devices overview everything seems in order, seems OK. But if you look closer in the details I see that a device is not there anymore.

**Describe the solution you'd like**
I would like to have a column that shows the availability status of a device. If this takes too much space a red "cross" could be shown next to the icon of the device. I think i would be pretty helpful to see the status of your devices a a single point

This column/icon should reflect the status here:
https://www.zigbee2mqtt.io/guide/configuration/device-availability.html

**Describe alternatives you've considered**
I didn't find a way to quickly see in the frontend the "fitness" of my devices, only the battery status ...

**Additional context**
https://github.com/Koenkk/zigbee2mqtt/issues/4266#issuecomment-974487671

Thx for considering it! Great work by the way. I didn't regret moving from ZHA to Z2M so far...

Sebastian

**Comment by nurikk** [comment]
Done, thanks

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by Bascht74** [comment]
Great!
