### ISSUE TITLE
Fronted does not open via Iframe

### ISSUE THREAD

**Issue by Vladimirov71** [nurikk/z2m-frontend#1105]
### What happened?

Fronted does not open via Iframe in home assistant. I see a blank screen.
z2m and HA are installed on different systems in docker and the same local network.

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
any logs from docker/browser/ha?

**Comment by Vladimirov71** [comment]
doesn't work in chrome browser. works in microsoft edge.

developer tool chrome browser

styles.ts:365 Error while parsing the 'sandbox' attribute: 'allow-download' is an invalid sandbox flag.
p @ styles.ts:365
main.90518dbdda1ba18108b9.js:167 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at getCurrentTheme (http://172.16.1.57:8099/main.90518dbdda1ba18108b9.js:167:41)
    at Object.7225 (http://172.16.1.57:8099/main.90518dbdda1ba18108b9.js:388:15)
    at __webpack_require__ (http://172.16.1.57:8099/runtime.3296ac9a5caef629c7d6.js:23:42)
    at __webpack_exec__ (http://172.16.1.57:8099/main.90518dbdda1ba18108b9.js:5207:48)
    at http://172.16.1.57:8099/main.90518dbdda1ba18108b9.js:5208:49
    at Function.__webpack_require__.O (http://172.16.1.57:8099/runtime.3296ac9a5caef629c7d6.js:67:23)
    at http://172.16.1.57:8099/main.90518dbdda1ba18108b9.js:5209:56
    at webpackJsonpCallback (http://172.16.1.57:8099/runtime.3296ac9a5caef629c7d6.js:180:39)
    at http://172.16.1.57:8099/main.90518dbdda1ba18108b9.js:2:93
getCurrentTheme @ main.90518dbdda1ba18108b9.js:167
7225 @ main.90518dbdda1ba18108b9.js:388
__webpack_require__ @ runtime.3296ac9a5caef629c7d6.js:23
__webpack_exec__ @ main.90518dbdda1ba18108b9.js:5207
(анонимная) @ main.90518dbdda1ba18108b9.js:5208
__webpack_require__.O @ runtime.3296ac9a5caef629c7d6.js:67
(анонимная) @ main.90518dbdda1ba18108b9.js:5209
webpackJsonpCallback @ runtime.3296ac9a5caef629c7d6.js:180
(анонимная) @ main.90518dbdda1ba18108b9.js:2
Не удалось загрузить карту исходного кода с помощью инструментов разработчика: Не удалось загрузить контент для http://172.16.1.57:8099/runtime.3296ac9a5caef629c7d6.js.map: Ошибка HTTP. Код статуса 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE...
Не удалось загрузить карту исходного кода с помощью инструментов разработчика: Не удалось загрузить контент для http://172.16.1.57:8099/scripts/vendor.ea7989ca51c5d50873f3.js.map: Ошибка HTTP. Код статуса 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE...
Не удалось загрузить карту исходного кода с помощью инструментов разработчика: Не удалось загрузить контент для http://172.16.1.57:8099/main.90518dbdda1ba18108b9.js.map: Ошибка HTTP. Код статуса 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE...
Не удалось загрузить карту исходного кода с помощью инструментов разработчика: Не удалось загрузить контент для http://172.16.1.57:8099/main.3d1da3b8dbc50333ee92.css.map: Ошибка HTTP. Код статуса 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE...
Не удалось загрузить карту исходного кода с помощью инструментов разработчика: Не удалось загрузить контент для http://172.16.1.57:8099/scripts/vendor.109be7bda8112bf971cc.css.map: Ошибка HTTP. Код статуса 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE...

**Comment by nurikk** [comment]
You shouldn't use [iframe sandboxing](https://www.w3schools.com/tags/att_iframe_sandbox.asp), but if you must then use correct permissions `sandbox="allow-scripts allow-same-origin"`

**Comment by Vladimirov71** [comment]
ok, I'll try to write an issue to the authors home assistant
