### ISSUE TITLE
powerSource Attribute - Battery backup

### ISSUE THREAD

**Issue by Wh1terat** [nurikk/z2m-frontend#1108]
Hi,

It's been bugging me that my HEIMAN sirens show as unknown power in z2m:
<img width="1250" alt="Screenshot 2021-11-28 at 22 15 15" src="https://user-images.githubusercontent.com/1288525/143788201-32163b45-ae47-4bde-bd40-d41da3fc32f4.png">

From what I can see, the last bit in  powerSource is not being considered. (which denotes battery backup)
<img width="634" alt="Screenshot 2021-11-28 at 22 00 36" src="https://user-images.githubusercontent.com/1288525/143788205-b52cbc8f-1dde-4dac-ab16-4aa33f8aecf7.png">

I have raised this to Koenkk/zigbee-herdsman-converters/issues/3429 but it'll need UI support too.

No idea what free fa icon would suit!
Or maybe better to have both mains and battery so battery level can be shown?

**Comment by nurikk** [comment]
This should be addressed  first in z2m

**Comment by Wh1terat** [comment]
@nurikk Agreed, I have raised it already. 
This is issue is perhaps more preemptive than anything :wink:
