### ISSUE TITLE
unknown group 901 (# 901)

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#111]
Hello, I have an unknown group 901 (# 901) in the frontend.
I cannot delete this.

Anyone an idea?

![sshot-1](https://user-images.githubusercontent.com/32480002/97800874-08b93080-1c39-11eb-985a-3924bb191a0e.jpg)
![sshot-3](https://user-images.githubusercontent.com/32480002/97800877-0951c700-1c39-11eb-9d9f-bef9c8c165c5.jpg)

**Comment by pedrolamas** [comment]
This is related to https://github.com/nurikk/z2m-frontend/issues/46

**Comment by nurikk** [comment]
This is default (system) group, it can't be deleted.
