### ISSUE TITLE
Osram Effects without function

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#112]
Hi, I have the problem with Osram lamps that the efects do not work.
Can you maybe look.

it is only breathe, the others are without function.

![sshot-3](https://user-images.githubusercontent.com/32480002/97807157-855f0580-1c5f-11eb-90d3-3ff19a837baf.jpg)

**Comment by qosmio** [comment]
Not all devices that support effects will support every feature. I see these on mine too. I believe this is due to a majority of the converters having it bundled in generically.

**Comment by nurikk** [comment]
Feel free to update converters code and fine tune `exposes` for your particular light bulb. @qosmio is right about generic implementation

**Comment by qosmio** [comment]
I actually like this approach of seeing everything shown, and not having to manually lookup and test zcl definitions. 

I wrote a few of the converters for Osram/Sylvania/Ledvance from sniffing manufacturers gateway, but you're limited to only discovering what the apps expose.
