### ISSUE TITLE
[Bug]: Link to Zigbee2MQTT version not working

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#1122]
### What happened?

Link to Zigbee2MQTT version not working..... 404

![image](https://user-images.githubusercontent.com/680252/144111972-7dd5e3f2-cc31-40c8-b3e2-e90e83e3e3db.png)

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by timoline** [comment]
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7636138/state.json.zip)

**Comment by timoline** [comment]
as far as I can see the commit hash link is not correct

the link is
https://github.com/Koenkk/zigbee2mqtt/commit/8d155a27
but should be
https://github.com/Koenkk/zigbee2mqtt/commit/bb22216d0984325eca200f7e362370e62baf686d

**Comment by timoline** [comment]
is it already fixed?

**Comment by timoline** [comment]
why?
