### ISSUE TITLE
Better support for iOS devices (mainly Safari)

### ISSUE THREAD

**Issue by YellowNest** [nurikk/z2m-frontend#1128]
**Is your feature request related to a problem? Please describe.**

It is impossible to change language settings from the hamburger menu. Only few languages can be displayed since its not possible to scroll down when the menu is "open"

**Describe the solution you'd like**

The menu must somehow be scrollable

**Describe alternatives you've considered**

Try to fit the menu more compact to the iphone screen

**Additional context**

**Comment by nurikk** [comment]
Fixed, thanks
