### ISSUE TITLE
[Bug]: typo in "availability"

### ISSUE THREAD

**Issue by pedrolamas** [nurikk/z2m-frontend#1133]
### What happened?

I've noticed that the code generically mentions **"Avaliability"** and I assume this is referring to Z2M [Device Availability](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#device-availability) feature, but as you can see, there is a typo in the word that is currently showing in the UI.

![image](https://user-images.githubusercontent.com/85504/144395718-cf9c9183-22d0-4795-b26c-4d3d9edf9198.png)

Seems this was introduced in https://github.com/nurikk/zigbee2mqtt-frontend/commit/68809e8cba50afa31fd7776fd785c1114142bc95

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks

**Comment by andreasbrett** [comment]
@nurikk there are still 25 occurrences with the typo (not in the frontend but in the code):
https://github.com/nurikk/zigbee2mqtt-frontend/search?q=avaliability
