### ISSUE TITLE
Easier way of translating the frontend

### ISSUE THREAD

**Issue by YellowNest** [nurikk/z2m-frontend#1137]
I have translated some projects over the years and would like to suggest that all translations should be done with PoEditor.
Since the frontend lacks many untranslated lines, there will be many different variants with different languages. A main template for translation should exist and when new lines are added it will show up in PoEditor. It will be much more easier and cleaner that way.
Please let me know what you think.

**Comment by nurikk** [comment]
Hi, thanks for suggestion. I have applied to free OSS licence from PoEditor team, let's see :)

**Comment by YellowNest** [comment]
Oh, that's great! 😊

**Comment by nurikk** [comment]
We've got the licence! Can you help with translation? I also need to get familiar with this tool :)

**Comment by nurikk** [comment]
https://poeditor.com/join/project?hash=Az88waAhPd

**Comment by YellowNest** [comment]
> We've got the licence! Can you help with translation? I also need to get familiar with this tool :)

Wow!!! good work! This is exactly what I was hoping for! This will be so much easier to translate! I'm so happy for this! Thanks alot!

**Comment by YellowNest** [comment]
@nurikk I see there's alot of lines without any "reference" so it will be hard to translate unless there is a reference language. I am not sure how to fix it but I assume the english translation has to be 100% translated and then grab all those translated lines as reference. Hope you understand what I mean 😊

**Comment by nurikk** [comment]
English has be to default and it has 100% translations

**Comment by YellowNest** [comment]
There are some lines that looks like this...

program_saturday
program_sunday
valve_detection

For me it appears as if they miss a translated line in PoEditor. There should be a line underneath but there isn't

**Comment by nurikk** [comment]
yes, this keys need to be translated, they're coming from z2m exposed features

**Comment by xrust83** [comment]
Я уже начал. Пока все понятно ;-)

**Comment by xrust83** [comment]
![image](https://user-images.githubusercontent.com/58448955/145181586-02920223-5289-4437-93ec-58c82b292985.png)
in my opinion, I found an error and it is continuous on all translations

**Comment by nurikk** [comment]
> ![image](https://user-images.githubusercontent.com/58448955/145181586-02920223-5289-4437-93ec-58c82b292985.png)
> in my opinion, I found an error and it is continuous on all translations

Wrong title here, kindly raise PR to fix
https://github.com/Koenkk/zigbee2mqtt/blob/98a57b45403847be1625b17b14391b829b9d6555/lib/util/settings.schema.json#L56

**Comment by nurikk** [comment]
Thanks, case is solved

https://poeditor.com/join/project?hash=Az88waAhPd

**Comment by xrust83** [comment]
this word is not yet in translation
