### ISSUE TITLE
[Bug]: Sorting on power no longer also sorts on battery %

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#1141]
### What happened?

It used to be if you sort on power it would sort powered devices before (or after) battery devices but the battery devices would be sorted based on the battery %, this no longer seems to be the case.

Making it more difficult to spot which devices might be running low.

https://user-images.githubusercontent.com/379665/144447259-1c7a3d44-149f-4876-873c-7489cb51a210.mov

### What browsers are you seeing the problem on?

Firefox, Safari

### Relevant stacktrace

```shell
N/a
```

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by sjorge** [comment]
The state linked here https://github.com/nurikk/zigbee2mqtt-frontend/issues/1032#issuecomment-967885789 is pretty much still valid, no devices got added or removed in that time.

**Comment by nurikk** [comment]
Fixed, thanks
