### ISSUE TITLE
[Bug]: Permit join checkbox does not reflect actual join state when join state changed by external system

### ISSUE THREAD

**Issue by bobmel** [nurikk/z2m-frontend#1151]
### What happened?

I run OpenHAB 3 with MQTT binding, mosquitto, and Zigbee2mqtt with ZigStar Stick v4. OpenHAB is configured so that I can enable and disable Zigbee2mqtt's 'Permit Join'. This works fine: When I enable 'Permit join' from OpenHAB, ZigStar Stick v4 LED starts blinking green. When I disable 'Permit join' from OpenHAB, ZigStar Stick v4 LED goes back to steady green.

However, the 'Permit join' checkbox in Settings/Main in Zigbee2mqtt's web ui does not change to reflect the actual 'Permit join' state. Reloading the web page does not make any difference: the checkbox state remains incorrect.

My expectation as a user is that the checkbox should reflect the actual 'Permit join' state even if the state change was performed by an external system like OpenHAB, at least after reloading the Zigbee2mqtt web ui Settings page. So I consider this to be a bug.

[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7662150/state.json.zip)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, it wouldn't change, checkbox in settings responses for permit on join during startup. Change it to checked to enable join during z2m startup.
