### ISSUE TITLE
[Bug]: Network Map doesn't show any connections between devices with Conbee II

### ISSUE THREAD

**Issue by swingerman** [nurikk/z2m-frontend#1161]
### What happened?

All connected devices are fully working and listed properly under devices but on the network map, the connection hierarchy is not shown. (see screenshot)

Scenario: changed dongle to Conbee II

I understand that for some devices it's normal but for all of them?

![image](https://user-images.githubusercontent.com/7681395/145185923-d9b8195e-2ffa-4d0c-b0d0-33e7faf2fe5f.png)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Did you donwload state.json.zip?

I will attach state.json.z
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7675039/state.json.zip)
ip

**Comment by nurikk** [comment]
Not a frontend issue
