### ISSUE TITLE
[Bug]: sort by broken in 0.6.34

### ISSUE THREAD

**Issue by bartplessers** [nurikk/z2m-frontend#1166]
### What happened?

Devices --> click on table column header to sort colum --> does not work (correctly)

I.e. here I sorted on "Manufacturer".
The Tuya device is in between Lidl devices...
![2021-12-09_17-16-53](https://user-images.githubusercontent.com/10470708/145434240-86485523-dff3-4e79-bc7a-3f2fd593e25c.png)

same happens on other columns.
Especially the column "power" is of my interest because it'ts a quick view to see were I have to change my batteries.

kind regards,
BartPlessers

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
FIxed, thanks

**Comment by bartplessers** [comment]
Hi @nurikk ,

Dowloaded latest version today:

Zigbee2MQTT versie
1.22.2-dev commit: 4f887a1
Coördinator type
zStack3x0
Coordinator revisie
20210708
Frontend
0.6.68


Sortorder seems to give problems again (was solved in previous release).


Something went wrong in deployment?

Grtz
Bart
