### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by marsjan155** [nurikk/z2m-frontend#1174]
### What happened?

When is any custom converter and permitJoin is enabled, Devices page, every 1 second, trying to download that images.
Using version `1.22.1 commit: unknown` with HomeAssistant `core-2021.10.6`
Console from devtools:
![image](https://user-images.githubusercontent.com/9789199/146182546-68983fe4-62e6-4369-aad7-f85de68d7075.png)

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi, can you try using latest dev? And if issue still there attach state.json from frontend?

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

state.json file from `Settings -> Tools -> Download state`

**Comment by marsjan155** [comment]
sure I'll check but i can't do it in the next 2 days

**Comment by nurikk** [comment]
Fixed in latest dev, thanks for report
