### ISSUE TITLE
[Bug]: Sorting option in the frontend is broken

### ISSUE THREAD

**Issue by the-cyberspace** [nurikk/z2m-frontend#1176]
### What happened?

The sorting option in the frontend is broken. See following screenshot:

Begin:
![afbeelding](https://user-images.githubusercontent.com/46862733/146229638-fd7f9b7c-7615-437f-a942-3af2ad13d31f.png)

In this screenshot the name table is sorted alphabetically but i`m having a sensor for a 3dprinter (see screenshot below) and as far as i know numbers appear first when you sort alphabetically.

End:
![afbeelding](https://user-images.githubusercontent.com/46862733/146229702-f093efd4-a18d-4f70-9206-e39f28432c31.png)

Zigbee2MQTT version: 1.22.1-dev commit: d875b29
Adapter hardware: ConBee2/RaspBee2
Adapter firmware version: 0x26720700

### What browsers are you seeing the problem on?

Firefox

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, this isn’t a bug. It’s how it’s implemented in underlying library 

https://github.com/tannerlinsley/react-table/blob/master/src/sortTypes.js
