### ISSUE TITLE
Enhance Documentation - How to activate existing Translation

### ISSUE THREAD

**Issue by xstable** [nurikk/z2m-frontend#1184]
I've found that there is a Tab for Translation, it's describes how to help to translate files.
As I'd fork the de.json file, I've seen that all the stuff I need is still translated. (see: https://github.com/nurikk/zigbee2mqtt-frontend/edit/dev/src/i18n/locales/de.json).
But in my HA installation, it's all shown in english languge.

Now I wonder, how to import or aktivate this still existing German Language File.
Would be great, if the documentation could be enhanced to describe such stuff.

**Comment by nurikk** [comment]
Hello, we've migrated to Poeditor, kindly join to help with translations. Btw you might like to use latest dev branch.

https://poeditor.com/join/project?hash=Az88waAhPd

**Comment by xstable** [comment]
@nurikk  thanks for your response. I can help with translation... true. 
But my request  at this point is about, how do I activate this existing translation in HA ?

**Comment by nurikk** [comment]
You can't "activate" them. Time to time I do translation export and publish dev release. So your choice is to switch to dev branch

**Comment by xstable** [comment]
Ok, thank you. So this means in the current stable release there is no german translation at all yet?!?
