### ISSUE TITLE
[Bug]: Simulated brightness settings not saved

### ISSUE THREAD

**Issue by Bascht74** [nurikk/z2m-frontend#1187]
### What happened?

If I set the simulated brightness values of a device (e.g. 929002398602) and click apply, everything seems to be fine:
![image](https://user-images.githubusercontent.com/66269310/146795957-844ea835-6f4e-439f-9e74-e07ca2c9aafe.png)

But it you reload the page, the (new) values are gone: 
![image](https://user-images.githubusercontent.com/66269310/146796001-ffd520e1-5ed4-42ec-8e3b-e2e8fcdf7a8a.png)

So they don't seem to be saved. 

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
If needed, please tell me where I can get it.
If you need state.json.zip, please let me know.
```

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Something is wrong with hass addon, I can't help with it

**Comment by Bascht74** [comment]
@nurikk 
I deleted the add-on specific part and created an issue here: 
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/260

Besides that the settings in the frontend are not saved if you change it. 
It looks fine, but if you reload the page the settings are gone...
I think that this behavior is part of the frontend and not the add-on.

Thx for any advice!

**Comment by nurikk** [comment]
settings are also addon issue

**Comment by Bascht74** [comment]
@nurikk 
Do you know a way find the cause of this issue in the addon?
Could it the environment (e.g. versions) that doesn't fit the web frontend or is it a file access thing because the frontend can not access something? Or is it specific to the yaml configuration stuff in the addon?

Any way to analyse this or compare it to a working environment?
Other settings can be saved in the frontend and they will be reset because of the YAML-config, so these are non-consistent. But here you can save the option it is gone right away without restart...

Sebastian

**Comment by Bascht74** [comment]
Bump. I will check with the last add-on changes.

**Comment by Bascht74** [comment]
I checked now with the new add on environment. 

If I set the simulated brightness in the frontend, the frontend creates a mqtt topic:
![image](https://user-images.githubusercontent.com/66269310/168471115-80d2f3a9-47de-4ef7-840d-0efdfca67323.png)
![image](https://user-images.githubusercontent.com/66269310/168471128-6dc2b929-2ba7-4995-b412-d156b4a21c1d.png)

But if I go out off the device configuration and back it shows zeros again:
![image](https://user-images.githubusercontent.com/66269310/168471211-1e65ffc0-deaf-478b-bb8f-2bca0a4f69f7.png)

The settings are saved now as you can see by the "from" / "to": 
`Info 2022-05-15 13:48:27MQTT publish: topic 'zigbee2mqtt/bridge/response/device/options', payload '{"data":{"from":{"simulated_brightness":{"delta":11,"interval":965}},"id":"0x001788010b730dd2","to":{"simulated_brightness":{"delta":11,"interval":965}}},"status":"ok","transaction":"kl6ht-4"}'`

... but they are not stored in the frontend / are not retrieved from z2m by the frontend. So they are not shown. 

@nurikk are you still shure about: 

> settings are also addon issue

as they are set but not persistently shown in the frontend (and they are not retrieved via mqtt if you open the device settings)?
All other settings work fine for me, only this one causing trouble.

Seb
