### ISSUE TITLE
Sort By 'Power' should sort with battery level

### ISSUE THREAD

**Issue by roumano** [nurikk/z2m-frontend#1188]
**Is your feature request related to a problem? Please describe.**
In Devices menu, we can sort with any field.
When Sorting By 'Power' should sort with battery level

**Describe the solution you'd like**
Sort By 'Power' should sort with battery level
empty battery should be see first, then battery full , endly alimented power 

**Describe alternatives you've considered**

**Additional context**

**Comment by nurikk** [comment]
Fixed in dev

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by alfs** [comment]
I'm using a standard install of z2m in homeassistant. Version 1.33.0-1.

Powered devices are sorted before low-battery devices, see screenshot.

Would be nice to have devices needing new battery to be on top.

Can powered devices be sorted below full battery devices? It's also logical for infinite power to be below the finite powered devices :) 

![Screenshot 2023-09-23 at 09 56 02](https://github.com/nurikk/zigbee2mqtt-frontend/assets/1869479/5fc4862d-f58b-4ef5-8f09-064949d433ae)
