### ISSUE TITLE
[Bug]: Frontend should work without internet connection.

### ISSUE THREAD

**Issue by hppyworld** [nurikk/z2m-frontend#1189]
### What happened?

# Bug Report
Frontend should work without internet connection.
Its better to not call internet for frontend load. it should work without calling external service.
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css

## What happened
Frontend can not load without internet. 

## What did you expect to happen
Frontend should work without calling to internet service.
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css

## How to reproduce it (minimal and precise)
Open frontend in webbrowser without internet and you will see it tries to load External CSS and can not work as internet is needed to load CSS. 

### What browsers are you seeing the problem on?

Firefox

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks
