### ISSUE TITLE
(Feature request) Link to the "supported devices" webpage on the "about" page of the frontend 

### ISSUE THREAD

**Issue by grostim** [nurikk/z2m-frontend#119]
I think it would be great to have a link to the relevant devices page from zigbee2mqtt.io on the "about" page of each device.

Typically, on this page:
![image](https://user-images.githubusercontent.com/3714755/98467414-6ddeca00-21d5-11eb-97ec-c9bde834e370.png)

I would like a link pointing towards this page:
https://www.zigbee2mqtt.io/devices/WXCJKG21LM.html

**Comment by nurikk** [comment]
Good idea, implemented in dev

**Comment by grostim** [comment]
Thanks! I will try it
