### ISSUE TITLE
Crash after adding new device

### ISSUE THREAD

**Issue by ludio71** [nurikk/z2m-frontend#1191]
### What happened?

I just installed the addon and tried to add first device.
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7757192/initialState.json.zip)

![image](https://user-images.githubusercontent.com/28319190/146977198-d2613fc6-bdc5-4c64-8060-7ab7ff350e10.png)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/XdJ7TaNvQpsGMaYUxdjmdWXHuy606Tx1fMbhs9vZFyU/#/
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt_edge


**Error type**: undefined
**Error message**: undefined
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
can't reproduce, try again
