### ISSUE TITLE
[Bug]: Flag for English translation to match British spelling

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#1196]
### What happened?

The latest update switched to the British English spelling for words like color, favorite, behavior,…

The flag to select the language should also reflect the switch to British English.

Even better would be to have both, as I personally prefer the American English spelling it was before the latest version.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by sjorge** [comment]
Spelling change seems to have happened in https://github.com/nurikk/zigbee2mqtt-frontend/commit/2713a78cf89b3add01adcc26c9a480339f454692

**Comment by nurikk** [comment]
Translations are completely crowdsourced, I don't have much time on wording checks. Kindly join translation project

https://poeditor.com/join/project?hash=Az88waAhPd

**Comment by sjorge** [comment]
I already joined the project, I commented on the change here: https://poeditor.com/projects/po_edit?id=494809&term=346944077&id_language=43#showComments346944077

My personal preference is American English, but at least some people want British English.

The project owner needs to:
1. Decided on British or American English going forward and make it clear somewhere for everybody translating
2. Update the flag if the project chooses to go with British English

The alternative is me or someone else going back and changing it to American English, then a day later someone else changes it back to British English, and round and round we go.

**Comment by nurikk** [comment]
As long as you’re guys happy I’m okay you changing back and forth:) Personally I gravitate towards British spellings

**Comment by sjorge** [comment]
I opened a PR, up to you if you merge it or give it a few days for people to chime in.

Language preference aside, the flag should be consistent and editing back and forth will just lead to frustrations so I don't think the later is the way to go.

**Comment by nurikk** [comment]
merged
