### ISSUE TITLE
[Bug]: frontent not loading in current ver.

### ISSUE THREAD

**Issue by vaenror** [nurikk/z2m-frontend#1199]
### What happened?

Running Hass.io current build on Rpi4 4GB with Conbee2 + extension. 

Frontend is not loading the "Devices" Page, eternal spinning cycle. Log says in yellow: "Using experimental new availability feature" and stops there. 
All other pages seemed to work fine. Using a conbee2. Used the same config in the Edge (dev) build an there it's working properly.
Tried several browsers and devices, same problem everywhere. As i said, same config in the Edge build ant its loading up instantly.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by pvi25** [comment]
Same issue over here, already for couple of weeks, see also https://github.com/Koenkk/zigbee2mqtt/issues/10137

**Comment by nurikk** [comment]
This issue already resolved in dev branch, tomorrow happens scheduled release.
Happy new year

**Comment by pvi25** [comment]
I did install dev branch, then its not displaying 'loading, please wait' indeed, but then the list of devices stays empty, but maybe that is another issue.
Also happy new year!

**Comment by nurikk** [comment]
> I did install dev branch, then its not displaying 'loading, please wait' indeed, but then the list of devices stays empty, but maybe that is another issue. Also happy new year!

do you have any devices connected to your coordinator? may be this can be "list of devices stays empty" issue?
