### ISSUE TITLE
[Bug]: plain JSON displayed instead of form item

### ISSUE THREAD

**Issue by ybizeul** [nurikk/z2m-frontend#1208]
### What happened?

Configuration (Specific) shows JSON instead of an actual menu or text field.

![image](https://user-images.githubusercontent.com/182035/147450366-99d95e71-1333-42be-ab53-7dfcbfe7ac92.png)

### What did you expect to happen?

I'm assuming this should be displayed as a text field, but "list" type might not be handled by the UI ?

### How to reproduce it (minimal and precise)

Join a RTCGQ11LM Aqara human body movement and illuminance sensor and display the Configuration (Specific) page.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20201026

### Adapter

Electrolama zig-a-zig-ah! (zzh!)

### Debug log

[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7781211/state.json.zip)

### What browsers are you seeing the problem on?

Safari

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by regevbr** [comment]
Same here, seems that there was never any support for a list feature
https://github.com/nurikk/zigbee2mqtt-frontend/blob/dev/src/components/features/composite/Feature.tsx
