### ISSUE TITLE
[Bug]: Unable to rename group from Web UI

### ISSUE THREAD

**Issue by reefland** [nurikk/z2m-frontend#1216]
### What happened?

1.22.2-dev commit: 15f1df8
Frontend version: 0.6.67

On the Groups page in Z2M Web UI, I click the blue icon to rename a group.  A dialog box briefly appears to edit but immediately goes away.  I expect to be able to use the dialog box and rename the group.   Renaming devices works fine.  This issue is not specific to any group, happens with all of them.

[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7797907/state.json.zip)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant stacktrace

```shell
didn't find one.
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by reefland** [comment]
Not sure if related, but one of the groups is also now showing zero members in UI: `Group Name: Red_Bar_Lights (#3)`

However when I cat out the `configuration.yaml` file it correctly shows 3 members:
```
 '3':
    friendly_name: Red_Bar_Lights
    devices:
      - 0xf0d1b80000007d2d/1
      - 0x7cb03eaa00a4c43b/3
      - 0xf0d1b80000008899/1
```

**Comment by Burki24** [comment]
Hi,

having the same problem, using Frontend 0.6.72
