### ISSUE TITLE
[Bug]: Frontend becomes unresponsive after a while

### ISSUE THREAD

**Issue by ginkel** [nurikk/z2m-frontend#1225]
### What happened?

I have deployed the zigbee2mqtt frontend on a Raspi 4 using the `koenkk/zigbee2mqtt` Docker image. Traffic is routed through  Traefik as reverse proxy, which also takes care of TLS termination. After a certain uptime (in the order of days to weeks), the frontend is no longer reachable and Traefik reports a "Gateway timeout" when attempting to reach z2m. Meanwhile, all z2m backend activity continues normally, so the Docker container is alive.

Unfortunately, I cannot download `state.json.zip` while the frontend is unresponsive.

A Docker container restart works around the problem (but I'd like to avoid having to periodically restart the container).

### What browsers are you seeing the problem on?

Firefox, Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
This issue has been fixed in previous release
