### ISSUE TITLE
Identify endpoints within group

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [nurikk/z2m-frontend#1231]
**Is your feature request related to a problem? Please describe.**
It is difficult to see which specific endpoint is a part of the group. For example, I might have a group of my ceiling fans and a switch with 3 buttons might have the fan connected to the center button so only that endpoint would be within the group. Currently I see all 3 endpoints (top, center and bottom) and it is impossible to see which endpoint(s) are within the group vs not within the group.

**Describe the solution you'd like**
A visual indicator showing which of the endpoints are within the group. This could be a marker next to the endpoint, it highlighted in a different colour or maybe even a box around it.

**Describe alternatives you've considered**
As above. Don't really mind which type of indicator shows the endpoint(s) within the group.

**Additional context**
<img width="1432" alt="Screen Shot 2022-01-03 at 5 21 04 pm" src="https://user-images.githubusercontent.com/59955188/147904024-85bfb514-2ac0-4ed6-b13d-06ac5a3320b4.png">
This screenshot shows my fans group. It is impossible to see which endpoints are within the group vs not.

Thanks for considering and great job on this piece of software.

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by bigfeetneedbigboots** [comment]
Sure, here you go...
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7804047/state.json.zip)

**Comment by FourteenBurbank** [comment]
Has a decision been made on incorporating my feature request?

**Comment by bigfeetneedbigboots** [comment]
Has a decision been made on incorporating my feature request?

**Comment by nurikk** [comment]
I'm sorry, Boss. I've been quite busy :)

<img width="1081" alt="Screenshot 2022-03-06 at 12 02 04 PM" src="https://user-images.githubusercontent.com/1525421/156908695-38ea032a-29fb-4a4f-a790-904345003182.png">
