### ISSUE TITLE
[Bug]: OTA update doesn't reflect the new version

### ISSUE THREAD

**Issue by vk496** [nurikk/z2m-frontend#1240]
### What happened?

After updating the device via OTA, the about page of the device continues showing the old firmware version.

Trying to read manually the genBasic attributes, reports expected values of date and version firmware.

The issue happens with the PR of lixee device (https://github.com/Koenkk/zigbee-herdsman-converters/pull/3493)

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Did you update your Zigbee2MQTT?

**Comment by vk496** [comment]
yep. 0.6.68 (1 commit behind dev). Z2M 1.22.2

Even after restarting Z2M or removing the device (it joins again automatically)

![imagen](https://user-images.githubusercontent.com/5502443/148509513-da5db1ad-816a-487c-b80a-308071912936.png)
![imagen](https://user-images.githubusercontent.com/5502443/148509590-e8364218-4fde-46cc-91f6-41f2db1d5861.png)

**Comment by vk496** [comment]
With the v4 firmware of the device worked as expected. So I assume it was something related to the firm and not to the frontend
