### ISSUE TITLE
Fahrenheit?

### ISSUE THREAD

**Issue by datadreamersllc** [nurikk/z2m-frontend#1250]
Is there a feature to display temperature of my sensors in Fahrenheit instead of Celsius?

**Comment by nurikk** [comment]
hi, sorry this is not supported

**Comment by nebhead** [comment]
Can we reconsider this feature request for people who live in areas where Fahrenheit is the prevailing unit?

**Comment by DCandE** [comment]
I was just now looking for this as well. a checkbox in setting convert C to F where it is originated would make the rest of my integrations much easier.
