### ISSUE TITLE
[Bug]: dashboard crash after using converters

### ISSUE THREAD

**Issue by Ikari34** [nurikk/z2m-frontend#1256]
### What happened?

After installing lixee.js to add a zlinky tic, I can't access to dashboard anymore (the scheme is not accessible to). When I go back and I don't put the external_converters:
  - converters/lixee.js
in the config file of zigbee2mqtt it's ok, the dashboard appear again.
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7862986/state.json.zip)
![cap_erreur_zigbee2mqtt_dashboard](https://user-images.githubusercontent.com/24602631/149336796-4184783f-cc82-4384-a01f-984f58582a71.jpg)
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7862988/initialState.json.zip)
 

### What browsers are you seeing the problem on?

Microsoft Edge

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, you have incorrect converter, your converted defines exposes and object `{}`, but it have to be an array `[]`
