### ISSUE TITLE
Allow adding notes to a device

### ISSUE THREAD

**Issue by tripplet** [nurikk/z2m-frontend#1296]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow adding notes to a device.
I image a separate tab with a simple multiline text field in the device details page.

**Describe alternatives you've considered**
Adding comments in the yaml files, but this defeats the purpose of using the web frontend.

**Additional context**
Was requested [here](https://github.com/Koenkk/zigbee2mqtt/issues/7161) in zigbee2mqtt in the past but went stale.
Due to the frontend communicating with zigbee2mqtt via an API this probably needs to be implemented in both projects?

I'm not sure how feature implementation is coordinated between the projects. API first then frontend?
Or frontend first as in this case it is UI feature request which needs an API endpoint (or not?).

Best regards
Tobi

**Comment by nurikk** [comment]
Hi, without respective API's in z2m I can't do anything

**Comment by tripplet** [comment]
New pull request here for reference: https://github.com/Koenkk/zigbee2mqtt/pull/11493

**Comment by tripplet** [comment]
There is another related issue here: https://github.com/Koenkk/zigbee2mqtt/issues/10158
Maybe both requests can be fixed with the same description feature?
I was initially thinking more of notes (which I currently keep in a separate file) for example: 
- How I did the wiring for an [LLKZMK11LM](https://www.zigbee2mqtt.io/devices/LLKZMK11LM.html) relay controller (which circuit breaker, ...)
- When was a battery last swapped, etc..
In general some multi line text.

The idea of having a short description which can easily be changed without affecting the friendly name is also handy.
Maybe the first line could be displayed in the dashboard column or the about page of a device and the full text on an extra tab which allows changing it in a multi line text box?

**Comment by tripplet** [comment]
Closing because feature is implemented.
(Thanks again)
