### ISSUE TITLE
topic tree

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#13]
Looking promissing.
Maybe add a new page with the mqtt topic - tree structure with their values....

[example](http://harizanov.com/wp-content/uploads/2014/09/common2.jpg)

**Comment by nurikk** [comment]
> Looking promissing.
> Maybe add a new page with the mqtt topic - tree structure with their values....
> 
> [example](http://harizanov.com/wp-content/uploads/2014/09/common2.jpg)

Device states can be viewed on device page, states tab.
Just click on device friendly name link from main page

**Comment by nbostrom** [comment]
@timoline is that a visualization of your friendly_name pattern, split by a divider, like "/"?

**Comment by timoline** [comment]
No is not mine example...but you could do split by a separator, "/", I also have changed to it...
imho, I think it is a best practice to use  "/" in your friendly_name to seperate things

**Comment by nurikk** [comment]
Interesting idea, I'll check what I can do with this
