### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by csillagv** [nurikk/z2m-frontend#1300]
If possible, I would like the Hungarian translation to be available in POEditor. I would also like to translate it.

**Comment by nurikk** [comment]
Hello, here's the reference PR how to do that
https://github.com/nurikk/zigbee2mqtt-frontend/commit/78730a54bb7543468cf5699f278859b20c622b09

You can do same for Hungarian locale, and afte merging I'll enable POEditor for it

**Comment by csillagv** [comment]
Thanks. I did the pattern according to my hope well. I send it :)
