### ISSUE TITLE
[bug] Some links to device pages are broken.

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#132]
Some examples:

Innr RB 285 C => https://www.zigbee2mqtt.io/devices/RB%20285%20C.html#innr-rb%20285%20c
Innr RB 250 C => https://www.zigbee2mqtt.io/devices/RB%20250%20C.html#innr-rb%20250%20c
IKEA LED1537R6/LED1739R5 => https://www.zigbee2mqtt.io/devices/LED1537R6%2FLED1739R5.html#ikea-led1537r6%2Fled1739r5

So it looks like anything with a ' ' (space) '/' (slash)... is broken, I'd hazard a guess  that something url encoding wise is not working.

**Comment by sjorge** [comment]
No symbols or '-' seems fine, but there is no encoding in those ofcourse.

**Comment by sjorge** [comment]
Here are the proper URLs:
https://www.zigbee2mqtt.io/devices/RB_285_C.html#innr-rb-285-c
https://www.zigbee2mqtt.io/devices/RB_250_C.html#innr-rb-250-c
https://www.zigbee2mqtt.io/devices/LED1537R6_LED1739R5.html#ikea-led1537r6led1739r5

So it looks like z2m replaces symbols/spaces with _ in the file name, spaces with - in the anchor and symbols with nothing in the achors.

**Comment by sjorge** [comment]
Still seems broken, just npm installed .77, restarted and cleared the browser cache?

**Comment by nurikk** [comment]
> Still seems broken, just npm installed .77, restarted and cleared the browser cache?

can yoy try to install 0.2.78 version?

**Comment by sjorge** [comment]
Works in .78! 👍
