### ISSUE TITLE
Thermostat is not properly integrated.

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#133]
![sshot-1](https://user-images.githubusercontent.com/32480002/98951356-71868f80-24fa-11eb-8216-0809bf46c5a9.jpg)

state

https://cloud.mail.ru/public/1Ais%2F5NpdBEPSc

**Comment by nurikk** [comment]
> ![sshot-1](https://user-images.githubusercontent.com/32480002/98951356-71868f80-24fa-11eb-8216-0809bf46c5a9.jpg)
> 
> state
> 
> https://cloud.mail.ru/public/1Ais%2F5NpdBEPSc

You're using outdated version. Kindly update to lasted dev branch and check again.

**Comment by salopette** [comment]
I think is up to date?

zigbee2mqtt version
1.16.1-dev commit: 97215c9
coordinator type
zStack3x0
coordinator revision
20201026
frontend version
0.2.78

**Comment by nurikk** [comment]
> I think is up to date?
> 
> zigbee2mqtt version
> 1.16.1-dev commit: 97215c9
> coordinator type
> zStack3x0
> coordinator revision
> 20201026
> frontend version
> 0.2.78

try to update herdsman-converters then, it seems your is behind current master

**Comment by nurikk** [comment]
Oh, sorry, I applied your state dump incorrectly. Checking

**Comment by nurikk** [comment]
Fixed, kindly update to the latest dev

**Comment by salopette** [comment]
THX! 
![sshot-1](https://user-images.githubusercontent.com/32480002/99028242-8ea97580-256f-11eb-9783-1ababf6b5e41.jpg)
