### ISSUE TITLE
[Bug]: Dev console missing clusters

### ISSUE THREAD

**Issue by vk496** [nurikk/z2m-frontend#1345]
### What happened?

Recently (some weeks ago) some new clusters were added to zigbee-herdsman (`0xFF66` liXeePrivate), but it doesn't appear under dev console (and does in the binding tab)

![imagen](https://user-images.githubusercontent.com/5502443/153581214-3db61df3-8a8a-4812-818d-477f76955df6.png)
![imagen](https://user-images.githubusercontent.com/5502443/153581302-2a4f37ad-36c8-41c6-b581-93f3234eca94.png)

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
fixed
