### ISSUE TITLE
Web frontend wrong link for Innr RS 228 T

### ISSUE THREAD

**Issue by tpftpf** [nurikk/z2m-frontend#136]
Minor Issue:

Currently the link is : 
https://www.zigbee2mqtt.io/devices/RS%20228%20T.html#innr-rs%20228%20t
It should be:
https://www.zigbee2mqtt.io/devices/RS_228_T.html

Keep up the great work!

Tom

**Comment by tpftpf** [comment]
👍

**Comment by nurikk** [comment]
Is it okay now?

**Comment by tpftpf** [comment]
👍
