### ISSUE TITLE
(Feature request) Give possibility to rename groups

### ISSUE THREAD

**Issue by grostim** [nurikk/z2m-frontend#137]
Groups should be renameable from the frontend.

zigbee2mqtt/bridge/config/rename #
Allows you to change the friendly_name of a device or group on the fly. Format should be: {"old": "OLD_FRIENDLY_NAME", "new": "NEW_FRIENDLY_NAME"}.

**Comment by pedrolamas** [comment]
Just stumbled on this myself, had to use the MQTT `zigbee2mqtt/bridge/config/rename` message to get it renamed, however I did notice that the frontend only showed the new name once I restarted zigbee2mqtt.
