### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Burki24** [nurikk/z2m-frontend#1372]
### What happened?

Starting the z2m-Dashboard. There are visual issues in TRVs:
![image](https://user-images.githubusercontent.com/20765982/154833146-966205ec-c541-4d4d-92f3-2ad7212cf754.png)

There are linebreaks needed. How to solve this?

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by Burki24** [comment]
I'm running already dev-branch. With Frontend V. 0.6.72.

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by Burki24** [comment]
For sure.
[state.json (6).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8103631/state.json.6.zip)

**Comment by Burki24** [comment]
The Device with this "Schedule Mode" can be found from Line 22183 to line 22456 as an example. 
edit: sorry, wrong lines. Now corrected.

**Comment by nurikk** [comment]
Fixed, wait in next `dev`
