### ISSUE TITLE
 [Feature request]: Iframe integration into exposes tab

### ISSUE THREAD

**Issue by vklachkov** [nurikk/z2m-frontend#1373]
Transferred from here, https://github.com/Koenkk/zigbee2mqtt/issues/11519

### Is your feature request related to a problem? Please describe

Our team is developing a complex Zigbee device that lacks the capabilities of the Z2M frontend. But we are completely satisfied with the current functionality. We would like to integrate our editor into the Exposes tab: [demo video](https://youtu.be/6OKWhm6D1Do)

### Describe the solution you'd like

Specify url for iframe in converter

### Describe alternatives you've considered

The alternative would be to keep our editor somewhere so that it only sends data to MQTT, which is inconvenient 

### Additional context

We understand that the task is quite specific. If it's impossible architecturally, we'll understand

**Comment by nurikk** [comment]
Hi, this is way to specific feature. I don't think it worth implementing.

**Comment by vklachkov** [comment]
OK, I understand. Close issue?
