### ISSUE TITLE
[Bug]: Slider is not adjustable less than 1

### ISSUE THREAD

**Issue by vklachkov** [nurikk/z2m-frontend#1374]
### What happened?

I am developing my own zigbee thermostat. In the converter, in exposes, I wrote `climate()` with a fractional step for adjusting the temperature and target temperature. Like this:

```js
exposes.climate()
    .withSystemMode(['off', 'auto'])
    .withLocalTemperature()
    .withLocalTemperatureCalibration(0.0, 2.5, 0.5)
    .withSetpoint('occupied_heating_setpoint', 15.0, 50.0, 0.5)
    .withEndpoint(epName),
```

But the slider step still remains 1. If I change the value from the thermostat itself, the slider correctly displays a fractional value

### What browsers are you seeing the problem on?

Firefox, Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by vklachkov** [comment]
How quickly! Thanks a lot
