### ISSUE TITLE
(Feature request) give possibibilty to define the group_id when creating a group:

### ISSUE THREAD

**Issue by grostim** [nurikk/z2m-frontend#138]
This is a very specific usecase, but sometimes i need to specify the group_id.
I do it from mqtt with :

> zigbee2mqtt/bridge/config/add_group #
> Allows you to add a group, payload should be the name of the group, e.g. my_group.
> 
> In case you also want to specify the group ID, provide the following payload {"friendly_name": "my_group", "id": 42}.

It would be convenient to do it from the frontend.

**Comment by nurikk** [comment]
added support, reopen if any issues
