### ISSUE TITLE
[Bug]: different battery icons

### ISSUE THREAD

**Issue by YellowNest** [nurikk/z2m-frontend#1386]
### What happened?

Battery symbols are different for different devices. One of the aqara temperature sensors is 100% and grey icon while heiman smoke detector is 100% but green icon.

![E28F7281-6BD1-4726-96EA-88F404EE12EE](https://user-images.githubusercontent.com/59575587/155838133-6d07fd21-c0f3-4486-8fc7-608d96acdf5f.jpeg)

### What browsers are you seeing the problem on?

Safari

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by sjorge** [comment]
If I am not mistake the icons that are green have ‘battery_low’ attribute and the gray one do not.

I’m pretty sure this is intentional

**Comment by nurikk** [comment]
> If I am not mistake the icons that are green have ‘battery_low’ attribute and the gray one do not.
> 
> I’m pretty sure this is intentional

Yep, that's right

**Comment by YellowNest** [comment]
Ok! thanks for explaining this
