### ISSUE TITLE
Upload firmware file?

### ISSUE THREAD

**Issue by vk496** [nurikk/z2m-frontend#1388]
Usually, you will be always interested in the last version of the zigbee device. But sometimes I think people would like to rollback a OTA update. Cases Like:

- New features/fixes of firmware that are not supported in Z2M yet (like switch from uint32 to uint48 data type)
- Switch to a different server update (IKEA test servers) and then want go back
- Some updates permanently breaks all (IKEA binding to groups only)
- Just for fun

Right now, you can only use what is defined in the converters AFAIK

**Comment by sjorge** [comment]
Just a heads up to not get your hopes up too much, some devices will refuse to downgrade. Like for example all the IKEA buttons.

**Comment by nurikk** [comment]
Are there any api for this in z2m?
