### ISSUE TITLE
Zigbee2MQTT Map UI Improvement

### ISSUE THREAD

**Issue by skumka** [nurikk/z2m-frontend#139]
## Description
1. At the moment you can see the whole map of your network with different types of relationships based on the selected filters.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/71942616/99144579-45d4e800-2667-11eb-849f-b608fb2769e6.png">

2. You can see all devices linked to the selected router/coordinator (nice feature especially on large networks)
<img width="867" alt="image" src="https://user-images.githubusercontent.com/71942616/99144595-600ec600-2667-11eb-9888-fdb9bc8075be.png">

## Missing feature
**What you cannot do is an easy way to see all orphaned devices** (orphaned means not linked to any router or to coordinator)

## Proposal
Add a filter to highlight only orphaned devices. I ask to grey (shade) down all linked devices like it is done for all devices which are not connected to the selected router for example (like on the picture above).

Adding this feature will help to identify very quickly devices which should be re-linked because they may not work properly

**Comment by timoline** [comment]
> Adding this feature will help to identify very quickly devices which should be re-linked because they may not work properly

Maybe not only in the map, but also in another page where it list these devices
