### ISSUE TITLE
Restar button in the frontend

### ISSUE THREAD

**Issue by DJTerentjev** [nurikk/z2m-frontend#1390]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to restart Z2M

**Describe the solution you'd like**
Now menu "Zigbee2MQTT" duplicate "Devices". If it's possible better to utilize this link to exit web interface of plug-in and  access main page. 
![image](https://user-images.githubusercontent.com/1267473/156253713-1762c4e7-f960-4cac-af09-aae27acf214b.png)

**Describe alternatives you've considered**
Permanent restart button in the frontend

**Additional context**
Thank you for your time.

**Comment by nurikk** [comment]
Hi, you can bookmark link `/#/settings/tools` and within one click open this page

**Comment by DJTerentjev** [comment]
I didn't know about that button. Thank you!
