### ISSUE TITLE
[Bug]: 1.24.0 displays [object,Object] in the availability column, reverting back to 1.23.0 restores status

### ISSUE THREAD

**Issue by bagobones** [nurikk/z2m-frontend#1393]
### What happened?

1.24.0 displays [object,Object] in the availability column, reverting back to 1.23.0 restores status

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks
