### ISSUE TITLE
Title in Top left

### ISSUE THREAD

**Issue by Omniconn-ai** [nurikk/z2m-frontend#1399]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
At present the top left reference and link is Zigbee2mqtt.  Is there anyway to change this to the host name of the operating system? 

**Additional context**
I have a number of Zigbee2mqtt gateways in a building all linked to a Thingsboard instance.  I wanted to use an iframe in the dashboard to show your frontend as its seriously good and useful.  Especially the mapping feature.  Saved hours as not needing to mess with external portals to show node data.

So it's easier to see in the iframe I was wondering if the host name or a custom name can be showed so it's easy to see the gateway you are viewing.  It's more of a convenient feature.

**Comment by nurikk** [comment]
Done
