### ISSUE TITLE
wrong Firmware build date

### ISSUE THREAD

**Issue by Maik-100** [nurikk/z2m-frontend#140]
I had a problem with my CC2530. It acts a Router. So I did a firmware update to the latest
version " CC2530_router_2020_09_29.zip". 
But if I use the new Web-Gui of Zigbee2MQTT it was displayed 2018-09-26. So either there is a problem within the firmware of the router or there is a problem some were else.
I put a screenshot to this issue.

![wrong_Firmware_build_date_CC2530_Router](https://user-images.githubusercontent.com/48841828/99154736-434bb000-26b2-11eb-867f-1057a048b7d6.JPG)

**Comment by nurikk** [comment]
Nothing wrong with this, the firmware version is correct (it defined in source code, not by .zip archive name)
