### ISSUE TITLE
[Bug]: Sort on ID not possible

### ISSUE THREAD

**Issue by gizmocuz** [nurikk/z2m-frontend#1400]
### What happened?

When I was sorting on different columns (name/last seen), I noticed I was not able to sort on ID (which was the default)
Because a cookie is set, this action can not be undone without deleting the cookie.
Would be great if there was a option to sort on ID

### What browsers are you seeing the problem on?

Microsoft Edge

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Neshco** [comment]
Same here on Chrome. 
But, using never used browser before, on same PC, bring settings to default and everything is sorted by ID number.
Cleaning cookies and restarting on Chrome, where the problem persist, did not solved the problem.
Where the information about sorting is stored?

**Comment by nurikk** [comment]
This number is just number in table, and never had sorting feature

**Comment by gizmocuz** [comment]
@nurikk , okey, is it possible to display not 'just a number' but the node_id ? Or does Zigbee have no node_id's (like ZWave)
Because I actually was expecting the number to be a NodeID, or at least a incremental index number so each new node get's a higher number.
This way I can sort on ID and this gives me a list of old to new devices.
For instance I added 5 smoke alarms after each other, all different names, the only way to get them in order is by sorting on this ID

**Comment by nurikk** [comment]
There’s no such thing as node id in Zigbee
