### ISSUE TITLE
[Bug]: space characters are changed to underscores in the "manufacturer" links on the "About" page

### ISSUE THREAD

**Issue by uncle-fed** [nurikk/z2m-frontend#1401]
### What happened?

When you click on the device _Manufacturer_ link (the "About" page), you should be taken to the https://www.zigbee2mqtt.io/supported-devices/ search that lists all devices by that vendor. If the vendor name contains spaces, the frontend replaces it with underscores. But the web site is actually programmed to handle spaces rather than underscores, so it finds nothing. 

Spaces should be replaced by %20 instead of _, e.g. manufacturer Ajax Online should be https://www.zigbee2mqtt.io/supported-devices/#v=Ajax%20Online

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks
