### ISSUE TITLE
zigbee2mqtt error

### ISSUE THREAD

**Issue by hu7907** [nurikk/z2m-frontend#1404]
### What happened?

some zigbee problem boring me during a few days
today, my zigbee2mqtt device lost was lost, i dont know how to happen.
i try to restore home assistant , but the list still didnt restore back
so i just can only add all of my device again, until the problem happen

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.100:8123/api/hassio_ingress/9QSLZcWglBCjxmgQCJQgvN5DvC13FOsgDEGOdUKH68c/#/
**Previous url**: http://192.168.1.100:8123/45df7312_zigbee2mqtt


**Error type**: undefined
**Error message**: undefined
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch
