### ISSUE TITLE
Got error: i is undefined

### ISSUE THREAD

**Issue by asgeirogm** [nurikk/z2m-frontend#1410]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8326809/initialState.json.zip)
<img width="1232" alt="Screen Shot 2022-03-22 at 18 59 21" src="https://user-images.githubusercontent.com/4902537/159545874-daea870c-609f-466d-99a3-30680ae30be2.png">

I was trying to add a new device to zigbee2mqtt, specifically this [Tuya Smart Button](https://www.aliexpress.com/item/1005003379547049.html). I followed the instructions for adding a new Tuya device and when I triggered the device by clicking on the button and turning the knob, there was nothing coming in the debug log. I then went to the zigbee2mqtt menu, found the device and clicked on it, opened the "Exposes" tab and got this error.

**Current url**: http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/#/device/0x003c84fffeb14057/exposes
**Previous url**: http://192.168.0.11:8123/45df7312_zigbee2mqtt

**Error type**: TypeError
**Error message**: i is undefined

Zt@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/main.125c9bd8fa26692dd8b6.js:1:49613
ra@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1060595
Us@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1112800
El@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1100009
_l@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099937
Sl@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099798
fl@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1096785
64448/Vi/<@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046493
60053/t.unstable_runWithPriority@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1156698
Ui@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046270
Vi@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046440
Wi@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046373
Le@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1117319
Zt@http://192.168.0.11:8123/api/hassio_ingress/HO_safUCcHuN8wAAtY7nXDVeqRwlb01EZaNNfYv0K9E/scripts/vendor.a0ef53a74e6d2443acda.js:2:1025079

**Comment by nurikk** [comment]
You're using quite outdated version. Consider updating to the latest release
