### ISSUE TITLE
List endpoint name in drop-down list when adding device to a group

### ISSUE THREAD

**Issue by jarrah31** [nurikk/z2m-frontend#1411]
**Is your feature request related to a problem? Please describe.**
I have recently added [this device](https://www.zigbee2mqtt.io/devices/GL-C-008-2ID.html#gledopto-gl-c-008-2id) to Z2M which has two endpoints - cct and rgb. When I try to add these devices to a group, the endpoint dropdown list displays three numbers, but I don't know how to identify which one is cct, rgb, or both. e.g.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/3072303/159561402-5d978a77-82f4-4ce7-a416-b3c4f0014730.png">

The endpoint names are shown when looking at the device's Exposes tab:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/3072303/159561600-d5e1a1b7-8d1e-49d0-9b09-e085120c6065.png">

**Describe the solution you'd like**
Would it be possible to add the Endpoint name in the drop-down list instead of or as well as the numbers please?

**Describe alternatives you've considered**
I can't find any alternative way to identify which endpoint relates to the provided numbers

**Additional context**

Thanks in advance.

**Comment by jarrah31** [comment]
One workaround is to issue a manual Publish command and specify the endpoint name using the following:

Topic: `zigbeepi2/bridge/request/group/members/add`
Payload: `{"group": "lounge_coving_cct", "device": "lounge_coving_right/cct"}`

When I then look in configuration.yaml, I see that it's used endpoint 15
```
  '2':
    friendly_name: lounge_coving_cct
    devices:
      - 0x00124b0021138f6d/15
      - 0x00124b0021139c3e/15
      - 0x00124b002113913f/15
      - 0x00124b002113944b/15
```

I've noticed another problem with the GUI. When I attempt to remove a device within a group using the red trashcan icon, the device isn't removed. Looking at the logs I see the following entry:
```
MQTT publish: topic 'zigbeepi2/bridge/response/group/members/remove', payload '{"data":{"device":"lounge_coving_right","group":"lounge_coving_cct"},"status":"ok"
```
I suspect the GUI is trying to just remove the device with no endpoint specified which doesn't match up, because if I manually publish the following with /cct, the device is removed from the group in the GUI:

Topic: zigbeepi2/bridge/request/group/members/remove
Payload: {"group": "lounge_coving_cct", "device": "lounge_coving_right/cct"}

This can be seen in the logs too:
```
MQTT publish: topic 'zigbeepi2/bridge/response/group/members/remove', payload '{"data":{"device":"lounge_coving_right/cct","group":"lounge_coving_cct"},"status":"ok"}'
```

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by jarrah31** [comment]
Thank you for looking, please find the file attached.
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8355581/state.json.zip)

**Comment by nurikk** [comment]
Done

**Comment by jarrah31** [comment]
Thank you!
