### ISSUE TITLE
[Bug]: Paired device disappeared from GUI

### ISSUE THREAD

**Issue by tebra-jl** [nurikk/z2m-frontend#1412]
### What happened?

One of my 3 Philips 8718696485880 is no more displayed on the frontend (Devices / Dashboard / Groups tabs).
That bulb was within a group before disappearing.
That bulb is still listed on Settings -> Raw and can still be controlled with command to the group.

### What browsers are you seeing the problem on?

Firefox, Safari

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by tebra-jl** [comment]
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8334926/state.json.zip)

**Comment by nurikk** [comment]
What's group name and what's the missing device (IEEE address)?

**Comment by tebra-jl** [comment]
Group name is « dining_lights_z2m »
The device missing is "0x00178801036dc5d1": {
                "friendly_name": "Living room - Table center"

**Comment by nurikk** [comment]
Your device is indeed missing, but not from frontend. Data is missing in z2m.

<img width="508" alt="Screenshot 2022-03-25 at 8 49 23 PM" src="https://user-images.githubusercontent.com/1525421/160123689-b8789cf6-0e05-406e-ae05-b7841e6f180c.png">

**Comment by tebra-jl** [comment]
Thanks for your help.
I don’t understand in which file this device (IEEE address) must be added to be visible in frontend.
devices.yalm and groups.yalm already include it.

**Comment by tebra-jl** [comment]
So my state.json file is missing that device and the frontend don’t display that device.
But devices.yalm and groups.yalm are properly configured.
What I’m missing ?  How to fix it?

**Comment by tebra-jl** [comment]
How to remove that device from my zigbee network and re-add it after ?
