### ISSUE TITLE
problems when deleting a device '0x00158d0005d2a19e':   friendly_name: Linky              aka ZLinky_TIC

### ISSUE THREAD

**Issue by bentouspam** [nurikk/z2m-frontend#1414]
### What happened?

Since Yesterday, I couldn't attach one new device. previously removed devices could be paired without problem.
the device was a MOES wireless scene switch with 1 button.
I decided to uninstall and reinstall Zigbee2mqtt.

at the first pairing, two devices I didn't put in pairing mode where present in the device pannel.
I started to pair my routers first (Ledvent bulb) and the logfile was more and more "verbosed".
I know that the Zlinky_TIC send a lot of data in the logfile so I decided to remove it in the device pannel. then I got a WSOD
White screen of the death :-)
device apeared without any pairing action were [ZB-SW01](https://www.zigbee2mqtt.io/devices/ZB-SW01.html#ewelink-zb-sw01)
and https://www.zigbee2mqtt.io/devices/ZLinky_TIC.html#lixee-zlinky-tic

[initialState.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8351482/initialState.zip)

[zigbee2mqtt-old.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8351548/zigbee2mqtt-old.zip)

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://homeassistant:8123/api/hassio_ingress/TcAFF8cR5Kg8yajsIm2DHn7M_TLGlhAzuOi-9UVG-oo/#/
**Previous url**: http://homeassistant:8123/45df7312_zigbee2mqtt


**Error type**: undefined
**Error message**: undefined
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by xrust83** [comment]
Your problem is not related to the frontend. And you need to look for the answer to your question in the branch of the zigbee project

**Comment by bentouspam** [comment]
Thanks a lot, I didn't know from witch part was comming this "request for comments"

have a good day,
Benoit.
