### ISSUE TITLE
own description on dashboard

### ISSUE THREAD

**Issue by ConradFlux** [nurikk/z2m-frontend#1418]
Since the latest release it's possible to add your own description. I use this field to show in which room the device is located.
It would be nice to have this field to be shown on the dashboard as well.

**Comment by nurikk** [comment]
Good point, implemented

<img width="736" alt="Screenshot 2022-04-15 at 5 28 37 PM" src="https://user-images.githubusercontent.com/1525421/163554035-17da3050-c343-4903-b84d-e524830d6c4e.png">
d
