### ISSUE TITLE
Can't set homeassistant specific device settings in frontend

### ISSUE THREAD

**Issue by andrebk** [nurikk/z2m-frontend#1419]
**Is your feature request related to a problem? Please describe.**
The zigbee2mqtt documentation describe [how to set homeassistant specific device settings](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#using-a-custom-name-for-the-device-and-entities), e.g. the name to be used in home assistant. However there is no way to set these settings in the device settings in the front end (that I've found at least).

Being able to set this in the frontend along with all the other settings would be very nice, and a much better experience then editing the configuration file that is constantly overwritten by changes in the frontend.

**Describe the solution you'd like**
Home Assistant specific device settings are added to the settings page for each device.

**Describe alternatives you've considered**
The only alternative I can think of is adding this information manually in the configuration yaml file(s). However, since there is no "reload config" button in the frontend (again, that I know of) this means that z2m will have to be restarted to load these changes. And since the frontend keeps overwriting my config files I am reluctant to do this for 50+ devices. 

If this is the intended approach I would love to be pointed in the direction of some info on when and why the config files are overwritten, so I can do this with a little confidence that it won't be wiped halfway through by something I didn't understand.

**Additional context**
Tested in:
zigbee2mqtt **1.24.0**
frontend version **0.6.76**

**Comment by nurikk** [comment]
it's right there
<img width="136" alt="Screenshot 2022-04-15 at 8 05 32 PM" src="https://user-images.githubusercontent.com/1525421/163568803-2577d78a-c793-42f3-9349-d00302ac7bba.png">

<img width="469" alt="Screenshot 2022-04-15 at 8 05 47 PM" src="https://user-images.githubusercontent.com/1525421/163568792-979f3d37-4c56-4fb4-beb6-3343ec0a860c.png">

**Comment by andrebk** [comment]
@nurikk Istill don't understand how it's "right there". I see a field for the friendly name, but that is not the same as the home assistant name:
```
devices: "0x12345678": 
  friendly_name: living_room/temperature_sensor 
  homeassistant: 
    name: Living Room Temperature Sensor
```

`friendly_name` and `homeassistant.name` are two different fields, and they don't have to have related/matching values I think . I only see the field for changing the `friendly_name` that you screenshotted in the UI, and it's not clear to me how the "update home assistant entity" checkbox is related to either field.
