### ISSUE TITLE
[Bug]: Device settings page has confusing whitespace

### ISSUE THREAD

**Issue by andrebk** [nurikk/z2m-frontend#1420]
### What happened?

The device settings page has a bunch of options, usually with an input box or checkbox. Above(?) the input element is a description of the setting. However, oftentimes the whitespace above and below a setting is very similar, and it is hard to tell which description belongs to which input element.

For example in this screenshot:
![image](https://user-images.githubusercontent.com/18532709/160684564-4f468468-9166-4bfd-ac56-f154e471b1ac.png)

1. The friendly name input box has less whitespace to "Retain MQTT messages of this device" below than actual description above
2. "Retention" title is right next to "Retention" checkbox, so clearly they look like they belong together even though that's wrong
3. "QoS" description is a text input. It has  little whitespace up to the textbox above, and larger whitespace to the one below, so it looks like it should be entered into the box above.

Another screenshot from the debounce section: 
![image](https://user-images.githubusercontent.com/18532709/160685907-60252110-4717-40ff-ac68-b8b3f240d0c0.png)

1. I honestly don't know if I've screenshot the correct region here, because I'm so confused as to what goes where
2. There is a big divider line in the middle. That makes me think that the things above and below the divider are not related, but it looks like they are? Makes it look like the text input above is for "Ignore debounce".
3. I have no idea which input the big `+` icons belong to

I hope I don't come off to negative here, I just want to try explain how I find this page confusing.

It looks to me like this code is autogenerated from a schema and is still using the default styling (or is maybe styled for another browser, I've only tested on firefox). Hopefully that means it should be fixable with only some CSS magic.

### What browsers are you seeing the problem on?

Firefox

### Relevant stacktrace

```shell
N/A
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
We're using external [library](https://github.com/rjsf-team/react-jsonschema-form) with [bootstrap4 theme](https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages/bootstrap-4) to generate this page, and it's not fully compatible with bootstrap5. If you can help with making things look nice, it much appreciated

**Comment by nurikk** [comment]
I’ve done one iteration over this issue. Should be better in latest dev branch
