### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Tntdruid** [nurikk/z2m-frontend#1421]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hello,

Can you add Danish to the Translation site?

https://poeditor.com/join/project?hash=Az88waAhPd

**Comment by nurikk** [comment]
Hi, here is reference PR how to do that

https://github.com/nurikk/zigbee2mqtt-frontend/commit/78730a54bb7543468cf5699f278859b20c622b09
