### ISSUE TITLE
Force language

### ISSUE THREAD

**Issue by zbyrek** [nurikk/z2m-frontend#1434]
**Is your feature request related to a problem? Please describe.**
I would like to have option to force language and not just autodetect option.

**Describe the solution you'd like**
There is language option in settings menu, but there is only link for translations, there could be list with languages.

**Describe alternatives you've considered**
It could be also set by config file.

**Additional context**
There is trasnaltion for my language but i prefer using English.

**Comment by zbyrek** [comment]
Found that option, sorry for bothering.

**Comment by Impact123** [comment]
Even though it's obvious, It's a custom when asking for help to share how you solved your problem. Others might have the same question and finding this existing issue will not help them solve it.

**Comment by zbyrek** [comment]
There is option to change language at the top of the site, it is represented by country flag I expected it to be in the settings so overlooked it.
I thought it was obvious for everyone else, that's why i didn't describe how I solved "issue".
