### ISSUE TITLE
Feature request: Show timestamp in logs tab

### ISSUE THREAD

**Issue by Impact123** [nurikk/z2m-frontend#1436]
**Is your feature request related to a problem? Please describe.**
The problem is that the log rows in the `Logs` tab are missing a timestamp.

**Describe the solution you'd like**
I'd like to be able to enable that a timestamp is shown in the log row similar to how (when configured) the Zigbee2MQTT logs do it.

The message would look like this example from my Zigbee2MQTT logs
```
debug 2022-04-12 11:36:19: Received Zigbee message from
```
instead of this example from the `Logs` tab
![image](https://user-images.githubusercontent.com/899193/162932695-c2ab47da-e618-4bd5-a9a4-4b5b3622966b.png)

**Additional context**
This has already been requested together with other enhancements in #451 but it seems like it wasn't picked up.

**Comment by nurikk** [comment]
done

**Comment by Impact123** [comment]
Works as expected. Thank you! Very much appreciated.
