### ISSUE TITLE
[Bug]: Item remove button on settings page for setting/options like debounce_ignore does nothing

### ISSUE THREAD

**Issue by Impact123** [nurikk/z2m-frontend#1456]
### What happened?

# Problem
The red `-` button in the device's `Settings` page for options like `ignore_debounce`, `filtered_optimistic`, `filtered_attributes` does not remove the item.

Clicking the `-` here will do nothing. At least not after it was saved.
![image](https://user-images.githubusercontent.com/899193/163869564-93a3f279-9ade-44c4-bd62-ade8403ce0d1.png)

Writing the options via MQTT like
```json
{
    "id": "mydeviceid",
    "options": {
        "debounce_ignore": null,
        "filtered_optimistic": null,
        "filtered_attributes": null
    }
}
```
to `zigbee2mqtt/bridge/request/device/options` works fine.

# How to reproduce
1. Go to a device's `Settings` tab.
2. Add a `Ignore debounce` option.
3. Save/Submit
4. Click the `-` to attempt remove the option 

# Expected behavior
I expected the option to be removed

# Proposed solution
Remove the option. Set it to `null` when it's the last to remove it completely

# Further information
## Tested with
|Software | Version  |
|--|--|
| **Zigbee2MQTT** | `1.25.0-dev` ([8c4312d](https://github.com/Koenkk/zigbee2mqtt/commit/8c4312d)) |
|**Frontend**|`0.6.83` |
|**Chrome**|`100.0.4896.88`|

# Addendum
It's not a bug but it would be nice if other options could be reset/removed too. You can't remove the `icon`, for example.

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by sammyke007** [comment]
I can confirm this. Had to manualy edit my config file.

**Comment by Impact123** [comment]
Bump to keep the bot happy. This is still an issue.

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
I must've missed to unstale this. Please reopen. This is still an issue.
