### ISSUE TITLE
[Bug]: Option `scene_add` missing on the frontend?

### ISSUE THREAD

**Issue by Grandma-Betty** [nurikk/z2m-frontend#1464]
### What happened?

As desribed in the official documentation ([Scenes | Zigbee2MQTT 4](https://www.zigbee2mqtt.io/guide/usage/scenes.html#scenes)), both ways to create a scene within Zigbee2MQTT (`scene_store` and `scene_add`) are also possible via the frontend:

![1](https://user-images.githubusercontent.com/48346793/166137437-18a08730-551b-4d6e-9b66-ca9c0051eac5.png)

But I am only able to find the option for `scene_store` within a device group or within a single device via the frontend...

![2](https://user-images.githubusercontent.com/48346793/166137617-32c3cf8a-f996-4506-b98f-572a5a4ad8cd.png)

...while I was not able to find the `scene_add` option via the frontend.

I am a Z2M newbie so I'm not sure if the `scene_add` option has ever been available via the frontend and therefore I'm unsure if it's a bug or not for that option not showing up.
Or am I missing something?
Thank you in advance!

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
scene_add was never implemented in fronted. It’s little bit useless compared to scene_store

**Comment by Grandma-Betty** [comment]
> scene_add was never implemented in fronted. It’s little bit useless compared to scene_store

Thanks for the response. But how would it be useless? The official documentation linked above says that `scene_add` has its advantages over `scene_store` as it lets you "_control which attributes will be stored in the scene (e.g. only brightness) and it's possible to set a transition time._"
This is also what I have mentioned <del>which is especially useful when you have multiple devices in a group and you want to have the **exact(!)** same brightness/color setting for all devices.</del>

**Comment by nurikk** [comment]
Idea behind current implementation is following: you configure all devices in group how do you like, then click store and bob’s your uncle, everything is working.

**Comment by nurikk** [comment]
Anyway if you’re willing to implement and submit PR, it’s always welcome
