### ISSUE TITLE
[Bug]: UI frontend blank after upgrade to 1.25.1-1

### ISSUE THREAD

**Issue by blacknell** [nurikk/z2m-frontend#1465]
### What happened?

I upgraded to 1.25.1-1 (previously 1.25.0-1) and the UI front end is blank. No errors in log.
Z2M still working itself, though
Front end works in safari

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by blacknell** [comment]
[state copy.json.txt](https://github.com/nurikk/zigbee2mqtt-frontend/files/8601584/state.copy.json.txt)

**Comment by smartmints** [comment]
I am using Edge browser. Go to browser settings and clear cached images and files.  Restart browser. This solved the problem.

**Comment by smartmints** [comment]
![image](https://user-images.githubusercontent.com/94444883/166223999-4e88abd3-a0aa-4af7-af6d-1948844c4b31.png)

**Comment by almirus** [comment]
same 
![image](https://user-images.githubusercontent.com/16898685/166229935-10c3a81e-c4e8-4da8-9ef9-929555f9f058.png)

**Comment by blacknell** [comment]
Also not working on home assistant mobile app

**Comment by blacknell** [comment]
fixed on chrome (by deleting cached files).
But I don't know how to do equivalent on HA Mobile App

**Comment by mojaki8286** [comment]
For the HA App on mobile. Goto Settings->Apps->(search HA)->Storage and Cache->Clear Cache. Restart  app
