### ISSUE TITLE
[Bug]: Map not opening when there is a error in the log file

### ISSUE THREAD

**Issue by vangguppie** [nurikk/z2m-frontend#1469]
### What happened?

After upgrade from 1.24.0-1 to 1.25.1 the map is not loading when there is a error in the log file. Same behavior from 1.25.0 to 1.25.1.

I have gledopto devices that sometimes give a error on LQI command. Prior to 1.25.1 map was functioning. 

### What browsers are you seeing the problem on?

Chrome, Safari

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by vangguppie** [comment]
[state.json-2.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8732222/state.json-2.zip)
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8732223/state.json.zip)

state.json = 1.25.0
state.json-2=1.25.1-1
