### ISSUE TITLE
Nginx proxy pass

### ISSUE THREAD

**Issue by jondavidsson** [nurikk/z2m-frontend#147]
I had some issues with proxy pass in nginx. I just recently started working with nginx so consider me a newbie.

The proxy pass example at https://www.zigbee2mqtt.io/information/frontend.html didn't work for me, maybe because it uses a subdomain(?). And since my goal was to have a proxy pass from user.example.com/zigbee it didn't work if I didn't add a trailing slash, user.example.com/zigbee/

For me to get it to work without the trailing slash I had to add this line in location:
rewrite ^([^.]*[^/])$ $1/ permanent;

Don't know if this is a correct way of doing it, but if it is, it might be a good idea to add it to the example for others who encounter the same issue.

**Comment by thehijacker** [comment]
> I had some issues with proxy pass in nginx. I just recently started working with nginx so consider me a newbie.
> 
> The proxy pass example at https://www.zigbee2mqtt.io/information/frontend.html didn't work for me, maybe because it uses a subdomain(?). And since my goal was to have a proxy pass from user.example.com/zigbee it didn't work if I didn't add a trailing slash, user.example.com/zigbee/
> 
> For me to get it to work without the trailing slash I had to add this line in location:
> rewrite ^([^.]*[^/])$ $1/ permanent;
> 
> Don't know if this is a correct way of doing it, but if it is, it might be a good idea to add it to the example for others who encounter the same issue.

Hello. I have same problem. How to do reverse proxy in nginx when I wish to have subfolder in url like: https://domain.com/zigbee.

I tried your solution but it does not work for me. Can you post entire location config?

Thank you.

**Comment by jondavidsson** [comment]
This is what’s working for me:

`location /zigbee {
                proxy_pass http://127.0.0.1:8080/;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                rewrite ^([^.]*[^/])$ $1/ permanent;
                auth_basic "Login";
                auth_basic_user_file /path-to/.htpasswd;
}
`

**Comment by thehijacker** [comment]
Now it is working. Here is my config if someone else finds it useful:

```
    location /zigbee {
        proxy_pass http://192.168.28.50:8080/;
        rewrite ^([^.]*[^/])$ $1/ permanent;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        auth_basic              realm_name;
        auth_basic_user_file    /etc/nginx/.passwords.list;
    }

    location ^~ /zigbee/api {
        proxy_pass       http://192.168.28.50:8080/api;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

```
Thank you.
