### ISSUE TITLE
Add the ability to change the name of the web frontend from the standard Zigbee2MQTT to a custom one.

### ISSUE THREAD

**Issue by solalex1** [nurikk/z2m-frontend#1472]
If there are several zigbee2mqtt servers, you can get confused which server it belongs to. I propose to put a separate variable in the configuration file, which should replace the standard <title>Zigbee2MQTT</title>

**Comment by nurikk** [comment]
This change will require support from z2m side. Meanwhile you can add window.location.host into <title/>


same was done here, for iframe https://github.com/nurikk/zigbee2mqtt-frontend/blob/78bb6d6058ea1ca6370f3a8c486b458fd4e233c7/src/components/navbar/index.tsx#L114
