### ISSUE TITLE
frontend device page crash

### ISSUE THREAD

**Issue by liveris17** [nurikk/z2m-frontend#1480]
### What happened?

front-end crash
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8702244/initialState.json.zip)

### What browsers are you seeing the problem on?

Firefox

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.50:8081/#/
**Previous url**: 


**Error type**: undefined
**Error message**: undefined
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Burki24** [comment]
Same here, after last dev-Update from Zigbee2mqtt. Frontend isn't reachable:
```
Mai 17 10:14:00 raspberrypi npm[189087]: (node:189087) UnhandledPromiseRejectionWarning: TypeError: name.orig.at is not a function
Mai 17 10:14:00 raspberrypi npm[189087]:     at check (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:94:19)
Mai 17 10:14:00 raspberrypi npm[189087]:     at Frontend.gzipStatic (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:54:16)
Mai 17 10:14:00 raspberrypi npm[189087]:     at runMicrotasks (<anonymous>)
Mai 17 10:14:00 raspberrypi npm[189087]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Mai 17 10:14:00 raspberrypi npm[189087]: (node:189087) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

```

It's a main problem. There are several Users, trying to reach the FrontEnd after an update and no chance. 
@nurikk Can you confirm, that there is an error inside? Zigbee2mqtt is running normaly, but Frontend will not be reachable.

**Comment by peteralm097** [comment]
Hi
My frontend has also become unreachable - just endless loading. Zigbee2mqtt seems to be working fine with lights and logging all working ok. I am on the dev branch of zigbee2mqtt, I can't see any errors in the zigbee2mqtt logs although I will up the logging verbosity this evening and see if that shows anything.

**Comment by nurikk** [comment]
Can you guys restart your z2m instance? And make sure that you have run `npm ci` after git pull

**Comment by Burki24** [comment]
> Can you guys restart your z2m instance? And make sure that you have run `npm ci` after git pull

Did'nt need that in the past, as I use the normal Update-process from zigbee2mqtt dev. Frontend isn't installed extra. And it always runs a `npm ci` after finished update-process.

@nurikk restarted the complete RPI with no effect.

@peteralm097 use a second shell and make: `sudo journalctl -u zigbee2mqtt.service -f
`
After that, you can restart zigbee2mqtt in the first shell and will find the startlog in the second shell.

**Comment by Impact123** [comment]
I had to run the frontend in dev/standalone mode to get something somewhat useful in the developer console. It was a fresh deployment so `npm ci` was used. Maybe this helps finding the issue.
```
LazyImage @ index.tsx:36
react-dom.development.js:20085 The above error occurred in the <LazyImage> component:

at LazyImage (http://localhost:3030/main.5d374424519a0a2495f7.js:1606:13)
at Suspense
at div
at DeviceImage (http://localhost:3030/main.5d374424519a0a2495f7.js:1619:80)
at Cell (http://localhost:3030/main.5d374424519a0a2495f7.js:6462:19)
at td
at tr
at tbody
at table
at Table (http://localhost:3030/main.5d374424519a0a2495f7.js:4104:18)
at div
at div
at DevicesTable (http://localhost:3030/main.5d374424519a0a2495f7.js:6441:13)
at DevicesPage (http://localhost:3030/main.5d374424519a0a2495f7.js:6549:13)
at c (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:120773:708)
at I18nextWithTranslation (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:106992:31)
at ErrorBoundary (http://localhost:3030/main.5d374424519a0a2495f7.js:845:9)
at Route (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:108666:29)
at Switch (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:108868:29)
at div
at main
at div
at Router (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:108297:30)
at HashRouter (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:107968:35)
at ThemeSwitcherProvider (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:80155:23)
at r (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:120773:179)
at InnerContextProvider (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:367:23)
at Provider (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:376:23)
at I18nextProvider (http://localhost:3030/scripts/vendor.1d91c7c64e9d02d788c6.js:106605:19)
at Main
```
Please let me know if you need more information

**Comment by Burki24** [comment]
@nurikk 

started z2m and the following error comes, evertime, I try to call the Frontend within a browser (firefox, chrome, edge):

```
(node:2790) UnhandledPromiseRejectionWarning: TypeError: name.orig.at is not a function
    at check (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:94:19)
    at Frontend.gzipStatic (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:54:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by Burki24** [comment]
@nurikk 
is there anything we can do to help? This problem consist after the last update from today:

```
(node:11012) UnhandledPromiseRejectionWarning: TypeError: name.orig.at is not a function
    at check (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:94:19)
    at Frontend.gzipStatic (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:54:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
I made a complete update-process and a restart and a complete reboot of the RPI.

thanks & greetz
Burkhard

**Comment by nurikk** [comment]
> @nurikk is there anything we can do to help? This problem consist after the last update from today:
> 
> ```
> (node:11012) UnhandledPromiseRejectionWarning: TypeError: name.orig.at is not a function
>     at check (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:94:19)
>     at Frontend.gzipStatic (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:54:16)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:11012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> ```
> 
> I made a complete update-process and a restart and a complete reboot of the RPI.
> 
> thanks & greetz Burkhard

[this](https://github.com/Koenkk/zigbee2mqtt/pull/12525) should help (one of z2m dependencies got updated and new version has bug)

**Comment by Burki24** [comment]
Thanks a lot. All things work fine.
