### ISSUE TITLE
Search for description text [feature request]

### ISSUE THREAD

**Issue by Bascht74** [nurikk/z2m-frontend#1497]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I entered a lot of descriptions, e.g. the battery change. I would be nice if I am able to search for text in the descriptions. This way you could search for 05.2021 and find every device with a battery change in may 2021...

**Describe alternatives you've considered**
If you enter text of the descriptions it doesn't find it, so you have to use the browser search, but that doesn't filter it (> 100 devices).

**Additional context**
./.

**Comment by nurikk** [comment]
Here we go buddy, shipped with 0.6.97

**Comment by Bascht74** [comment]
Thx a lot
