### ISSUE TITLE
Consistent Dark mode

### ISSUE THREAD

**Issue by extremelyonline** [nurikk/z2m-frontend#1503]
**Is your feature request related to a problem?**

The dark mode toggle seems to be per session only.

**Describe the solution you'd like**
A config/docker env to set the default theme setting

**Comment by DirkStorck** [comment]
Hi,

where do I find that toggle? 

Thank you!

EDIT: ok found it 

![grafik](https://user-images.githubusercontent.com/2306190/184835007-ac9acc0c-cfcc-4a37-bd05-163fb7ef8bfb.png)

**Comment by KameDomotics** [comment]
Hi, with the latest version of Zigbee2mqtt (1.33.0-1) I also have this problem, dark mode toggle seems to be per session only.
Is it possible to set the day mode permanently? Thanks

**Comment by kszys** [comment]
#metoo - I hate the dark mode and hate having to toggle it all the time...

**Comment by ur7x** [comment]
Yes add me to the list as well.. would like a config variable setting that sets it to either light or dark mode.

**Comment by verticalsoft** [comment]
I can also confirm this defaults to black/dark every time you go in now.

**Comment by josemaX** [comment]
Same here, but this happens from some HA 2023.8.x, before these releases it worked fine (never seen dark mode before).

It happens both Web browsers and HA Companion app (iPadOS at least)

**Comment by kszys** [comment]
Just started using Z2M, so not sure how it was before - but it happens
indeed in the web browsers and also the Android app.

**Comment by Oleg-Sob** [comment]
Please make a light theme by default.

**Comment by lee-costa** [comment]
Any update on this? Still happening…

**Comment by Oleg-Sob** [comment]
Try rebooting the system, it worked for me.

**Comment by kwetnico** [comment]
Hi same problèm with update 1.33.1..
@Koenkk  it's possible to correct this ?

**Comment by WarC0zes** [comment]
> Try rebooting the system, it worked for me.

Hi,
rebooting HA or rebooting machine ?
For HA, no effect :(

**Comment by Oleg-Sob** [comment]
Rebooting the entire machine.

**Comment by KameDomotics** [comment]
> Rebooting the entire machine.

No effect, it doesn't work

**Comment by Oleg-Sob** [comment]
Try running it in another browser and clear the cache and cookies.

**Comment by ur7x** [comment]
Doesn't do it in Chrome, but it does in the current version of FireFox

On my system if I used my internal IP in FireFox it does it... If I use my external IP (again in FireFox) it is normal.   really weird.
