### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by kharder-dk** [nurikk/z2m-frontend#1505]
I would like to help translate the frontend to danish but the danish language is not created in POEditor.

**Comment by nurikk** [comment]
Hello, here's example how to bootstrap new localisation
https://github.com/nurikk/zigbee2mqtt-frontend/commit/78730a54bb7543468cf5699f278859b20c622b09

**Comment by NicolaiPetri** [comment]
@kharder-dk  If you need help for bootstrapping language just reach out to me. I can help with this.
