### ISSUE TITLE
Restarted 4 bulbs at the same time

### ISSUE THREAD

**Issue by MegoVaTx** [nurikk/z2m-frontend#1507]
### What happened?

Restarted 4 bulbs at the same time

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://192.168.1.2:8123/api/hassio_ingress/cE5DtuEV72gBWrS_hY2y2O-3FH14Lr0Mef3hls2RQ-o/#/
**Previous url**: https://192.168.1.2:8123/45df7312_zigbee2mqtt_edge/dashboard


**Error type**: undefined
**Error message**: undefined
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by MegoVaTx** [comment]
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/8971920/initialState.json.zip)

**Comment by nurikk** [comment]
Hi, can you try to update to the latest release version?
