### ISSUE TITLE
Can't serve Z2M on a custom domain

### ISSUE THREAD

**Issue by denysdovhan** [nurikk/z2m-frontend#1510]
### What happened?

I'm trying to expose Z2M on a custom domain, let's say `mydomain.com`.

I've set up a Nginx Proxy Manager configuration forwarding from `zigbee.domain.com` to local `192.168.0.x:8080`. When I try to open `192.168.0.x:8080` it works fine and frontend loads.

However, when I'm trying to open `zigbee.domain.com` I get an empty page and an error message in a console:

```
Uncaught SyntaxError: Invalid or unexpected token (at index.5094f535.js:1:5493)
```

I have tried configuring an auth-token and url, like this, but it doesn't help:

```yaml
frontend:
  auth_token: super-secred
  url: https://zigbee.domain.com
```

The issue is present in Chrome, Safari, and Firefox.

Dump of state: [state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9021285/state.json.zip)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant stacktrace

```shell
Uncaught SyntaxError: Invalid or unexpected token (at index.5094f535.js:1:5493)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by denysdovhan** [comment]
I rolled back from `1.25.2` to `1.25.1` and it works fine.

**Comment by nurikk** [comment]
hi, have you tried following this manual?

https://www.zigbee2mqtt.io/guide/configuration/frontend.html#nginx-proxy-configuration

**Comment by denysdovhan** [comment]
I did. But this docs doesn't seem relevant, since the issue is present in Firefox as well as in Webkit browsers.

**Comment by lexiismadd** [comment]
I'm also experiencing this issue on a custom domain.  The frontend shows no devices or anything

**Comment by nurikk** [comment]
> I did. But this docs doesn't seem relevant, since the issue is present in Firefox as well as in Webkit browsers.

do you have basic http authentication enabled?

**Comment by lexiismadd** [comment]
I don't

**Comment by denysdovhan** [comment]
The issue was resolved for me.

**Comment by YKPDang** [comment]
> The issue was resolved for me.

https://xkcd.com/979/
