### ISSUE TITLE
Add the ability to permit join to coordinator

### ISSUE THREAD

**Issue by drjjr2** [nurikk/z2m-frontend#1515]
**Is your feature request related to a problem? Please describe.**
Some Aqara devices are particular about their route to the coordinator. One workaround for this is to force them to join the network with the coordinator rather than any router. After that they do not attempt to reroute and will stay joined with the network.

**Describe the solution you'd like**
Add the coordinator to the list of routers under "Permit Join"

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nurikk** [comment]
Hello, if you click Permit join button it will open join only on coordinator

**Comment by drjjr2** [comment]
> Hello, if you click Permit join button it will open join only on coordinator

I don't have that as an option. I have "all" and then all of the routers and light bulbs. Any thoughts on why I wouldn't have the coordinator as an option? It's a SONOFF Zigbee 3 USB Dongle.

**Comment by nurikk** [comment]
If I send 0x0000 as target will it enable joint only on coordinator? @Koenkk

**Comment by Koenkk** [comment]
@nurikk yes!

**Comment by nurikk** [comment]
Should be good now, can you try on latest dev? @drjjr2

**Comment by drjjr2** [comment]
> Should be good now, can you try on latest dev? @drjjr2

I'm not cool enough to have the edge version installed yet. Let me see about getting that installed.
