### ISSUE TITLE
[Feature request]: Control groups from frontend

### ISSUE THREAD

**Issue by aofc** [nurikk/z2m-frontend#1516]
It would be nice if we could control groups (change brightness, turn on/off devices, etc.) from the frontend. At this time, when clicking on a group, I get the list of its member devices and can control each of them individually, but that defeats the purpose of them being in the same group...

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.
