### ISSUE TITLE
[Bug]: Color conversion from RGB to XY and vice versa

### ISSUE THREAD

**Issue by ptvoinfo** [nurikk/z2m-frontend#1518]
### What happened?

Zigbee2Mqtt (zigbee-herdsman-converters/lib/color.js) and Frontend (color-convert) use different formulas to convert from RGB to XY and vice versa. 

It looks like the implementation in Z2M is more relevant to real Zigbee devices.

Probably, you can add the "rgb" mode to the color editor because Z2M can internally convert RGB to the necessary ColorXY or HSV value.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant stacktrace

```shell
None
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by ptvoinfo** [comment]
Check

> Hi, try to switch to the latest dev branch
> 
> https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

Checked. It works correctly now. Thank you!
