### ISSUE TITLE
[Feature request]: House plan as background for device map?

### ISSUE THREAD

**Issue by TommySharpNZ** [nurikk/z2m-frontend#1520]
Once we have a few devices the current map becomes less useful epsecially if you are trying to figure out where network range is dropping off.

I'd like to be able to use a plan of my house as the background for the map and drag zigbee devices to where they are physically located on the map. Then I could truly see where black spots are in my zigbee network.

No other alternatives exist...

This would be a GREAT feature!.

**Comment by nurikk** [comment]
How do you create house plans?

**Comment by TommySharpNZ** [comment]
floorplanner.com is one way to do it.

**Comment by pedjas** [comment]
This would be really helpful.
