### ISSUE TITLE
[Bug]: Device specific *_calibration settings do not accept negative numbers

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#1521]
### What happened?

You can set a negative number for the `*_calibration` settings manually in *configuration.yaml* and they get applied correctly. A you can see [here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/64a2e2381aa12df9839e0279a721043b6436945d/lib/utils.js#L88) this does a simple `value + calibration` so 25 + -1 = 24 as expected.

However the frontend does not let you enter a value that is smaller than 0. It will however display a negative number just fine when it comes from the configuration file, but you can't update it without changing it to a positive number.

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by sjorge** [comment]
Seem to only effect firefox on iOS, works fine on desktop.

**Comment by Impact123** [comment]
When the field is empty I can't input `-` either. I first have to write `0.5`, for example, then move the cursor to the start and write `-`. Does that work for you?

**Comment by sjorge** [comment]
Yeah I can get it to work on PC, just not on iOS, it also gives me a numeric input pad so I think it just tries to be smart based on the input field.

Works fine on firefox on macOS, hence me closing it.
