### ISSUE TITLE
[Bug]: Battery symbol shows full while % is very low

### ISSUE THREAD

**Issue by bverkron** [nurikk/z2m-frontend#1523]
### What happened?

Several devices currently have a very low battery (all < 20%) and are flashing but most of them still show the battery full icon which contradicts it status.

This screenshot was taken mid-blink (so they icons show slightly transparent) with the column shorted by battery %. So the one with the tool tip at the top is the highest of all of them. The rest below are 15% or lower, going all the way down to last one which is 11%. That is the only one that shows a low / empty battery symbol

![image](https://user-images.githubusercontent.com/19174503/182048594-747d672f-004a-400f-bd6e-964f81e47ba7.png)

You can also see that one entry that actually shows a low battery symbol is at 21% while another that's at 16% shows a full battery icon.
<img width="322" alt="Screen Shot 2022-08-01 at 10 56 57 AM" src="https://user-images.githubusercontent.com/19174503/182212234-b0425cec-a0d3-4e4d-8ee8-8af11e12fd7d.png">
<img width="323" alt="Screen Shot 2022-08-01 at 10 57 02 AM" src="https://user-images.githubusercontent.com/19174503/182212279-4c3b8632-11a9-42bc-98bc-1027dbe901c1.png">

### HA Addon version

1.26.0-1

**Edit**: Just upgraded to 1.27.0-1 and same issue. Also switched to edge version ([this is the commit I'm on](https://github.com/Koenkk/zigbee2mqtt/commit/c2faa3815a251c331331d49a9b43172fede026fa), I think) because of another issue and battery icons are still doing the same thing.

### Platform

Version | core-2022.7.7
Host Operating System | Home Assistant OS 8.4
Supervisor Version | supervisor-2022.07.0

### Logs of the issue (if applicable)

n/a

### What browsers are you seeing the problem on?

Chrome, Safari

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by bverkron** [comment]
state.json with personal info redacted (******)
[state-redacted.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9236177/state-redacted.json.zip)

**Comment by nurikk** [comment]
Hi, can you share screenshot from Raw tab?

**Comment by bverkron** [comment]
> Hi, can you share screenshot from Raw tab?

[raw.txt](https://github.com/nurikk/zigbee2mqtt-frontend/files/9244375/raw.txt) (redacted personal info)

**Comment by sjorge** [comment]
Is this not because the sensors with the green battery also have a `battery_low` property an as long as that is not asserted to true it shows as green 100% full ? I remember it at least being the case since the very beginning.

**Comment by nurikk** [comment]
in this case we have following state:

```
"battery": 16,
"battery_low": false,
```
this is why it's green with 16%

**Comment by bverkron** [comment]
There's a contradiction here then. It seems like the % is considered low by the frontend (not sure what the "low" threshold is) thus the icon is blinking (I assume blinking indicates a low battery), but because the `battery_low` state is false it shows a full battery? Seems like the frontend is using it's own definition of "low" that's different than what the devices is reporting via `battery_low`.

Additionally just because a battery isn't low as defined by "battery_low" doesn't mean it should be show at 100%.

Seems logical to set the [battery icon](https://fontawesome.com/search?q=battery-&c=energy&s=solid) based on the % (`battery` attribute) and the blink based on the `batter_low` if present or % if not present.

**Comment by Impact123** [comment]
Unstale.

**Comment by bverkron** [comment]
@nurikk, @sjorge looks like this got auto-closed (despite the recent comment 9 days ago to keep it open). Looks like the issue is still there in the latest release. The bot added `wontfix` but not sure what the official decision on this is. Seems like a consistency issue to me based on my [comment above](https://github.com/nurikk/zigbee2mqtt-frontend/issues/1523#issuecomment-1211477064)

![image](https://user-images.githubusercontent.com/19174503/197256732-d40e69e9-c823-478c-b5c3-4e5a6448660b.png)

Also interesting that the actual percentage is show once it drops below 10% (I think).
