### ISSUE TITLE
[Feature request]: warning when using "umlaute" in Name or Location

### ISSUE THREAD

**Issue by mmattel** [nurikk/z2m-frontend#1525]
**Is your feature request related to a problem? Please describe.**
When adding content to a device name or location, a warning should appear when using "umlaute" like äöüÄÖÜ or similars from other languages. This is relevant when using Home Assistant, as of 2022.08, the discovery fails with a warning message containing: `Received message on illegal discovery topic` It drove me nuts finding out... There is no need to prevent, but a warning would be very helpful.

**Describe the solution you'd like**
When a special character (umlaut or others) is recognized in the name or location of a device when applying, a warning would be helpful telling that this name might get issues when using HA.

**Describe alternatives you've considered**
Adding a note in the documentation, but this might get overseen easily and is not an elegant solution.

**Additional context**
When naming the device using standard ascii, it was immediately recognized by HA.

**Comment by nurikk** [comment]
We have friendly name validation code in z2m codebase. Should be easy to implement umlaut validation there

@Koenkk

**Comment by Koenkk** [comment]
@mmattel what characters are supported?

**Comment by mmattel** [comment]
Good question. I only have experience with german umlauts which did not work with mqtt HA discovery. But I highly guess that the issue also exists when using languages like french or spanish which have accents or nordic languages or even cyrillic - without having it tried...
Regarding umlaut: `äöüÄÖÜß` which can be replaced by ae, oe, ue, ss.
This is maybe similar in other latin based langauges.

**Comment by Koenkk** [comment]
@emontnemery see discussion above, what characters are supported for the topic?
