### ISSUE TITLE
search/filter on dashboard

### ISSUE THREAD

**Issue by bartplessers** [nurikk/z2m-frontend#1527]
Possible to have a "search box" on top of the Dashboard (just like on the Devices tab)?

Something like:
![2022-08-09_10-10-26_searchbox](https://user-images.githubusercontent.com/10470708/183619488-8e33914a-fb45-4fae-8396-73e5dbda0996.png)

kind regards,
B

**Comment by leroyloren** [comment]
I would be happy for the clear button.

![obrazek](https://user-images.githubusercontent.com/57643470/185747954-0e76c682-9027-4ead-ab45-5efc8a52e4c3.png)

**Comment by nurikk** [comment]
In progress

**Comment by nurikk** [comment]
Got landed in latest dev
