### ISSUE TITLE
Sort on "Power": possible to have connected devices after full batteries

### ISSUE THREAD

**Issue by bartplessers** [nurikk/z2m-frontend#1528]
Hi,

If I sort on "Power", the ascending sortorder is 
1. connected devices
2. low battery
3. full battery

In example:
![2022-08-10_8-52-38](https://user-images.githubusercontent.com/10470708/183834767-bed18015-372e-46e0-bc24-c60ce8330953.png)

I use this often to see which devices need  the battery replaced.
Those are now situated between "connected" and "full".

For me it is more logic to have following sortorder:
1. low battery
2. full battery
3. connected devices

In that way the most critical device is on top.

thanx for considering this,

kind regards,
Bart

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.
