### ISSUE TITLE
[Bug]: EnOcean PTM215Z devices, missing in MAP scan

### ISSUE THREAD

**Issue by delinend** [nurikk/z2m-frontend#1536]
### What happened?

Hi.

I'm using the last DEV branch, an just added som EnOcean PTM215Z button devices.
They ALL works just fine. An there is no problems with MQTT to ny Domoticz.

The only problem I see, is if I make a MAP scan in the frontend, all my EnOcean PTM215Z devices, are NOT showing in the MAP ?!?

I can fine see them all in the "Device" and "Dashboard" meny's, but none of them, is showing in the MAP.

Some extra info's. All my PTM215Z devices, are showing LQI 127 and a "?" on the Power. I don't thing they are sending battery status.

Best regards
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9365316/state.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by sjorge** [comment]
I'm pretty sure this is expected for GreenPower devices, I don't think I've every seen them on a network map.

**Comment by Danit2** [comment]
https://www.zigbee2mqtt.io/devices/PTM_215ZE.html#green-power

Read this section.
