### ISSUE TITLE
Frontend times out on Safari / iOS Web Engine

### ISSUE THREAD

**Issue by kneip68** [nurikk/z2m-frontend#154]
Running z2m 1.6.1 and 1.6.1-dev behind Nginx Proxy, the frontend times out on Mac OS Safari and iOS Web Engine (Both Safari and Chrome tested) whereas works perfectly in Chrome on Mac OS (in the background of the error screenshot).

Any hints? Something I can do to debug?

KR

Kneip

![image](https://user-images.githubusercontent.com/44921902/99903484-0476b500-2cc5-11eb-9593-fac5ac54c44e.png)

**Comment by kneip68** [comment]
Additional Info:
Debug Console Safari:
![image](https://user-images.githubusercontent.com/44921902/99903749-b1056680-2cc6-11eb-8ee3-49a50cace0ad.png)

Debug Console Chrome:
![image](https://user-images.githubusercontent.com/44921902/99903770-d4c8ac80-2cc6-11eb-99c1-199d02e788a1.png)

**Comment by nurikk** [comment]
You need to properly configure your proxy server (nginx?)

**Comment by kneip68** [comment]
But why is it then working on Chrome on MacOS?

Anyway, I followed the nginx example given [here](https://www.zigbee2mqtt.io/information/frontend.html#nginx-proxy-configuration) and translated it to use a folder. Using it's own server name is not an option here, as I need to have the domain set in the certificate and have other TLS encrypted services on this pi as well.

Here is the resulting site config, any hints appreciated:

[proxy.txt](https://github.com/nurikk/z2m-frontend/files/5592638/proxy.txt)

**Comment by nurikk** [comment]
> But why is it then working on Chrome on MacOS?
> 
> Anyway, I followed the nginx example given [here](https://www.zigbee2mqtt.io/information/frontend.html#nginx-proxy-configuration) and translated it to use a folder. Using it's own server name is not an option here, as I need to have the domain set in the certificate and have other TLS encrypted services on this pi as well.
> 
> Here is the resulting site config, any hints appreciated:
> 
> [proxy.txt](https://github.com/nurikk/z2m-frontend/files/5592638/proxy.txt)

Perhaps something is wrong with authorisation, can you try to disable basic authorisation for a test?

**Comment by kneip68** [comment]
OK, you were right. I still don't know why Chrome does treat the security realms differently, but obviously nginx iOS webengine and Safari do not forward the security realm from the main location to the api location in my case. When switching of authentification --only-- on the api location in my example given above, it starts to run.
I will try to enhace the configuration so that is only having one security realm, I will post back once I have found the correct nginx settings.

**Comment by kneip68** [comment]
Next try. I now fiddled around with my setup, and found that even if I put the auth realm on server level, it does not work if I don't disable it on the /api location.
So finally I gave the original example from [z2m.io](https://www.zigbee2mqtt.io/information/frontend.html#nginx-proxy-configuration) documentation modified as little as possible a try (see attachement) and even that one does not work with Safari.

So to me it seems that in z2m version 1.16.1-dev the api can not work behind auth for Safari/iOS web engine despite the docu. Should I raise an issue at z2m somewhere or is it handled here as well?
[z2m_template.txt](https://github.com/nurikk/z2m-frontend/files/5610448/z2m_template.txt)

**Comment by nurikk** [comment]
> Next try. I now fiddled around with my setup, and found that even if I put the auth realm on server level, it does not work if I don't disable it on the /api location.
> So finally I gave the original example from [z2m.io](https://www.zigbee2mqtt.io/information/frontend.html#nginx-proxy-configuration) documentation modified as little as possible a try (see attachement) and even that one does not work with Safari.
> 
> So to me it seems that in z2m version 1.16.1-dev the api can not work behind auth for Safari/iOS web engine despite the docu. Should I raise an issue at z2m somewhere or is it handled here as well?
> [z2m_template.txt](https://github.com/nurikk/z2m-frontend/files/5610448/z2m_template.txt)

Websoket protocol has nothing to do with basic HTTP authorisation. Try to disable it (basic auth) and enable token based authentication 
https://www.zigbee2mqtt.io/information/frontend.html

**Comment by kneip68** [comment]
Thx for adding the documentation to zigbee2mqtt.io. Will give it a try.

**Comment by nurikk** [comment]
> Thx for adding the documentation to zigbee2mqtt.io. Gave it a try and works with adding the access token to configuration.yaml and disabling basic auth for the API location in in nginx conf.
> 
> 2 suggestions:
> 
> 1.) Change the documentation in z2m.io example for nginx to include the basic auth bypass like so
> `location /api { auth_basic off; ... }`
> 
> 2.) Can the api authentification token be read from configuration yaml instead of entering it manually?
> 
> Thx again, finally I can extend my zigbee network only taking my iPhone through the house without installing any additional software.
> 
> Great work
> 
> Cheers Kneip

1) Would you mind to raise update doc and raise PR?
2) If you don't want token based auth then disable it (this is like you're entering username/password), reading it from config doesn't make any sense :)
