### ISSUE TITLE
Group properties should be editable via frontend

### ISSUE THREAD

**Issue by ste-fle** [nurikk/z2m-frontend#1543]
**Is your feature request related to a problem? Please describe.**
When controlling individual lights, the transition time property is reflected in the light's switch on behavior. When using groups (e.g. all lights of a room) to reduce the zigbee traffic, the lights turn on/switch state instantly which is quite harsh on the eyes. Although it's possible to also add transition times to whole groups (https://www.zigbee2mqtt.io/guide/usage/groups.html#configuration), this is currently not supported via frontend (friendly name is the only thing that can be changed) and must be done via configuration.yaml manually. The documentation also shows a few other properties which currently cannot be changed in the frontend. 

**Describe the solution you'd like**
The group properties supported by zigbee2mqtt should be editable via the frontend.

**Comment by Impact123** [comment]
Unstale.
