### ISSUE TITLE
[Bug]: Icons move on map screen

### ISSUE THREAD

**Issue by rwb196884** [nurikk/z2m-frontend#1545]
### What happened?

When you load the map screen the device icons move about.
You have to click on each of them (which is difficult becuase they're moving) to make them stop, and if you don't stop them they they go off the screen.

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.

**Comment by pedjas** [comment]
This issue is annoying.

**Comment by rwb196884** [comment]
Same issue reported here: https://github.com/Koenkk/zigbee2mqtt/issues/8428

**Comment by lordbah** [comment]
Really? Issue is just ignored without even any comment? It's user-hostile interface.

**Comment by pedjas** [comment]
All that is needed it is that once user moves item and place it on some position that position is remembered and item does not float never again, even if map is recreated.

**Comment by Per-Chr** [comment]
> All that is needed it is that once user moves item and place it on some position that position is remembered and item does not float never again, even if map is recreated.

Does not work for me.

Currently on Version 1.40.2.
Loaded map, moved items and they stopped floating.
Closed the frontend.
Restarted the frontend and reloaded the map but they were still floating.

So can someone PLEEEAAASE fill up the freezing liquid !!!!!

**Comment by pedjas** [comment]
What you described is how we expect it to work but it does not. Icons are reset to float mode each time you refresh map.
