### ISSUE TITLE
Option to ignore OTA firmware update for a device

### ISSUE THREAD

**Issue by gerard33** [nurikk/z2m-frontend#1549]
**Is your feature request related to a problem? Please describe.**
I have some Ikea remotes for which I don't want to upgrade the firmware as the current version support binding to groups and the newer firmware only supports binding to devices and I don't prefer that.

**Describe the solution you'd like**
I would like to have a possibility in the OTA page to ignore firmware updates for a device so I don't accidentily update the firmware. Maybe a checkbox can be added so you can also show these hidden devices, so you can still upgrade once you want to do that.

**Describe alternatives you've considered**
I now have added `do not update` in the description, but that field is not visible in the OTA screen.

**Comment by sjorge** [comment]
You probably want to file that as a feature request here https://github.com/koenkk/zigbee2mqtt/issues

**Comment by gerard33** [comment]
I guess it's a frontend setting to store if a device must be shown in the OTA list isn't it?

**Comment by sjorge** [comment]
It's probably better to have z2m just have a flag to ignore OTA's for a device. Then if anything else will try to be helpful and do upates you wont have surprises.
