### ISSUE TITLE
[Bug]: configure_reporting throws 

### ISSUE THREAD

**Issue by GCRVL** [nurikk/z2m-frontend#1552]
### What happened?

When calling configure_reporting in the reporting tab of a device, a slash is added at the end of the ID, resulting in a device not found error.

![image](https://user-images.githubusercontent.com/4420162/192107765-ef6e940f-c8e3-4295-b85f-0d3d8f89ee75.png)

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Ho this happened (steps to reproduce)? Is it external converter device?

**Comment by GCRVL** [comment]
![image](https://user-images.githubusercontent.com/4420162/192588847-c248261d-452b-41f1-8237-3ab98ee72442.png)
![image](https://user-images.githubusercontent.com/4420162/192588947-b616373b-3d9c-4a60-aa3f-ffde5e4da30f.png)

Happens when I try to change the reporting configuration of a TS011F_plug_3

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by GCRVL** [comment]
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9658257/state.json.zip)
