### ISSUE TITLE
[Bug]: Norwegian language is just English

### ISSUE THREAD

**Issue by Lovasz-Akos** [nurikk/z2m-frontend#1554]
### What happened?

Switched language to Norwegian and it's just English

### What browsers are you seeing the problem on?

Microsoft Edge

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed it latest dev

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by Lovasz-Akos** [comment]
I'll just have to take your word on that, it's kind of a struggle for me to update, I'm running a server with buildroot linux, just figured I'll let you know if you don't already :D
