### ISSUE TITLE
Add events to translation

### ISSUE THREAD

**Issue by xrust83** [nurikk/z2m-frontend#1573]
I have a remote control with 4 buttons that can issue 12 actions
1_single
1_double
1_hold
2_single
2_double
2_hold
3_single
3_double
3_hold
4_single
4_double
4_hold

Please add them to the context "values" or tell me how to get it, don't accept Pull request by language
https://www.youtube.com/watch?v=BUJ8g5vRPYA

**Comment by xrust83** [comment]
If possible, then add the same: 
(pressed)
for a call, 
(wakeup, shake, fall, tap, slide, flip180, flip90, rotate_left, rotate_right, side)
and for a cube

**Comment by xrust83** [comment]
![image](https://user-images.githubusercontent.com/58448955/193470955-df8706fb-6852-42b4-a184-922aabb8319b.png)
There are still tags that have not been translated, they can be caught only if you have this or that device, or someone notifies you about it.

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by xrust83** [comment]
Oh sure
[state.json-5.zip] (https://github.com/nurikk/zigbee2mqtt-frontend/files/9693271/state.json-5.zip)

**Comment by xrust83** [comment]
After the update, the translation flew into the section exposed. I didn't pay attention when, but everything is fine on the master version, but there is no translation on the developer version

<img width="518" alt="Знімок екрана 2022-11-21 о 00 09 55" src="https://user-images.githubusercontent.com/58448955/202929610-d702d613-756e-4d8b-b54d-f276c606681b.png">
<img width="488" alt="Знімок екрана 2022-11-21 о 00 19 58" src="https://user-images.githubusercontent.com/58448955/202929615-83b6e08d-0b03-41c4-8be6-5bc56d87d19a.png">

**Comment by xrust83** [comment]
Thank you. 0.6.121 all fix
