### ISSUE TITLE
[Bug]: Question-mark battery icon for Konke button device with battery reported

### ISSUE THREAD

**Issue by Tche333** [nurikk/z2m-frontend#1576]
### What happened?

The Konke button devices have a question mark in the dashboard view
![image](https://user-images.githubusercontent.com/17355631/193417130-3042f7d6-71da-46aa-ab5e-705e8c5be289.png)
However, when looking into the details of the device, you can find out battery information is available
![image](https://user-images.githubusercontent.com/17355631/193417151-728e4322-192d-4207-a5f7-de78a763a334.png)
Those devices are working fine, but I can't quickly check their battery status.

From the state file
    "deviceStates": {
        "Button-01": {
            "battery": 0,
            "last_seen": "2022-10-01T11:14:03+02:00",
            "linkquality": 63,
            "voltage": 2500
        },
        "Button-02": {
            "battery": 60,
            "last_seen": "2022-10-01T12:16:03+02:00",
            "linkquality": 65,
            "voltage": 2800
        },
        "Button-03": {
            "battery": 60,
            "last_seen": "2022-10-01T11:52:28+02:00",
            "linkquality": 5,
            "voltage": 2800
        },

I'm using zigbee2mqtt as an HassOS Add-on & I've just try the edge latest version: result is still the same.

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by aofc** [comment]
I had the same issue. To get the battery working in the frontend I had to add my own external converter to my instance of Z2M. 

Here is the code I use:

```
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition =  {
    zigbeeModel: ['3AFE280100510001'],
    model: '2AJZ4KPKEY',
    vendor: 'Konke',
    description: 'Multi-function button',
    fromZigbee: [fz.konke_action, fz.battery, fz.legacy.konke_click],
    toZigbee: [],
    exposes: [e.battery_low(), e.battery(), e.action(['single', 'double', 'hold'])],
    meta: {battery: {voltageToPercentage: '3V_2500'}},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
        await reporting.batteryVoltage(endpoint);

        // Has Unknown power source, force it.
        device.powerSource = 'Battery';
        device.save();
    },
};

module.exports = definition;
```

Notice I had to expose the _battery_low()_, function even though I don't think this device supports this property. But without it, the battery would not get recognized, I don't know why exactly. 

Now this is more an issue to post to the zigbee-herdsman-converters repo, although it might be a bug in the frontend.
