### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by YellowNest** [nurikk/z2m-frontend#1578]
**Is your feature request related to a problem? Please describe.**

The login with auth token seems inconvenient. Loggin in with a iOS device is difficult and results in empty device list

**Describe the solution you'd like**
A login screen just like Homebridge config UI X would be perfect. (User/Pass)
https://github.com/oznu/homebridge-config-ui-x

**Describe alternatives you've considered**
No other alternatives

**Additional context**

![](https://www-smarthomeassistent-de.cdn.ampproject.org/i/s/www.smarthomeassistent.de/wp-content/uploads/2021/01/Homebridge-Login-1-702x459.png)

**Comment by 6wheels** [comment]
+1

I just added an auth-token in the configuration, and I was surprised that the password window is in clear text as well as the password value in the local storage.

Any improvement would be welcomed.

**Comment by YellowNest** [comment]
Bumping this issue

**Comment by 6wheels** [comment]
Any info on this one? is it in the pipe?
