### ISSUE TITLE
Make it possible to change settings of a group using the GUI

### ISSUE THREAD

**Issue by tamueller** [nurikk/z2m-frontend#1582]
**Is your feature request related to a problem? Please describe.**
There are several options to control group behaviour (all_members_off/Last_State, optimistic, etc.). It is not possible to set those options using the GUI.

**Describe the solution you'd like**
The Groups UI should have a possibility to set the options described in: https://www.zigbee2mqtt.io/guide/usage/groups.html#configuration

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Impact123** [comment]
Unstale.
