### ISSUE TITLE
[Bug]: Xiaomi Lightsensor GZCGQ01LM works fine but is not displayed in dashboard

### ISSUE THREAD

**Issue by JayJay-Master** [nurikk/z2m-frontend#1585]
### What happened?

Xiaomi lightsensors GZCGQ01LM are not displayed in dashboard. On devive page under details I can see all values and the are also well transfered to Homekit via homebridge-z2m plugin. I have 2 of this devices and both shows same behavior.
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9822339/state.json.zip)

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by JayJay-Master** [comment]
Hello,
no guess what could be the reason for this behavior? Or is there somewhere a possibility to configure the display in the dashboard? I had unfortunately not found anything about this.
Help would be greatly appreciated.

**Comment by ReneTode** [comment]
i got the same problem after a recent update from z2m

**Comment by JayJay-Master** [comment]
bump

**Comment by lbarjak** [comment]
continues to exist
