### ISSUE TITLE
[Bug]: Composite expose issues

### ISSUE THREAD

**Issue by vladyspavlov** [nurikk/z2m-frontend#1586]
### What happened?

I'm working on the new converter for the device and ran into a problem. You can find PR here https://github.com/Koenkk/zigbee-herdsman-converters/pull/4750

A dropdown in composite expose changes the value only if it is applied. It looks like it's state-based and until you apply it, the state doesn't change, so the dropdown value doesn't change. Here's a video for demonstration:

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/16994749/197086820-e6589644-ea60-4875-9609-ef3366eb221e.mp4
</details>

Additionally, if you refresh the page and try to apply without any changes, there is the next error:
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/16994749/197306250-3571d47e-5d19-4d84-9035-c4133c0d8d4e.png)
</details>

If you change the day in the drop-down list but do not change the schedule, the following error will be displayed:
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/16994749/197306209-7a81e50c-60e2-4d0c-bfe7-e73f25a5526d.png)
</details>

<details>
<summary>Device state</summary>

```
{
    "battery_low": false,
    "boost_timeset_countdown": 0,
    "child_lock": "UNLOCK",
    "comfort_temperature": 21.5,
    "current_heating_setpoint": 24,
    "eco_temperature": 19,
    "error_status": 0,
    "frost_protection": "OFF",
    "heating_stop": "OFF",
    "holiday_start_stop": "2022/10/06 06:15 | 2022/10/06 05:18",
    "holiday_temperature": 18,
    "last_seen": "2022-10-22T00:00:05.082Z",
    "linkquality": 87,
    "local_temperature": 23,
    "local_temperature_calibration": 0,
    "online": "ON",
    "open_window": "OFF",
    "open_window_temperature": 12,
    "preset": "manual",
    "schedule": {
        "schedule": "10:30/18 11:20/19.5 24:00/21.5",
        "week_day": "wednesday"
    },
    "schedule_friday": "10:30/18 11:20/19.5 24:00/21.5",
    "schedule_monday": "10:30/18 11:20/19.5 24:00/21.5",
    "schedule_saturday": "10:30/18 11:20/19.5 24:00/21.5",
    "schedule_sunday": "10:30/18 11:20/19.5 24:00/21.5",
    "schedule_thursday": "10:30/18 11:20/19.5 24:00/21.5",
    "schedule_tuesday": "10:30/18 11:20/19.5 24:00/21.5",
    "schedule_wednesday": "10:30/18 11:20/19.5 24:00/21.5",
    "system_mode": "heat",
    "update": {
        "state": null
    },
    "update_available": null,
    "working_day": "mon_sun"
}
```
</details>

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by vladyspavlov** [comment]
Hi,
Sorry for the delay. Here's a state.json.zip:
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9957589/state.json.zip)

**Comment by nurikk-sa** [comment]
> Hi, Sorry for the delay. Here's a state.json.zip: [state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9957589/state.json.zip)

Thanks! Fix just landed to the dev, can you help to verify?
