### ISSUE TITLE
[Bug]: Frontend dashboard devices list is repeatedly empty

### ISSUE THREAD

**Issue by blacknell** [nurikk/z2m-frontend#1587]
### What happened?

Recently, the list of devices in the zigbee2mqtt dashboard comes up blank. I have to refresh it several times and/or start the dashboard map and then revisit the devices tab (this doesn't always work). All the devices themselves are working as expected.

I expect to see the list of devices almost immediately.

My system is currently seeing this blank screen almost all the time. In around 20% cases the list eventually appears after a long delay. I've tried after restarting z2m and HA but no difference.

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant stacktrace

```shell
n/a
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by blacknell** [comment]
[state.json (2).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/9849496/state.json.2.zip)

**Comment by jagjordi** [comment]
Did you find a solution to this problem? I am facing a similar issue.

**Comment by blacknell** [comment]
> Did you find a solution to this problem? I am facing a similar issue.

No

**Comment by jagjordi** [comment]
In my case it turned out it was some issue with NGINX reverse proxy. If I access directly with the server IP it works

**Comment by dylexrocks** [comment]
If anyone faces the same issue and comes across this. The solution is quite simple. The frontend communications via websocktes and this has to be enabled in the nginx config. 

See: [https://stackoverflow.com/a/39216976](https://stackoverflow.com/a/39216976)

**Comment by jagjordi** [comment]
For me it ended up being related to uBlock plugin
