### ISSUE TITLE
Red triangle ?

### ISSUE THREAD

**Issue by francisp2** [nurikk/z2m-frontend#159]
I have on 2 routers a red triangle ? What is the meaning of that ?

![image](https://user-images.githubusercontent.com/52328611/100274615-0b205900-2f5f-11eb-9ace-f5664c5dc079.png)
![image](https://user-images.githubusercontent.com/52328611/100274665-1f645600-2f5f-11eb-9cf5-9f3798118a5e.png)

**Comment by nurikk** [comment]
Have you tried to hover mouse pointer on this triangle and wait for a while?
