### ISSUE TITLE
Is @rjsf/bootstrap-5 really a runtime dependency?

### ISSUE THREAD

**Issue by jirutka** [nurikk/z2m-frontend#1591]
[package.json](https://github.com/nurikk/zigbee2mqtt-frontend/blob/dev/package.json):
```
    “dependencies”: {
        "@rjsf/bootstrap-5": "https://github.com/nurikk/fileshare/blob/main/rjsf-bootstrap-5-4.2.0.tgz?raw=true"
    }
```

`@rjsf/bootstrap-5` doesn’t seem to be needed in runtime. I tried to delete it from `node_modules`, restart zigbee2mqtt, force-reload the front-end, and I don’t see anything missing. Thus I think it should be moved to `devDependencies`.

My motivation is to reduce the number and the size of the zigbee2mqtt dependencies needed in runtime. bootstrap-5 pulls in react-icons which makes half of the node_modules size.

**Comment by nurikk** [comment]
Correct, it accidentally slipped into dependencies
