### ISSUE TITLE
Wrong link in ingress mode

### ISSUE THREAD

**Issue by ciotlosm** [nurikk/z2m-frontend#16]
When using `ingress` with Home Assistant add-on, the link left of **Home** points to `/` which leads to Home Assistant interface loading twice. This should be corrected to work with `ingress` or suppressed when using `ingress`

https://github.com/nurikk/z2m-frontend/blob/ddd76ca3b51840644942d4883cf42148a5341952/src/components/navbar/index.tsx#L13

![Screenshot 2020-09-24 at 11 48 20](https://user-images.githubusercontent.com/7738048/94122968-deb36800-fe5b-11ea-9a38-b75424dd5424.png)

**Comment by nurikk** [comment]
Fixed in latest update

**Comment by ciotlosm** [comment]
Working in latest edge add-on.
