### ISSUE TITLE
Mobile UI is not very user friendly

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#160]
There are some general user friendlyness issues when viewing on an mobile device like and iPhone.

For example #155, but there are some other issues too...

![image](https://user-images.githubusercontent.com/379665/100338760-4bbcb880-2fd9-11eb-9a1c-7815ede30b40.png)
The expose tab is a complete mess and unusable.

![image](https://user-images.githubusercontent.com/379665/100338878-6f7ffe80-2fd9-11eb-9755-dbbe71ff92be.png)
The divider between devices is hard to see, also it's kind of a pain that there is no sorting options so finding a device is hard.

I'd much rather have a more minimalist view here. One line per devices that slits
```
ID | friendly_name | LQI | PS | [button to open detailed page]
```

![image](https://user-images.githubusercontent.com/379665/100339354-0c429c00-2fda-11eb-9ce2-822acd270327.png)

The detail page sometimes opens with the tabs on the top not visible, but not always... It would also be nice to move the actions to the top on mobile and make the buttons a bit bigger, for those fat fingers.

Perhaps also hide less useful tabs like cluster and state on mobile to safe some space... 

Not sure how hard this is though, a I think now the interface just re-flows to fit, sort of at least.

**Comment by nurikk** [comment]
I'm not a very good expert in CSS and not really into implementation a mobile-friendly version. This results in what we have at this moment. Any help is much appreciated

**Comment by sjorge** [comment]
Unfortunately, I'm horrible with UI stuff :(

**Comment by nurikk** [comment]
Should be better now

**Comment by sjorge** [comment]
![image](https://user-images.githubusercontent.com/379665/100541907-4ebce080-3247-11eb-9009-dabf9de135f2.png)
![image](https://user-images.githubusercontent.com/379665/100541923-7449ea00-3247-11eb-9284-7fc6cbd9d33b.png)

Yes, good improvements.
The tab bar is now visible on the info page, and on the expose page more stuff is now accessible...

Not sure how hard it is to do but... can you move the label/description be moved above the value/action controls when the width gets below a certain point? That might free up some more room and make the labels readable again.

**Comment by sjorge** [comment]
New index also looking lot better!

**Comment by sjorge** [comment]
Can we get the friendlyName on the detrailed page? Looks like the header was remove so it is not available currently.

**Comment by sjorge** [comment]
I’ll close this now, it’s a lot more usable than it was before!
