### ISSUE TITLE
Implement list type exposes feature

### ISSUE THREAD

**Issue by nurikk** [nurikk/z2m-frontend#1600]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/4775#issuecomment-1304828216

@kirovilya

**Comment by kirovilya** [comment]
When adding a list item (by pressing the plus button) before pressing the Apply button, an empty object is sent to the topic:
`MQTT publish: topic 'zigbee2mqtt/0x54ef44100051c668', payload '{"schedule":[{}]}'`

Then if you do not change the default values and click Apply, an empty object will also be sent.

If you change only one value from the fields and click Apply, the object will be sent only with the changed attribute, and not the entire set of attributes:
`MQTT publish: topic 'zigbee2mqtt/0x54ef44100051c668', payload '{"schedule":[{"minute":1}]}'`

I want to get the full set of object attributes, and not just the changed ones
