### ISSUE TITLE
I can  connect via zigbee2mqtt and make my own frontend?

### ISSUE THREAD

**Issue by Noudne** [nurikk/z2m-frontend#1602]
Helloy. I want to connect my unsupported zigbee device to zigbee2mtt and not add it to the site, but make my own frontend and execute my own javascript queries, can I do that?

**Comment by nurikk-sa** [comment]
Hey, @Noudne!

Absolutely you can! Using external converters https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Noudne** [comment]
> Привет,@Noudne!
> 
> Абсолютно можете! Использование внешних преобразователей https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

I need to add a file with my device and the converter code there and I can use javascript to get data from the device or message. Will my device be able to work on zigbii2mktt after that without an external interface, but with its own?
