### ISSUE TITLE
Feature Request: Add the ability to change a device's icon by uploading an image

### ISSUE THREAD

**Issue by Impact123** [nurikk/z2m-frontend#1606]
**Is your feature request related to a problem? Please describe.**
Setting a custom icon can be a bit inconvenient as it involves manually converting an image to a base64 string if you want to use a local file. I usually download images from the web and crop/modify them locally. If I want to use it I have to convert it or upload it somewhere else first.
![image](https://user-images.githubusercontent.com/899193/201239862-a65f9319-8f24-4e49-9143-badfcd6d9873.png)

**Describe the solution you'd like**
An ability to upload, maybe by drag & dropping, an image and let the frontend convert it to what it wants.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by xrust83** [comment]
- You can upload your icons to GitHub and provide a direct link to your repository.
https://raw.githubusercontent.com/xrust83/iconz2m/main/NAS-AB02B2.png

- You can use my base icons =)
https://github.com/xrust83/iconz2m

- If your icons are in png format, 512x512 pixels, 72 pixels/inch and a transparent background, I can add your icons to my library

**Comment by Impact123** [comment]
Unstale.

**Comment by pedjas** [comment]
> * You can upload your icons to GitHub and provide a direct link to your repository.

Would that work in networks with no Internet access?

**Comment by xrust83** [comment]
> > * You can upload your icons to GitHub and provide a direct link to your repository.
> 
> Would that work in networks with no Internet access?

without internet access, the zigbee logo will be displayed as it is now.  if you create a local server from which you copy the database with pictures, then it will work like this.
