### ISSUE TITLE
[Bug]: Aqara motion sensor does not update states and missing link in map of devices

### ISSUE THREAD

**Issue by jarlesb** [nurikk/z2m-frontend#1608]
### What happened?

I have added multiple Aqara motion sensors, however only one of them is reacting to motion change. The others are only showing stale data.

When I look at the Map of devices, it seems only the one marked in green works and has a link. The other devices marked in red are added well, but only "floats" around.

Running hassio with Home assistant 2022.11.2 and ZigBee2mqtt addon (1.28.2-1)
Device: SONOFF Zigbee 3.0 USB Dongle Plus-E

Aqara device RTCGQ11LM

![Zigbee2Mqtt aqara motion issue](https://user-images.githubusercontent.com/34880506/201736098-89914d27-73e9-48c5-ae4d-eb2aafe9ccd6.jpg)

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by xrust83** [comment]
Pentagrama 👹
