### ISSUE TITLE
[Bug]: How to start not documented

### ISSUE THREAD

**Issue by jbrepogmailcom** [nurikk/z2m-frontend#1610]
### What happened?

Unable to start, because there is no guide. Sorry I am not developer, I am just dumb user - I was able to run npm i zigbee2mqtt-frontend, but what to do next to run it please? Thank you.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
none
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Impact123** [comment]
The frontend is included with Zigbee2MQTT. [See here on how to enable it](https://www.zigbee2mqtt.io/guide/configuration/frontend.html)

**Comment by jbrepogmailcom** [comment]
Thanks but it does not seem to work. I have added entry
frontend: true
  port: 8080

to file /opt/zigbee2mqtt/data/configuration.yaml

then I restarted zigbee2mqtt service, but I am getting "This site can’t be reached". It looks like no web server is running.

**Comment by Impact123** [comment]
That's not valid. Use the syntax from the docs I linked
```yaml
frontend:
  port: 8080
  ```
  Please ask in Z2M's discord for further help as this is not an issue related to the frontend
