### ISSUE TITLE
Update zigbee-herdsman

### ISSUE THREAD

**Issue by faucherc** [nurikk/z2m-frontend#1621]
Please update the zigbee-herdsman dependency to the lates version to get the lastest attributes available in the "Dev console".

**Comment by MattL0** [comment]
@nurikk  any news? Thanks

**Comment by MattL0** [comment]
Up

**Comment by afharo** [comment]
I think this was achieved in https://github.com/nurikk/zigbee2mqtt-frontend/commit/1ff5bc10747f3e82af5628de303cdcee16726b64 by @nurikk-sa. 

We may probably close this issue, WDYT?

**Comment by MattL0** [comment]
> I think this was achieved in [1ff5bc1](https://github.com/nurikk/zigbee2mqtt-frontend/commit/1ff5bc10747f3e82af5628de303cdcee16726b64) by @nurikk-sa.
> 
> We may probably close this issue, WDYT?

Yea this can be closed

**Comment by MattL0** [comment]
Thanks

**Comment by faucherc** [comment]
Thanks
