### ISSUE TITLE
[Bug]: Unable to apply schedule for new TV02-Zigbee TS0601 _TZE200_hue3yfsn

### ISSUE THREAD

**Issue by raoulbhatia** [nurikk/z2m-frontend#1622]
### What happened?

I paired new TV02-Zigbee TS0601 _TZE200_hue3yfsn with a pre-defined schedule.

When opening the web frontend: "Devices" > "my device" > "Exposes",
I am unable to apply a custom schedule directly.

Whichever schedule / working_day combination I chose, the "schedule" input is empty and the "Apply" button stays disabled.

<img width="1244" alt="Screenshot 2022-12-06 at 21 36 41" src="https://user-images.githubusercontent.com/727412/206019134-f76aaadc-fab7-46b7-a302-eb69fb05cfbe.png">

However, "schedule_monday" through "schedule_sunday" displays values from the "payload" as observed from z2m logs.

<img width="1248" alt="Screenshot 2022-12-06 at 21 37 47" src="https://user-images.githubusercontent.com/727412/206019166-306eaa68-d704-4f88-a89e-8f8e57b1d061.png">

The only way to get the "Apply" button working is to first manually set a new schedule via `mosquitto_pub` and then, the frontend allows to set new schedules.

i.e.
```
mosquitto_pub -t "zigbee2mqtt/TRV NEW/set" -m '{"schedule": {"week_day": "monday", "schedule":"08:00/18.5 24:00/18.5"}}' -u USER -P PASSWORD
```

Screenshot after the first publish:

<img width="1258" alt="Screenshot 2022-12-06 at 21 44 36" src="https://user-images.githubusercontent.com/727412/206019195-6297fd9f-4ef9-46db-bfcb-b704ed298c61.png">

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by raoulbhatia** [comment]
Possibly related https://github.com/Koenkk/zigbee2mqtt/issues/15404

**Comment by Benny56** [comment]
Same here

**Comment by Benny56** [comment]
Same here. A few days ago it worked as expected.

**Comment by KalleKal** [comment]
same issue here und same workaround works

**Comment by raoulbhatia** [comment]
@Koenkk do you need more information to replicate this problem?

**Comment by Koenkk** [comment]
For the apply button to be enabled, the `schedule`  field also needs to be filled in.
