### ISSUE TITLE
[Bug]: Color XY control on the second endpoint

### ISSUE THREAD

**Issue by ptvoinfo** [nurikk/z2m-frontend#1623]
### What happened?

@nurikk 
If I define exposes on the second endpoint for a color value like:
presets.light_brightness_colorxy().withEndpoint('l2'),
the front-end incorrectly sends the following color command to Z2M. Z2M interprets it as a command for the first endpoint.

```
Received MQTT message on 'xiaomi1/0x00124b0022055177/set' with data '{"color":{"hex":"#FF0018"}}'
```
the expected command should contain the endpoint name:

```
Received MQTT message on 'xiaomi1/0x00124b0022055177/set' with data '{"color_l2":{"hex":"#FF0018"}}'
```
Note 1: at the same time, it correctly sends a command to change brightness.

```
Received MQTT message on 'xiaomi1/0x00124b0022055177/set' with data '{"brightness_l2":223}'
```

Note 2: if I send the expected command to Z2M via MQTT Explorer, Z2M works correctly.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant stacktrace

```shell
n/a
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by DJTerentjev** [comment]
@nurikk could you please check this issue.

**Comment by ptvoinfo** [comment]
up
