### ISSUE TITLE
Zigbee2MQTT Web UI not loading

### ISSUE THREAD

**Issue by Trace-star** [nurikk/z2m-frontend#1633]
liunx install zigbee2mqtt,   Zigbee2MQTT Web UI not loading after zigbee2mqtt start
![企业微信截图_1671001411228](https://user-images.githubusercontent.com/29688398/207528289-01012e87-43a6-4045-a597-4c98ff69dd3e.png)
![企业微信截图_16710013989982](https://user-images.githubusercontent.com/29688398/207528311-ecaafcb6-6831-4041-af22-5eaf3304c1c8.png)

**Comment by josipledic** [comment]
same issue here

**Comment by nurikk** [comment]
check your MQTT connection settings https://www.zigbee2mqtt.io/guide/configuration/mqtt.html

**Comment by laurenttaieb** [comment]
I have opened a trouble ticket today on probably the same issue
