### ISSUE TITLE
Could we limted the number of devices that load on Home page

### ISSUE THREAD

**Issue by cloudbr34k84** [nurikk/z2m-frontend#1653]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
My Zigbee2MQtt frontend is getting slower as i add more devices. Would limited the number of devices loading on the homepage help??
I have 127 devices and when im moving around on the HA app inside Z2M it takes while for the devices to populate. When i press Permit Join sometimes that doesn't show the countdown until i refresh the page..

So maybe we could limit the it to the last 10 devices added
?
**Describe alternatives you've considered**

**Additional context**

**Comment by Impact123** [comment]
This would be a workaround, not a proper solution.

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by cloudbr34k84** [comment]
> This would be a workaround, not a proper solution.

Ok I have no idea just a thought

**Comment by cloudbr34k84** [comment]
> Hi! Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

Here you go. What will this tell you??
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/10419981/state.json.zip)

**Comment by Bascht74** [comment]
Hi, I got the same problem. 
I have 120 devices.
The problem started, after I activated "device availability (advanced)".
After that the UI is very slow.

@cloudbr34k84 Could you try disabling that (set to simple and restart Z2M). 
For me it is much smoother...

![image](https://user-images.githubusercontent.com/66269310/212986434-703bb1a6-bd65-4f9c-9cb3-7920181a659d.png)

**Comment by Bascht74** [comment]
@nurikk The window takes a lot of CPU-Load and memory: 
![image](https://user-images.githubusercontent.com/66269310/212987424-a9db1e69-a24e-4c04-86bd-961f6f9d6ba6.png)

Switching to the OTA-Tab: 
![image](https://user-images.githubusercontent.com/66269310/212988194-877c0479-24c5-4837-b27a-2770acd2989f.png)

**Comment by cloudbr34k84** [comment]
yeah ok i have turned it off, ill monitor it now
