### ISSUE TITLE
[Bug]: Dashboard not showing all devices

### ISSUE THREAD

**Issue by Schmetterfliege** [nurikk/z2m-frontend#1655]
### What happened?

I just noticed that the dashboard is not showing all of my Ikea Tradfri switches.
Actually, that was the case yesterday. Today no switches are shown at all on the dashboard page.
However, the devices page shows my 5 switches perfectly fine (and all of them are working as expected).
Dashboard Page:
![image](https://user-images.githubusercontent.com/76066402/212556115-659c23af-0d07-4f4c-a567-995f5411b4bf.png)

Devices Page:
![image](https://user-images.githubusercontent.com/76066402/212556107-10d0e40f-4b78-45cc-914e-34fc2845921d.png)

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/10420748/state.json.zip)

**Comment by tlamoureux24** [comment]
I can confirm, i have two AQARA WRS-R02 which works perfectly, i have them in devices but not in dashboard

**Comment by kapabel** [comment]
Same here. I have an Aqara water leak sensor which I reset and reintegrated. Now it shows up in the device list but not in the dashboard anymore.

edit: I reset and now it’s all working as it should.
