### ISSUE TITLE
Device History (devices that left the network log)

### ISSUE THREAD

**Issue by evlo** [nurikk/z2m-frontend#1656]
**Is your feature request related to a problem? Please describe.**
My biggest issue so far with z2m  is that for some time devices just "leave the network", i do not know why, it was better for the time, and now it happens again

Especially if one has lights on regular light switch, it is pain (even if there is no issue on z2m side)

**Describe the solution you'd like**
Some tab or flag for the device so it is kept in devices list, or moved to separate device list of devices that left the network - i do not think it needs to track devices that are removed from z2m by the user, but if so, it definitely should be different flag then if device leave network by itself.

**Describe alternatives you've considered**
Moving to ZHA, but much worse device support and UI
I'm also trying BT BLE devices now, where it is possible, but it seems to sometime send slower info about state, but for sensors that do advertise it seems to be a way as there is no real pairing.

Some kind of log parsing for `has left the network` message in log and notification, did not looked into that so far

**Additional context**
_let me know if you think this needs mockup screens created_

I think it would still be useful even if there is no issue on z2m side for devices to be leaving network ... dunno about other users, in ie. tuya app on phone it would keep the trace of devices as "offline"

**Comment by Bascht74** [comment]
The devices are stored at devices.yaml. 
Maybe it could be possible to show those that a not in the database.db?

This could help, too, if you switch from on adapter to another and you need to re-pair every device. Then you would know what you still need to pair and what is done. 

Right now, I compared the db-file and the devices.yaml via some conversion and excel :-) But no fun...
