### ISSUE TITLE
[Bug]: Input validations missing

### ISSUE THREAD

**Issue by jjarven** [nurikk/z2m-frontend#1660]
### What happened?

1) Choose a device, go to settings, enter QoS value like 3, submit change and restart Z2M - will not start due value being out of bounds.

2)  Choose a device, go to settings, click '+'-sign on 'Ignore debounce'-field, enter something, submit change and now you can't remove the field anymore with '-'-sign.

Only way correct these is to manually edit configuration.yaml.

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by wowgamr** [comment]
Same for me with Chrome 111.0.5563.65
