### ISSUE TITLE
[Bug]: Datek 0402946-modul becomes unsupported after upgrade to 1.30

### ISSUE THREAD

**Issue by magne74** [nurikk/z2m-frontend#1668]
### What happened?

After updating to latest z2m this module becomes unsupported. Tried to re-pair it without luck. I then loaded a backup of previous version again. The device the became supported again. I then updated the z2m one more time with the same results. 

### What browsers are you seeing the problem on?

Safari

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Impact123** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5425
