### ISSUE TITLE
Needs a "refresh all" button on devices-->exposes tab

### ISSUE THREAD

**Issue by mbrink123** [nurikk/z2m-frontend#1672]
**Is your feature request related to a problem? Please describe.**
In z2m, on the device--exposes tab, there are refresh buttons that you click to pull data from the device into Z2M.  When a new device is added, these data points are blank/null, and you have to click the refresh buttons to see whats in the devices.

**Describe the solution you'd like**
I would like to see one button that refreshes all items on the page.  An Inovelli switch has 63 refresh buttons for each device.  I want to click one button at the top and refresh all of them or just have the page automatically refresh the data.

**Describe alternatives you've considered**
Page could just automatically refresh without me having to manually refresh it.

**Additional context**
These are the blue buttons I am talking about.
![image](https://user-images.githubusercontent.com/97499020/217980760-6b71d620-f8c3-477e-8a55-b82095aed356.png)

**Comment by cloudbr34k84** [comment]
yeah this is a great idea!

**Comment by mbrink123** [comment]
Still needed

**Comment by mbrink123** [comment]
Fun fact, there are currently 63 different exposes on a Innovelli switch.  After a recent firmware upgrade all the exposes in Z2M go back to "null" and need to have the refresh button clicked to update Z2M to show the setting stored in the switch.  I have 40 switches, that's 2520 refresh buttons I have to click....  See the need for a "refresh all" button?

**Comment by michaelkkehoe** [comment]
Still needed

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.
