### ISSUE TITLE
A way to Show which routers have child devices linked

### ISSUE THREAD

**Issue by cloudbr34k84** [nurikk/z2m-frontend#1673]
Its great to have the map but as my device list grows the map takes way to long to load and when it does it sometimes just refreshes and goes back to the device page. 

if we could also expose within the device if its linked to a router device or what child devices are linked to the router. ZHA has this and it was useful.

Maybe have a mini map for the device??

Thoughts??
Very simple UI example of showing the information maybe?

![image](https://user-images.githubusercontent.com/58960644/218000254-ca30802c-232a-4e65-9366-ce1537df4749.png)

**Comment by cloudbr34k84** [comment]
Adding a comment to keep this open

**Comment by Impact123** [comment]
Unstale.

**Comment by Impact123** [comment]
Unstale.

**Comment by cloudbr34k84** [comment]
> Unstale.

i take it you agree?

**Comment by Impact123** [comment]
It just sounded interesting and the bot keeps closing things.

**Comment by cloudbr34k84** [comment]
its been awhile since anything was done to the interface,I find it would help rather having to load the map all the time which takes ages when you have 100+ devices
