### ISSUE TITLE
[Bug]: Aqara FP1 exposes page not letting me set zones

### ISSUE THREAD

**Issue by misterwobbley** [nurikk/z2m-frontend#1677]
### What happened?

I have the Aqara FL1 Presence sensor paired on Z2MQQT.   I go to the device page and then the exposes page.

When I scroll down to the "region_upsert" section, set a region number in the scroll bar (it doesn't matter which region I set)  and click on the green box with a plus in it, the elements to set up the zone position on the screen flash up for less than one second and then disappear again before I even have the chance to move the pointer and click on anything.

I have tried using Firefox, Chrome & Edge on Windows, Firefox, Chrome & |Chromium on Linux Mint and Firefox, Chrome & the HA App on Android, all of which show the same behaviour.

I am running on HA OS on a raspberry pi, Home Assistant 2023.2.3, Supervisor 2023.01.1, Operating System 9.5 and Frontend 20230202.0

[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/10714790/state.json.zip)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by mark1foley** [comment]
Hi,

I see the same issue when using Zigbee2MQTT.  Have tried several Edge and Chrome browsers and both exhibit the same behaviour. 

Zigbee2MQTT version
 1.30.2
Coordinator type ConBee2
Coordinator revision 0x26780700 (latest).
Frontend version
 0.6.125

**Comment by amaisano** [comment]
Same issue. I had to add a breakpoint in Chrome devtools in the DOM for child node changes to freeze it long enough to take a picture. I'm on the latest stable of all software in the stack.

![image](https://user-images.githubusercontent.com/688435/225438419-b0c79614-0e73-49de-95d2-fbf8c0fbbccb.png)

**Comment by amaisan0** [comment]
unstale Please fix!!!

**Comment by accelle17** [comment]
Strange. I was encountering this and when I checked it today, it is already fixed. Adding regions is hard though, I wish there was a way to declare the regions by putting just a text and not sliders then hit +.

**Comment by amaisano** [comment]
You're right - it does seem to be working now. Perhaps it was fixed here?

https://github.com/Koenkk/zigbee-herdsman-converters/pull/5386
