### ISSUE TITLE
Feature request: Add friendly name on device pages.

### ISSUE THREAD

**Issue by SargonofAssyria** [nurikk/z2m-frontend#168]
Please add friendly name on the About, Bind, State, Exposes and Clusters pages.
It helps to identify the item.

**Comment by nurikk** [comment]
It's already there
<img width="1036" alt="Screenshot 2020-12-02 at 08 53 52" src="https://user-images.githubusercontent.com/1525421/100814111-f28ed200-347b-11eb-9f1c-6765c78a369c.png">

**Comment by SargonofAssyria** [comment]
Sorry but this is my screen.
![2020-12-02_09-10-32](https://user-images.githubusercontent.com/24824113/100846139-721da080-347e-11eb-98fa-d1d4f7b09fd1.png)
![2020-12-02_09-11-47](https://user-images.githubusercontent.com/24824113/100846155-7649be00-347e-11eb-9b96-8b3b67df5894.png)

**Comment by nurikk** [comment]
> Sorry but this is my screen.
> ![2020-12-02_09-10-32](https://user-images.githubusercontent.com/24824113/100846139-721da080-347e-11eb-98fa-d1d4f7b09fd1.png)
> ![2020-12-02_09-11-47](https://user-images.githubusercontent.com/24824113/100846155-7649be00-347e-11eb-9b96-8b3b67df5894.png)

Try to update your z2m installation

**Comment by SargonofAssyria** [comment]
Yep! updated to 0.2.100 and it is there. Sorry I updated a few days a ago, should have done just after the commit of z2m of 30 nov. 
Tnx a lot.
