### ISSUE TITLE
[Bug]:  Request z2m backup not working

### ISSUE THREAD

**Issue by Flyer11111** [nurikk/z2m-frontend#1680]
### What happened?

I click on Request z2m backup spinning icon appears . have left it for hours , never changes to download file. ?

I've updated removed / reinstall  Zigbee2MQTT 

Zigbee2MQTT version
    1.30.1-dev commit: [e9a3835]
Coordinator type
    zStack3x0

Coordinator revision
    20221226

Coordinator IEEE Address
    0x00124b0018e306eb

Frontend version
    0.6.124
    
    Any help would be great thanks

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will attach state.json.zip
[state.json(1).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/10723186/state.json.1.zip)

**Comment by sblessley** [comment]
Same problem; Edge browser 116.0.1938.76 (Official build) (64-bit)

I have restarted Z2M (environment: HA add-on; HA under proxmox)

state.json.zip attached.
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/12579843/state.json.zip)

**Comment by Supadone** [comment]
Hi
I've had the same problem for a long time and was hoping that an update would solve it, but unfortunately not.
I have the problem with Safari and Chrome, cookies have already been deleted. Since the problem apparently only occurs rarely, does anyone have an idea where the error could be? Z2M runs on a Raspberry Pi 4

**Comment by Flyer11111** [comment]
I found this out

Backup and restore is not supported for any other adapters (ConBee/Raspbee, EZSP and Zigate). First make sure you are running the latest version of Zigbee2MQTT ...
