### ISSUE TITLE
Expose /version ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [nurikk/z2m-frontend#169]
This is a feature request :)

I would like to get the current version of z2m via the new user interface. Maybe like http://z2m/version ?

I know there is the information in Settings -> About, but I need to directly parse html ...

Thanks,

**Comment by nurikk** [comment]
> This is a feature request :)
> 
> I would like to get the current version of z2m via the new user interface. Maybe like http://z2m/version ?
> 
> I know there is the information in Settings -> About, but I need to directly parse html ...
> 
> Thanks,

Get it directly from mqtt
