### ISSUE TITLE
Missing a favicon.ico

### ISSUE THREAD

**Issue by PedroLamas** [nurikk/z2m-frontend#17]
If @Koenkk allows it, I propose the one from the Zigbee2mqtt docs: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/favicon.ico

**Comment by Koenkk** [comment]
I'm wondering if Zigbee2MQTT is even allowed to use this (got it from: https://www.google.com/search?q=bee+favicon&safe=off&rlz=1C1GCEU_nlNL822NL822&sxsrf=ALeKk037356ccOMzxmh0pxraRZZXctt-Fg:1601289779729&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj814Kk1YvsAhWHzKQKHbbnDAgQ_AUoAXoECAsQAw&biw=1920&bih=969&dpr=1#imgrc=fClwDUGBeCU0gM) Maybe we should switch to a different icon instead.

**Comment by PedroLamas** [comment]
Ah, I thought the current one was a custom one... in that case, how about asking if someone on the zigbee2mqtt community wants to take a stab in designing a brand new one? 🙂

**Comment by Koenkk** [comment]
I made a favicon based on the zigbee2mqtt logo. You can find it here: https://raw.githubusercontent.com/Koenkk/zigbee2mqtt.io/master/docs/favicon.ico

**Comment by Landrash** [comment]
@Koenkk Looks good but maybe make wings gray to separate them from the rest of the bee?

**Comment by nurikk** [comment]
Welcome the new favicon in latest dev
<img width="208" alt="Screenshot 2020-09-29 at 07 11 42" src="https://user-images.githubusercontent.com/1525421/94495071-5e0db680-0223-11eb-8496-3229b0fde110.png">

**Comment by nurikk** [comment]
Done
