### ISSUE TITLE
SEA802 wrong battery info.

### ISSUE THREAD

**Issue by SargonofAssyria** [nurikk/z2m-frontend#170]
The SEA802 Thermostat displays wrong battery info.
It state is 'false' and that translates to 'battery_low' it should be the other way around.
![2020-12-02_19-44-50](https://user-images.githubusercontent.com/24824113/100917136-0a477400-34d7-11eb-90bb-8259d53b6f9d.png)
![2020-12-02_19-45-10](https://user-images.githubusercontent.com/24824113/100917143-0d426480-34d7-11eb-94f6-ba639af741c7.png)

**Comment by nurikk** [comment]
This data comes from buggy converter, do you see `"battery_low": "false"` it should be `"battery_low": false`
Error comes from this place (and few more)

https://github.com/Koenkk/zigbee-herdsman-converters/blob/6c4bc1a8b867f7bd8c9d3204449274cc4f69435e/converters/fromZigbee.js#L486

**Comment by Koenkk** [comment]
Fixed
