### ISSUE TITLE
[Feature request]: Fine grained log configuration

### ISSUE THREAD

**Issue by VincentSC** [nurikk/z2m-frontend#1712]
**Is your feature request related to a problem? Please describe.**
When trying to debug a problem, it is impossible to use the logs - it's just a large stream of unrelated messages.

I've got 145 devices and since I have 30+ devices I find it difficult to work on the Z2M project, and have given up multiple times as the logs are not convenient.

**Describe the solution you'd like**
It would help if there are possibilities to have a more fine-grained way to configure:
- live devices: seen in last x days
- disconnected devices: at least x days not seen
- new device: configure, interview, etc
- a specific device, by ID
- M2Z specific commands
- Coordinator related
- ...

This way I can focus on debugging what I want.

**Describe alternatives you've considered**
Improved logging where the source is more complete and can be more easily parsed. This would mean enrichment of the device-info, instead of the suggested filtering within the frontend.

**Comment by Impact123** [comment]
Unstale.

**Comment by VincentSC** [comment]
Ooooh :(
