### ISSUE TITLE
[Bug]: No devices in Frontend when using DNS rewrites

### ISSUE THREAD

**Issue by dominikhoebert** [nurikk/z2m-frontend#1718]
### What happened?

If connected to the frontend by port:ip everything works fine. I use Adguard and NGINX Proxy Manager to set a local DNS rewrite http://zigbee2mqtt.home. The frontend is accessible, but it does not show the zigbee devices (empty list), also all the settings in the settings menu are hidden. Not sure if bug or wanted behavior, and just wrong configuration.

I tried to set the URL in the frontend settings without any success. 

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
hello, have you tried sample config from this article?
https://www.zigbee2mqtt.io/guide/configuration/frontend.html#nginx-proxy-configuration
