### ISSUE TITLE
[Bug]: Can't see zigbee mqtt in add-on store as repository, but is working fine

### ISSUE THREAD

**Issue by atv2016** [nurikk/z2m-frontend#1733]
### What happened?

See above. It's working fine, but i want to update but i can't find it added to the add on store (when one goes to the ...) so i have no way of updating.

### What browsers are you seeing the problem on?

Chrome, Safari

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by atv2016** [comment]
@Koenkk Sorry to shout out, but would you know what do about this problem? Have you seen it before maybe?
Should i just try and add it again ?

Not sure if you also maintain the HA integration for zigbee mqtt. 

Thanks for your help.

**Comment by atv2016** [comment]
Just to add, if i click on changelog in the add-on (where configuration, log, etc is) it says:
Addon 45df7312_zigbee2mqtt with version latest does not exist in the store

Weird? Maybe it's best to add it again? Just hope it's not going to break anything.

**Comment by Koenkk** [comment]
Are you using the correct repo? Should be https://github.com/zigbee2mqtt/hassio-zigbee2mqtt

**Comment by atv2016** [comment]
I think so? I don't have any repo's currently added in my add on store for zigbee mqtt, strangely enough.

If i click on the zigbee mqtt website link in the add-on, yes it takes me to that repo.

**Comment by atv2016** [comment]
Well i'm glad it to say it got resolved simply by re-adding the repository to the add-on store. It then also saw it was out of date and i updated it.

**Comment by Koenkk** [comment]
Great! I assume this can be closed now.

**Comment by atv2016** [comment]
Yup close it please, thanks for your help!
