### ISSUE TITLE
[Bug]: Request backup feature produces zip file where all filenames are truncated

### ISSUE THREAD

**Issue by aofc** [nurikk/z2m-frontend#1735]
### What happened?

When using the Request backup button, it takes a while but it ends up producing a zip file that I can download. Problem is, inside this zip file, all filenames are truncated, missing their first character. Have been experiencing this issue with this backup feature since it was introduced a while ago. I figured it would get fixed some day... Am I the only one having this issue? Using the latest dev version.

![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/23260814/711298ce-a13f-473c-885d-45e8a07bc0ea)

Tested on Edge & Chrome. Trying to reproduce the bug on Firefox led to an error with the JSZip module in Firefox's Dev console when trying to download the file: "Uncaught DOMException: The URI is malformed." and a warning about XMLHttpRequest: "Using XMLHttpRequest synchronously on the main thread is deprecated due to its negative impact on end-user navigation."  

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
@Koenkk hey mate, can you please have a look? something strange here

**Comment by Koenkk** [comment]
On what system are you running z2m?

**Comment by aofc** [comment]
Hey sorry it seems I never got back to you. This is actually still an issue. I'm running Debian 11. It's a pretty standard setup. Maybe it's related to a library you're using for this backup feature? I'm sure I'm not the only one with this, am I? I'm running the latest stable version now.

I tested the "download state" button which also produces a zip file. It doesn't have the same problem. Strange.
