### ISSUE TITLE
GZCGQ01LM - MiJia light intensity sensor - display illuminance in dashbaord

### ISSUE THREAD

**Issue by jomuc** [nurikk/z2m-frontend#1761]
**Is your feature request related to a problem? Please describe.**
not related to a problem.

**Describe the solution you'd like**
Would it be possible to add illuminance and illuminance_lux in dashboard view like for other devices e.g. [RTCGQ14LM](https://www.zigbee2mqtt.io/devices/RTCGQ14LM.html#xiaomi-rtcgq14lm)?
At the moment, dashboard shows only power outage counter. link quality and battery.

**Describe alternatives you've considered**
no idea, how to configure/customize dashboard views.

**Additional context**
Status information:
{
"battery": 100,
"illuminance": 32323,
"illuminance_lux": 1707,
"last_seen": "2023-08-07T05:11:43.930Z",
"linkquality": 160,
"power_outage_count": 12,
"voltage": 3124
}

**Comment by danieledwardgeorgehitchcock** [comment]
This should just be a case of adding the illuminance values to the exposes section (you could probably copy the code from the other device's converter for that) in the Zigbee Herdsman Converter project

**Comment by jomuc** [comment]
Thanks for your hint. I will ask for a change in zigbee-herdsman-converter.
