### ISSUE TITLE
[Bug]: Light mode no longer works

### ISSUE THREAD

**Issue by KameDomotics** [nurikk/z2m-frontend#1778]
### What happened?

After updating to the latest add-on version (1.33.0-1) the day mode is not maintained after closing/reopening the Zigbee2mqtt UI.

Is there any way to set the day mode by default?

(Problem detected with Safari browser and with Home Assistant companion app)

### What browsers are you seeing the problem on?

Safari

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by KoalaWerewolf** [comment]
I'm experiencing the same issue. z2m 1.33.0, HA 2023.8.4, Firefox 117.0

**Comment by JackTalisker** [comment]
Same thing on Google Chrome and Microsoft Edge

**Comment by keithr59** [comment]
Same issue on Opera.

It looks like it may have been caused by PR: https://github.com/nurikk/zigbee2mqtt-frontend/pull/1763

**Comment by andyblac** [comment]
it would be nice have the option to disable auto mode.

**Comment by JackTalisker** [comment]
Waiting for the patch, for those who want to get the light theme back, select it then delete the two stored cookies (local + session).
The light mode will persist (until you select the dark one again).

**Comment by JackTalisker** [comment]
Waiting for the patch, for those who want to get the light theme back, select it then delete the stored cookie (the local one is enough).
The light mode will persist (until you select the dark one again).
