### ISSUE TITLE
Two times OFF in Exposes tab

### ISSUE THREAD

**Issue by 1igeza** [nurikk/z2m-frontend#179]
In exposes tab -> status there is OFF switch OFF. I checked it on PC and in Phone browser the same issue. It's only cosmetic, button works correctly. 
zigbee2mqtt version
    1.16.2-dev commit: 4078f2d
coordinator type
    zStack3x0
coordinator revision
    20201113
frontend version
    0.2.106
.
![Bez tytułu](https://user-images.githubusercontent.com/39980292/101802652-fa034a80-3b0f-11eb-93f1-405c431140bd.png)

**Comment by salopette** [comment]
![sshot-1](https://user-images.githubusercontent.com/32480002/101819844-114d3280-3b26-11eb-84ed-ee7531db24be.jpg)
