### ISSUE TITLE
[Bug]: Xiaomi DJT11LM not showing setting headers

### ISSUE THREAD

**Issue by oneseventhree** [nurikk/z2m-frontend#1792]
### What happened?

Unsure what these settings are as there is no headers (in pink)
<img width="439" alt="Screenshot 2023-10-04 at 7 18 17 am" src="https://github.com/nurikk/zigbee2mqtt-frontend/assets/15043282/6ac1f3b3-7b30-44c2-b20a-f143c6161353">

I am guessing some are angle and sensitvity but not sure of the rest

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Rotzbua** [comment]
Can confirm also for other devices.

PR incoming.
