### ISSUE TITLE
MQTT topics are empty at moment of the frontend start

### ISSUE THREAD

**Issue by Hacker-CB** [nurikk/z2m-frontend#18]
I found strange behavior on my network with 116 devices:

- Start z2m
- Z2m published all restored states to MQTT. Frontend still not ready, no respond on port 8099.
- Frontend ready. Last seen is N/A (Because MQTT topic is empty at moment frontend started, I have only `availability:true` in my setup, because it is retained) 

So, I think you need force z2m to republish all devices last state after each start. (May be push to `devices/get` topic?)

**Comment by nurikk** [comment]
Frontend doesn't interact with MQTT, it has it's own API

**Comment by nurikk** [comment]
Maybe @Koenkk can help with this

**Comment by Koenkk** [comment]
@Hacker-CB after you restart Zigbee2MQTT, I believe you will also need to reload the frontend

**Comment by Hacker-CB** [comment]
I reloaded frontent with CMD-R in Safari.

**Here is situation with N/A in frontend:**

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/4232995/94793522-42510e80-03e3-11eb-927a-abf5b495b45b.png">

**Parse database.db (match thermometer)**

<img width="602" alt="image" src="https://user-images.githubusercontent.com/4232995/94793554-4ed56700-03e3-11eb-8573-defdb0847c0f.png">

**Comment by Hacker-CB** [comment]
Every time after restarting z2m and reloading frontend web page it shows `N/A` for all devices until receive any new message from devices.

**Comment by Hacker-CB** [comment]
Seems that problem is on the frontend side.
I restarted z2m and all `last seen` value kept. But all became `N/A` after refreshing frontend.

**Comment by Hacker-CB** [comment]
Double checked. All `last_seen` became `N/A` after each frontend refresh

**Comment by timoline** [comment]
same here

**Comment by nurikk** [comment]
This happens because the retain option isn't set. Enabling 
```yaml
device_options:
  retain: true
````
will solve this issue. 

FYI https://github.com/Koenkk/zigbee2mqtt/blob/1bccc5d9f17be93c1f680f8ed2d37cbbc0aef0fd/lib/extension/frontend.js#L108

**Comment by timoline** [comment]
thank you, lookslike this fixed the issue.
But I think this isnt a well kwown option for most  of us...

**Comment by kennymc-c** [comment]
For me it does not work with the retain function activated. After reloading the page several devices, which had a Last Seen value before, are back on N/A. For some devices, which send a value very often, it seems to work. But with almost all battery powered devices the value is not stored.

**Comment by nurikk** [comment]
Fixed in latest dev, reopen if occurs again
