### ISSUE TITLE
[Bug]: missing icons on dashboard

### ISSUE THREAD

**Issue by Rotzbua** [nurikk/z2m-frontend#1805]
### What happened?

Some properties have no icon.

Action:
![grafik](https://github.com/nurikk/zigbee2mqtt-frontend/assets/7337347/87778a3e-dacc-4234-952f-7b802679b492)

humidity_alarm / temperature_alarm:
![grafik](https://github.com/nurikk/zigbee2mqtt-frontend/assets/7337347/0273a6b4-ad9c-4557-ae3a-b02521263e69)

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by xrust83** [comment]
there are no icons for several reasons:
1. You need to decide on the design of the icon, it is sometimes quite difficult to come up with it.
2. If you have selected an icon, it should be found in the list of awesome fonts
3. The icon must be free
4. You can add it by opening PR =)
