### ISSUE TITLE
Feature request form logging output.

### ISSUE THREAD

**Issue by SargonofAssyria** [nurikk/z2m-frontend#182]
I am on:
`zigbee2mqtt version 1.16.2-dev commit: e0fa681
coordinator type        zStack3x0
coordinator revision  20201113
frontend version        0.2.107`
It would be nice if there could be a filter in the logging output for 'error' output or a separate tab for 'error' output

**Comment by bochelork** [comment]
I just wanted to request a filter as well, just a text filter so I can trace a specific device. With 60 devices in a network it's hard to track the logs.

**Comment by bochelork** [comment]
Thanks!

**Comment by SargonofAssyria** [comment]
Tnx, works perfect.

**Comment by timoline** [comment]
nice feature, but unfortunatly it broke the coloring
