### ISSUE TITLE
[Bug]: Duplicated values in database.db and Reporting tab in frontend

### ISSUE THREAD

**Issue by emandtf** [nurikk/z2m-frontend#1829]
### What happened?

I'm not sure if it is related to frontend or not, but starting from 1.33 it started to happens.
I just updated to latest 1.33.2 but nothing changed.
Same thing for DEV branch.

In "Reporting" tab, submitting a value (even the same already present!) by using appropriate "Apply" blue button, generates a **duplicated value in "database.db"** and even in that Reporting page.
![duplicated01](https://github.com/nurikk/zigbee2mqtt-frontend/assets/13537385/20086511-c6f9-4423-a7a3-3c3adc9b8948)

The duplicated label seems be written in Database with the additional "_manufacturerCode: null_" that the original one doesn't has.
Normal value in database.db was:

> {"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":5,"repChange":2}

The duplication is inserted next to the previous:

> {"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":5,"repChange":1,"manufacturerCode":null}

If I try to remove the duplicated one by using "Disable" red button it works, but if I try to remove even the original one I get a "green toast notification" for the "successfully" action but nothing changes: the original value remains both in database and in "Reporting" tab.
At this point if I really want to remove that Endpoint from Reporting page, I need to stops Z2M and manually edit database.db file.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Did you download state.json.zip?

I will NOT attach state.json.zip (there isn't anything useful there for this issue)

**Comment by PVi1** [comment]
I'm experiencing the same issue. To make matters worse, in my case with Develco, when I attempted to remove the original temperature reporting entry, the device stopped reporting the temperature. I returned home after two days, only to realize that our bedroom would be quite cold tonight. :-)

When I tried to customize reporting entry, I end with duplicate records visible in state.json, too.
![Screenshot from 2023-11-15 22-37-37](https://github.com/nurikk/zigbee2mqtt-frontend/assets/4092388/7bfcd8a9-24bc-4a5b-bc6f-e75581d7dd2a)

![Screenshot 2023-11-15 at 22-09-06 Zigbee2MQTT](https://github.com/nurikk/zigbee2mqtt-frontend/assets/4092388/37705ca2-e731-4279-8626-b42f917b2b1f)


Moreover, the new entry appeared in the table after the last updates, probably, the one with manuSpecificPhilips2.

**Comment by nurikk-sa** [comment]
Hey @Koenkk can you have a look on this?

**Comment by Koenkk** [comment]
will be fixed in https://github.com/Koenkk/zigbee2mqtt/issues/19317

**Comment by emandtf** [comment]
The bug has returned again after updated from 1.39.0 to 1.40.0.....
