### ISSUE TITLE
Device page should have padding around battery icon

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#184]
![image](https://user-images.githubusercontent.com/379665/102012091-b34c6500-3d48-11eb-95af-68964f47f60a.png)

**Comment by nurikk** [comment]
This one is fixed long time ago, consider upgrading to latest dev

**Comment by sjorge** [comment]
That was the latest dev (z2m) and the the latest front end release installed on top to check

**Comment by sjorge** [comment]
.107, I just checked. I wonder if it’s some odd caching thing

**Comment by sjorge** [comment]
Seems to be a caching thing. I took my old iphone 6 for testing and there it's fine.
