### ISSUE TITLE
[Bug]: Notifications are persistent and do not disappear without interaction

### ISSUE THREAD

**Issue by pyrodex** [nurikk/z2m-frontend#1847]
### What happened?

Prior to https://github.com/nurikk/zigbee2mqtt-frontend/releases/tag/0.6.145 the notifications would eventually go away without user interaction decluttering the web UI. Since that change the notifications are basically persistent without either clicking them off one by one or reloading the entire UI. The clicking off thing can honestly lead to misclicks as you are trying to clear them off to see what is going on. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Koenkk** [comment]
@nurikk I think adding 


```
  dismiss: {
    duration: 5000,
    onScreen: true
  }
```

here: https://github.com/nurikk/zigbee2mqtt-frontend/commit/1f477f15519a084cd1733ad6ed9635ecbe311063#diff-2cd355da31190d161942aed16965a60bba98b533e29ab5cd382ee50d3ecdae75R55 will fix it

**Comment by theDiverDK** [comment]
Fingers crossed it will be fixed soon :-)

**Comment by vygi** [comment]
Same problem also in the Home Assistant App (Android). Very disturbing.

**Comment by DataGhost** [comment]
Looks fixed in 0.6.149 but this ticket wasn't mentioned in the commit or release message.

**Comment by theDiverDK** [comment]
Thanks DataGhost

Hope the docker image will be updated soon as well 😊

**Comment by Koenkk** [comment]
Confirmed that this issue is solved in the latest dev, thanks @nurikk !

**Comment by theDiverDK** [comment]
@Koenkk Any ETA when the docker image has the new changes?

Thanks? 😊

**Comment by Koenkk** [comment]
It's already available in the dev docker image, next z2m release is on 1 January.

**Comment by theDiverDK** [comment]
Thanks for the quick answer 😊
