### ISSUE TITLE
[Bug]: Error 2023-12-06 17:24:28 Publish 'set' 'scene_store' to 'Guest room Wardrobe light strip' failed: 'Error: Not a group'

### ISSUE THREAD

**Issue by Luligu** [nurikk/z2m-frontend#1853]
### What happened?

When you try to set a scene on a device (not a group) you get the message:
Error 2023-12-06 17:24:28Publish 'set' 'scene_store' to 'Guest room Wardrobe light strip' failed: 'Error: Not a group'

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
Error 2023-12-06 17:24:28 Publish 'set' 'scene_store' to 'Guest room Wardrobe light strip' failed: 'Error: Not a group'
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
