### ISSUE TITLE
[Bug]: IKEA switch not visible on Dashboard

### ISSUE THREAD

**Issue by 0crap** [nurikk/z2m-frontend#1856]
### What happened?

As the title says, my [IKEA switch](https://www.zigbee2mqtt.io/devices/E1743.html#ikea-e1743) is not visible on the Dashboard.

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Cosmeen** [comment]
Hello @0crap,
As this issue is very old, I would try reconnecting the switch.

**Comment by 0crap** [comment]
Thx, this was fixed long ago.
