### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by quantummobile** [nurikk/z2m-frontend#1863]
### What happened?

Since the UI of lof toasts have changed, they just pile up in a stack that end up filing all the vertical space of the screen and then just stays there, unless you remove them one-by-one by clicking on each and every one on them. So annoying. That was not the case with previous toasts UI. They just stayed for a bit and then removed themselves.
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/47085307/1bc5803f-daf8-48ca-b915-847ce88d2c48)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
It’s fixed in the latest dev version

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by quantummobile** [comment]
> Hi, try to switch to the latest dev branch
> 
> https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

Hey,

Thanks for the reply. 

Now that I know that you’re aware of this bug, I’ll wait for a stable version with the fix.
