### ISSUE TITLE
Better handling of notification dismissal

### ISSUE THREAD

**Issue by rsyring** [nurikk/z2m-frontend#1868]
**Is your feature request related to a problem? Please describe.**

Notifications stack up on the right side of the screen and can take a ridiculous amount of effort to clear them all.  I recently added over a dozen devices and then kicked off some firmware updates.  I figured out that I could click a notification to get rid of it.  But there were a lot of them and over time they stacked up way beyond the top of the screen.

![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/109467/a035873e-465d-499d-b3e8-860bb413a95c)

**Describe the solution you'd like**

Auto-dismiss notifications or add UI option to dismiss all notifications at once.

**Describe alternatives you've considered**

I refresh the page but that's not ideal.

**Additional context**

I'm using the HA add-on.

**Comment by Koenkk** [comment]
This has already been fixed, fix will be included in the 1 January Z2M release
