### ISSUE TITLE
Zigbee2MQTT Proxy - Change name in sidebar

### ISSUE THREAD

**Issue by swissjon** [nurikk/z2m-frontend#1879]
**Is your feature request related to a problem? Please describe.**
I run 2 instances of z2m, HA addon and Docker. The z2m proxy would be very helpful to show everything in HA, however the name in the sidebar is Zigbee2MQTT for both instance, so I have 2 items called Zigbee2MQTT. A minor inconvenience, but confusing. 

**Describe the solution you'd like**
In the config section of Zigbee2MQTT Proxy, allow customization of the name displayed in the sidebar. 

**Describe alternatives you've considered**
Right now I'm using panel_iframe: in yaml. This works fine except when accessing remotely.

**Comment by Koenkk** [comment]
This issue belongs to https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
