### ISSUE TITLE
[Cosmetic/Typo]: German "Asudruck" must be "Ausdruck" under "Einstellungen" tab 

### ISSUE THREAD

**Issue by ItsaBastI** [nurikk/z2m-frontend#1901]
### What happened?

In the "Einstellungen" tab of a device, the full sentence is "Attribute mittels regulärem Asudruck aus publiziertem Payload filtern." where the word "Asudruck" must be "Ausdruck".
Unfortunately POEditor won't allow more contributors to German.

### What browsers are you seeing the problem on?

Safari

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by pano9000** [comment]
This appears to be fixed in the meantime, as I can confirm with v0.6.156
Could you close the issue as done please?
