### ISSUE TITLE
Show last updated timestamp

### ISSUE THREAD

**Issue by voltagex** [nurikk/z2m-frontend#1914]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I don't notice that one of my sensors hasn't been reported for some time.

**Describe the solution you'd like**
In the frontend, please give me a last updated timestamp for each device shown and highlight any devices that haven't reported for a while.

**Describe alternatives you've considered**
Forgetting about Zigbee and waiting 10 years for Apple to make Thread work well.

**Additional context**

Edit: ah damn, all of my devices are N/A - this should be bigger and easier to see.

**Comment by nurikk** [comment]
Hello! Z2m has couple of mechanisms for your issue. Try to check documentation on last_seen and availability features

**Comment by voltagex** [comment]
@nurikk yep, my mistake. It wasn't clear that I needed to update the configuration in Home Assistant in YAML mode, then also click the enable button in the z2m interface.
