### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by lgLindstrom** [nurikk/z2m-frontend#192]
Following this instruction https://www.zigbee2mqtt.io/information/frontend.html  I get connection refused when trying to connect from other computer

Guess I done something wrong but please help a newbe ... :)

**Comment by nurikk** [comment]
Try to explore ’host’ property in frontend config

**Comment by lgLindstrom** [comment]
I have tried 0.0.0.0 and 192.168.68.202   which is IP of the pi.
Probably I should have mentioned that I am trying to connect remotly from my PC.

**Comment by lgLindstrom** [comment]
Any help on this issue??

**Comment by mhrynovets** [comment]
I'm facing same trouble.
'host' 0.0.0.0 or IP of pi doesn't help. 
**netstat** says, that desired port is **not** LISTENING.
z2m installed as addon on HA-supervised.

**Comment by mhrynovets** [comment]
Trouble is on addon side - defined in config port is not proxied outside of z2m docker image.
Using proxied port for Socat 8485 solved this.

**Comment by dirkclemens** [comment]
@mhrynovets any hint for the socat solution?

`socat TCP4-LISTEN:8080,fork TCP4:[192.168.2.222]:8089`
with z2m running on the box with the ip 192.168.2.222, port 8080 configured in the configuration.yaml and port 8089 for access from a remote machine? what is the correct command? is that called within the container? if so, how can I configure docker to call socat? Thanks for supporting
