### ISSUE TITLE
[Bug]: Front end looks snappy

### ISSUE THREAD

**Issue by vladimircristian90** [nurikk/z2m-frontend#1924]
### What happened?

After update to 1.35.3 on Windows, frontend looks snappy
![Screenshot 2024-02-07 124658](https://github.com/nurikk/zigbee2mqtt-frontend/assets/2479185/5370bd0d-2511-45ef-8b0b-d702ef9c3c6d)

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by piren62** [comment]
I've tried with firefox and works fine. The problem is with chrome
:)

**Comment by almirus** [comment]
https://github.com/nurikk/zigbee2mqtt-frontend/issues/1921#issuecomment-1930728402

**Comment by vladimircristian90** [comment]
Workaoround: go into the site settings in chrome and delete data.
