### ISSUE TITLE
[Bug]: LYWSD03MMC (with devbis 1.1.0 firmware) does not appear on the dashboard

### ISSUE THREAD

**Issue by KennethLavrsen** [nurikk/z2m-frontend#1926]
### What happened?

A LYWSD03MMC (with devbis 1.1.0 firmware) do not appear on the dashboard

The devices load correctly and also report correctly to Home Assistant via MQTT.
But they are not at all shown on the Zigbee2MQTT dashboard as if they do not exist

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant stacktrace

```shell
No trace
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by KennethLavrsen** [comment]
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/14234119/state.json.zip)

**Comment by KennethLavrsen** [comment]
This was earlier reported on https://github.com/Koenkk/zigbee2mqtt/issues/21322 but closed with note to open bug here

And also reported here https://github.com/Koenkk/zigbee2mqtt/issues/21274  still open as I type this

**Comment by lbarjak** [comment]
GZCGQ01LM does not appear either.

**Comment by edrzns** [comment]
same for pvvx's forked formware

**Comment by gkfirst8** [comment]
My ROB_200-003-1 is also not showing up in the Dashboard. (It does have 'Exposes' with Sate & Linkquality)

What are the rules for it to show up in the Dashboard?

Attached by state:
[state.json(1).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/14314436/state.json.1.zip)

**Comment by janusjanusjanus** [comment]
Same situation here (1.36.0). The devices are listed under "devices" but not in the dashboard.

**Comment by KennethLavrsen** [comment]
Problems seems to have been fixed. I just noticed that the devices are shown in the dash board now and I did not upgrade any firmware. Great. Closing. Thanks

**Comment by KennethLavrsen** [comment]
Closing
