### ISSUE TITLE
Out of date z2m dependencies breaking the dev console

### ISSUE THREAD

**Issue by mrskycriper** [nurikk/z2m-frontend#1939]
Recently notices that frontend fails to recognize recently renamed `manuSpecificLumi` cluster, showing the old name `aqaraOpple`. But since this cluster name is no longer used in `zigbee-herdsman`, any attempt at accessing it from dev console results in failure. It is also no longer seen on endpoint-cluster graph.

The exact place, where it's causing a problem is [here](https://github.com/nurikk/zigbee2mqtt-frontend/blob/dev/src/components/device-page/AttributeEditor.tsx). Cluster list is imported from `zigbee-herdsman`. The up to date version of which is `0.34.9`, while the version used by this project is `0.19.0`.

Also `zigbee-herdsman-converters` is out of date. Current version is `18.40.0`, while this project uses `15.87.0`. While I didn't have any priblems with it myself, it is still being used [here](https://github.com/nurikk/zigbee2mqtt-frontend/blob/ffafc981998f1b0c4013e6a6b1f3e8d920dd204a/i18n-z2m-exporter.js#L1).

**Comment by rccoleman** [comment]
Looks like these dependencies were updated within the last day to the latest versions, but aren't all available in the latest UI release.
