### ISSUE TITLE
[feat] Toggle/Setting to display network addresses in decimal format.

### ISSUE THREAD

**Issue by Nerivec** [nurikk/z2m-frontend#1971]
**Is your feature request related to a problem? Please describe.**

Network addresses in frontend are displayed in hex format, but all Z2M logging is in decimal format, making it harder to quickly identify devices (have to [convert](https://www.rapidtables.com/convert/number/decimal-to-hex.html) every time).

**Describe the solution you'd like**

A toggle or setting somewhere to display network addresses in decimal or hexadecimal format in frontend.

https://github.com/nurikk/zigbee2mqtt-frontend/blob/03f1c801235cc65cf8ff7c5d3c01a84209759e94/src/components/device-page/info.tsx#L141

https://github.com/nurikk/zigbee2mqtt-frontend/blob/03f1c801235cc65cf8ff7c5d3c01a84209759e94/src/components/zigbee/DevicesTable.tsx#L113

**Describe alternatives you've considered**

Switching all Z2M logging to hex is not practical.

**Comment by supaeasy** [comment]
@Nerivec Is there a special way to convert? For example I have the following error:


`zh:ember: Delivery of MULTICAST failed for "65533" [apsFrame={"profileId":260,"clusterId":6,"sourceEndpoint":5,"destinationEndpoint":255,"options":1024,"groupId":256,"sequence":226} messageTag=255]`

And 65533 converts to FFFD or 0000FFFD - but there is not a single device in my Z2M list that matches FFFD. What am I doing wrong?

**Comment by Nerivec** [comment]
For multicast/broadcast, addresses are special, since they target the whole network, not just a single device. They mean the following:
```
0xFFFB = Low power routers only
0xFFFC = All routers and coordinator
0xFFFD = All non-sleepy devices
0xFFFF = All devices including sleepy end devices
```

---

Can also check this tool I made to parse Z2M `ember` logs https://nerivec.github.io/z2m-ember-helper/ (`ember` only, as `ezsp` doesn't implement most of the underlaying features that the tool uses). It will try to provide some automatic feedback (the more hours of logs, the better).
Be sure to create a [feature request](https://github.com/Nerivec/z2m-ember-helper/issues) if you get any idea for it😉
