### ISSUE TITLE
Allign LQI to the right

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#20]
in the table, please allign LOI to the right, (allign numbers always to the right)

**Comment by nurikk** [comment]
What's LOI?

**Comment by timoline** [comment]
LQI ;-)

![image](https://user-images.githubusercontent.com/680252/94927203-3c7e2a80-04c2-11eb-8637-759d37564f71.png)

**Comment by timoline** [comment]
why are all my suggestions closed?
they are not implemented or discussed
