### ISSUE TITLE
exposes  type

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#201]
Since exposes now have a type: climate, fan, cover, lock, light , switch etc

https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/exposes.md#exposes

Maybe an idea to show the type in the devices list?

**Comment by nurikk** [comment]
What problem this is going to solve?

**Comment by timoline** [comment]
The problem :-)
currently on the device list, you cannot see the type and sort by it....it could be handy

**Comment by nurikk** [comment]
Devices have multiple exposed features, we don't have single feature that defines device class. And this is quite far fetched "problem"

**Comment by timoline** [comment]
As far as I understand the documentation, devices can have multiple exposed features, but is defined by a type.

```
{
    "type": "switch",
    "features": [
        {"type":"binary","name":"state","property":"state","value_on":"ON","value_off":"OFF","value_toggle":"TOGGLE","access":7}
    ]
}
```

so a device has its own type, or?
