### ISSUE TITLE
[Bug]: "Localise device images" button is glitched in English but not on other translations

### ISSUE THREAD

**Issue by x-magic** [nurikk/z2m-frontend#2028]
### What happened?

A new feature was added in https://github.com/nurikk/zigbee2mqtt-frontend/issues/1477#issuecomment-1818877608 to cache device images locally. The feature works, but it seems the frontend button is broken. Some languages (such as zh-CN and fr) the button works fine: 
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/3180639/45765328-6427-4236-b7dd-b6d8b63027b9)
also it's understandable if it's not localised yet, it won't show up (such as in pt-BR): 
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/3180639/c4b72519-e6c2-4799-92d7-a973d8aa6c69)
 but it would be strange that it won't show up in English: 
![image](https://github.com/nurikk/zigbee2mqtt-frontend/assets/3180639/12c54dd0-fea7-48db-b63a-8de9d231671d)
despite it's available in the language files: 
- https://github.com/nurikk/zigbee2mqtt-frontend/blob/81c13ba5e86c126c212f76d5253e2bc09c1ee204/src/i18n/locales/en.json#L2613
- https://github.com/nurikk/zigbee2mqtt-frontend/blob/81c13ba5e86c126c212f76d5253e2bc09c1ee204/src/components/settings-page/image-localiser.tsx#L85-L90

### What browsers are you seeing the problem on?

Firefox, Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Koenkk** [comment]
This is fixed now!
