### ISSUE TITLE
frontend fails to load data

### ISSUE THREAD

**Issue by Leinetaler** [nurikk/z2m-frontend#203]
Hi,
i started my Linux journey beginning december and implemented mosquitto, zigbee2mqtt and node-red as service successfully on raspberry pi4.

everything works fine but only the frontend which is starting ok, fails to load data - accessed direcly via webbrowser localhost:portnumber (in my case actually 1881).

zigbee2mqtt works fine and i use an node-red admin interface to joyn or rename.

can you give me a hint where to look after as iḿ running out of ideas and www search findings to follow.?

every feedback is very appreciated!

sunny regards

**Comment by nurikk** [comment]
Hi, this doc should help

https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/frontend.md

**Comment by Leinetaler** [comment]
Hi nurikk,
many thanks for your great development and effort to anser my question!
I read your great documentation more than a dozen times and use it for copy and paste the cammands - itś really nooby-friendly :-) 

As with your frontend definitions from that page (which i actually tested again - for prove before answer) the frontend load the top menu - which works, but it starts with bold message and a running circle:

"Loading, please wait."   and change to "Loading devices takes too long time."

Thats all. the frontend is not able to connect to the very well running zigbee2mqtt service (deployed following your doc).
And it leaves no trace which iḿ able to find with :

"systemctl status zigbee2mqtt.service"

or checking /opt/zigbee2mqtt/data/log/ directly.

**Comment by Leinetaler** [comment]
but i found now https://github.com/nurikk/z2m-frontend and will give that a try  - if my doughter will then relase me from playing with her :-)

**Comment by nurikk** [comment]
You're definitely doing some Nginx(or other) proxying stuff that isn't correctly configured. Try to connect directly to the host:port

**Comment by nmaupu** [comment]
I have the exact same problem using a standalone installation on a RPI.
Zigbee2Mqtt version: 1.16.2
Configuration:

frontend:
  port: 8080
  host: 0.0.0.0

**Comment by nmaupu** [comment]
Nevermind, working ok with version zigbee2mqtt 1.17.0 commit: 07cdc9d 👍

**Comment by Morphy99** [comment]
That's weird I have the same issue today upgrading to stable 1.17. I came from 1.16 Dev and had an issue with my database getting wiped but a backup being made. Everything works fine after restoring it but after restarting Z2M the devices page fails to load.

**Comment by florianschroen** [comment]
Same here. Currently with latest-dev:
```
zigbee2mqtt version    1.17.0-dev commit: 90abc2e
frontend version       0.3.1
```
I am running as docker container via systemd...
```
ExecStart=/usr/bin/docker run --rm --name=%p \
  -e TZ=Europe/Berlin \
  -v z2m-data:/app/data \
  -v z2m-root:/root \
  --device=/dev/ttyACM0 \
  -p 8080:8080 \
  koenkk/zigbee2mqtt:latest-dev
```
Access directly via `http://<host>:8080/`

For me the problems started with:
* docker koenkk/zigbee2mqtt:latest-dev - IMAGE ID f51997fde62c
* Zigbee2MQTT version 1.16.2-dev (commit #016137b)

(initally reported at https://github.com/Koenkk/zigbee2mqtt/issues/4266#issuecomment-752680322)

**Comment by Morphy99** [comment]
I'm running in docker too. I'm not on latest dev although I tempted to give it a try again.
zigbee2mqtt version
1.17.0 commit: 07cdc9d
coordinator type
zStack12
coordinator revision
20190619
frontend version
0.2.129

**Comment by nurikk** [comment]
Do you see anything red in your browser console? In the network tab?

**Comment by Morphy99** [comment]
Like this?
![image](https://user-images.githubusercontent.com/5853979/103758758-89662580-500a-11eb-849e-52ea0eaad217.png)

**Comment by florianschroen** [comment]
Yes. there are no red lines (request-errors) in the network tab.
![Screenshot_20210106_130106](https://user-images.githubusercontent.com/625094/103766973-0fd93200-5020-11eb-879a-1e95867fbd4a.png)

There only some warnings in the console depending invalid pseudo elements and the "io" cookie which will be handled as X-Site-Cookie in the future.
![Screenshot_20210106_130339](https://user-images.githubusercontent.com/625094/103766976-1071c880-5020-11eb-9435-31f6ac960c2a.png)

**Comment by cstoetzer** [comment]
Hi.

I am facing the same problem.  "Loading devices takes too long time"

It happened for the first time after I paired a new device.

zigbee2mqtt version 1.17.0 commit: 07cdc9d

**Comment by nurikk** [comment]
> Hi.
> 
> I am facing the same problem. "Loading devices takes too long time"
> 
> It happened for the first time after I paired a new device.
> 
> zigbee2mqtt version 1.17.0 commit: 07cdc9d
> frontend version 0.2.129

Do you use any proxy or something else? I've done testing on Docker and vanilla installation, everything works fine

**Comment by cstoetzer** [comment]
> Do you use any proxy or something else? I've done testing on Docker and vanilla installation, everything works fine

No. Installation on a Raspberry Pi according to the instructions on zigbee2mqtt.io and after updating to 1.17.0.

**Comment by sunfos2019** [comment]
Have the same problem. Started 2 days ago. Don't know after what it started. Latest stable 1.17.0.
All menus work fine except Devices (screenshot).
Latest Google Chrome (also tried another Chrome installation).
Home Assistant OS 5.9 (VMware)
Home Assistant 2021.1.0
Supervisor 2020.12.7
Frontend 20201229.1
No errors in logs.
zigbee2mqtt works fine.

<img width="1920" alt="2021-01-09_112933" src="https://user-images.githubusercontent.com/51086768/104087223-39d46380-526f-11eb-8179-29c25987e219.png">

**Comment by JoLander** [comment]
I'm facing the same issue after upgrading from 1.16 dev to 1.17 dev.
No proxy nor anything else involved. Pure direct access via localhost and port. 
The frontend shows loading, but ends with the here mentioned error afterwards. 
None of the tabs in the frontend show any data, except the 'log' tab, which shows the mqtt messages fine.

**Comment by JoLander** [comment]
I re-added the option 'new_api: true' in the 'Experimental' section of the configuration.yaml and now it works.
The actual documentation on zigbee2mqtt.io does not mention this anymore in the frontend configuration description.

**Comment by nurikk** [comment]
FYI @Koenkk 

> I re-added the option 'new_api: true' in the 'Experimental' section of the configuration.yaml and now it works.
> The actual documentation on zigbee2mqtt.io does not mention this anymore in the frontend configuration description.

**Comment by cstoetzer** [comment]
> I re-added the option 'new_api: true' in the 'Experimental' section of the configuration.yaml and now it works.
> The actual documentation on zigbee2mqtt.io does not mention this anymore in the frontend configuration description.

For me, unfortunately, it does not help. The option was on for me all the time.

homeassistant: false
permit_join: true
frontend:
->  port: 8088
experimental:
->   new_api: true

**Comment by Morphy99** [comment]
> > I re-added the option 'new_api: true' in the 'Experimental' section of the configuration.yaml and now it works.
> > The actual documentation on zigbee2mqtt.io does not mention this anymore in the frontend configuration description.
> 
> For me, unfortunately, it does not help. The option was on for me all the time.
> 
> homeassistant: false
> permit_join: true
> frontend:
> -> port: 8088
> experimental:
> -> new_api: true

Doesn't work for me either. I had it on previously but removed it to see if it helped with the devices page not loading. Re-adding makes no difference.

**Comment by schamu** [comment]
Hi there,
I can only agree with that. I have exactly the same problem. I have already deleted the database, changed the network key and changed the PID. Then I started to re-pair everything. After a few devices the error was there again. I have 60 devices in my Zigbee network.

**Comment by nurikk** [comment]
Can you verify that you can see this string in your log during z2m start?

`Zigbee2MQTT:info  2021-01-09 19:47:39: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload`

**Comment by cstoetzer** [comment]
Yes.

Zigbee2MQTT:info  2021-01-09 13:02:56: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'

**Comment by nurikk** [comment]
> Yes.
> 
> Zigbee2MQTT:info 2021-01-09 13:02:56: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'

this is quite different, I'm interested in *topic 'zigbee2mqtt/bridge/devices'*

**Comment by schamu** [comment]
I can only find MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload

**Comment by cstoetzer** [comment]
Read incorrectly, sorry.  I cannot see this line.

Maybe the problem comes from here:

Zigbee2MQTT:error 2021-01-09 13:02:57: Failed to call 'Bridge' 'onMQTTConnected' (Error: Cluster 'hvacThermostat' has no attribute '16387'
    at Object.getAttribute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/utils.js:84:19)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:87:36
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:83:43)
    at /opt/zigbee2mqtt/lib/extension/bridge.js:512:60
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/opt/zigbee2mqtt/lib/extension/bridge.js:484:50)
    at Bridge.onMQTTConnected (/opt/zigbee2mqtt/lib/extension/bridge.js:47:20)
    at async Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:381:21)
    at async Controller.start (/opt/zigbee2mqtt/lib/controller.js:167:9))

**Comment by nurikk** [comment]
> I can only find MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload

you don't have new api enabled

**Comment by schamu** [comment]
In the configuration yaml:

experimental:
  new_api: true
frontend:
  port: 8081

**Comment by nurikk** [comment]
> In the configuration yaml:
> 
> experimental:
> new_api: true
> frontend:
> port: 8081

are there any spaces in your yaml config? so far this is incorrect config due to spacing

**Comment by schamu** [comment]
yes, there are spaces

**Comment by JoLander** [comment]
> > Yes.
> > Zigbee2MQTT:info 2021-01-09 13:02:56: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
> 
> this is quite different, I'm interested in topic **'zigbee2mqtt/bridge/devices'**

In the not working version without the new_api option this topic is not shown.
After I added the new_api option back to the configuration, I do get this topic in the log and the frontend is working correctly.

**Comment by cstoetzer** [comment]
I have removed the complete sections "frontend" and "experimental" 
-> restart 

Then I added it back at the end of the config file.
 -> restart

Unfortunately no change. The line is not shown in the log.

**Comment by cstoetzer** [comment]
> Will try the -dev Version.

After the installation of the dev version it works. Curious. Thanks and sorry for the inconvenience.

**Comment by schamu** [comment]
I have now switched everything again to the dev. version. It doesn't work. Same as before.

**Comment by Morphy99** [comment]
> Can you verify that you can see this string in your log during z2m start?
> 
> `Zigbee2MQTT:info 2021-01-09 19:47:39: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload`

I don't have this in my log either. I have this in my configuration.yaml:

```
frontend:
  port: 8080
experimental:
  new_api: true
```
I've noticed this in the log, not sure if it's related:

```
error 2021-01-09 13:52:37: Failed to call 'Bridge' 'onMQTTConnected' (Error: Cluster 'hvacThermostat' has no attribute '16387'
    at Object.getAttribute (/app/node_modules/zigbee-herdsman/dist/zcl/utils.js:84:19)
    at /app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:87:36
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:83:43)
    at /app/lib/extension/bridge.js:512:60
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/app/lib/extension/bridge.js:484:50)
    at Bridge.onMQTTConnected (/app/lib/extension/bridge.js:47:20)
    at async Controller.callExtensionMethod (/app/lib/controller.js:381:21)
    at async Controller.start (/app/lib/controller.js:167:9))
```

**Comment by cstoetzer** [comment]
> I have now switched everything again to the dev. version. It doesn't work. Same as before.

I followed these instructions:

https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html 

I think it has something to do with the database. After the restart / installation, previously paired devices were no longer visible. I had to re-pair them first.

**Comment by Morphy99** [comment]
> > I have now switched everything again to the dev. version. It doesn't work. Same as before.
> 
> I followed these instructions:
> 
> https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html
> 
> I think it has something to do with the database. After the restart / installation, previously paired devices were no longer visible. I had to re-pair them first.

Is your database backed up? I had something similar when swapping back from dev to stable. My database got erased but backed up as database.db.backup or something similar. I renamed it back to database.db and everything worked fine until I restarted z2m and then the devices failed to load. I think I added a TRV as well so I'll try removing that as that error looks possibly related to that.

**Comment by cstoetzer** [comment]
@Morphy99 
> I've noticed this in the log, not sure if it's related:

I had the same error message. After reinstall ( switch to -dev version) it's gone.

**Comment by schamu** [comment]
it is in my log too:

error 2021-01-09 15:15:45: Failed to call 'Bridge' 'onMQTTConnected' (Error: Cluster 'hvacThermostat' has no attribute '16387'
    at Object.getAttribute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/utils.js:84:19)
    at _configuredReportings.map (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:87:36)
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:83:43)
    at devices.zigbee.getDevices.map (/opt/zigbee2mqtt/lib/extension/bridge.js:519:60)
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/opt/zigbee2mqtt/lib/extension/bridge.js:491:50)
    at Bridge.onMQTTConnected (/opt/zigbee2mqtt/lib/extension/bridge.js:48:20))

**Comment by Morphy99** [comment]
Interesting! What hvac devices have you guys got? It's not related to my Tuya TRV I added as I removed it. I have Eurotronic Spirit TRV's apart from this.

**Comment by cstoetzer** [comment]
> Interesting! What hvac devices have you guys got? It's not related to my Tuya TRV I added as I removed it. I have Eurotronic Spirit TRV's apart from this.

Eurotronic Spirit

**Comment by schamu** [comment]
I have 11 Eurotronic Spirit Zigbee. All of them work and can be controlled.

**Comment by sunfos2019** [comment]
Found when the problem starts in my case - after adding new device to network - [DIYRuZ_Geiger](https://www.zigbee2mqtt.io/devices/DIYRuZ_Geiger.html).

After that I restart Zigbee2mqtt and see in its log:
`
hjghjghghjgdf
jgdfhjgdsjfgsdf
`
Zigbee2MQTT:error 2021-01-10 06:18:10: Failed to call 'Bridge' 'onMQTTConnected' (Error: Cluster 'msIlluminanceMeasurement' has no attribute '61441'
    at Object.getAttribute (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/zcl/utils.js:84:19)
    at /zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:87:36
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:83:43)
    at /zigbee2mqtt-1.17.0/lib/extension/bridge.js:512:60
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/zigbee2mqtt-1.17.0/lib/extension/bridge.js:484:50)
    at Bridge.onMQTTConnected (/zigbee2mqtt-1.17.0/lib/extension/bridge.js:47:20)
    at async Controller.callExtensionMethod (/zigbee2mqtt-1.17.0/lib/controller.js:381:21)
    at async Controller.start (/zigbee2mqtt-1.17.0/lib/controller.js:167:9))

And database.db string related to [DIYRuZ_Geiger](https://www.zigbee2mqtt.io/devices/DIYRuZ_Geiger.html) is:

{"id":9,"type":"Router","ieeeAddr":"0x00124b001ec7977d","nwkAddr":18149,"manufId":0,"manufName":"modkam.ru","powerSource":"Mains (single phase)","modelId":"DIYRuZ_Geiger","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":12,"inClusterList":[0],"outClusterList":[1024,6],"clusters":{"genBasic":{"attributes":{"modelId":"DIYRuZ_Geiger","manufacturerName":"modkam.ru","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":4,"hwVersion":1,"dateCode":"19/09/2020 13:46","swBuildId":2}}},"binds":[{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00124b001940c183","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001940c183","endpointID":1}],"configuredReportings":[{"cluster":1024,"attrId":61441,"minRepIntval":0,"maxRepIntval":60,"repChange":0},{"cluster":1024,"attrId":61442,"minRepIntval":0,"maxRepIntval":60,"repChange":0}],"meta":{}}},"appVersion":2,"stackVersion":4,"hwVersion":1,"dateCode":"19/09/2020 13:46","swBuildId":2,"zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1610248335876}

After unregistering this device from network Devices tab of Zigbee2mqtt add-on starts working again.
When DIYRuZ_Geiger is inside network everything (frontend, network) works fine except Devices tab. And it's shown on Map.
I'm not sure if this issue is related to frontend or Zigbee2mqtt itself.

<img width="745" alt="2021-01-10_063940" src="https://user-images.githubusercontent.com/51086768/104113872-237de480-530f-11eb-9690-4f2f1fbe1625.png">

**Comment by schamu** [comment]
A few minutes ago has Konkk fixed  this issue:

Koenkk commented 33 minutes ago
Fixed!
Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Koenkk** [comment]
Does anyone still have issues with this on the latest dev branch?

**Comment by Morphy99** [comment]
All good here thanks!

**Comment by sunfos2019** [comment]
I wait for stable.

**Comment by florianschroen** [comment]
For me it is fixed. Thanks!

docker image: koenkk/zigbee2mqtt:latest-dev
zigbee2mqtt version: 1.17.0-dev commit: bdc261f
frontend version: 0.3.4

**Comment by Koenkk** [comment]
Looks like dev fixes it, let's close this then.

**Comment by lumenghz** [comment]
@Koenkk I meet same issue...

I start up `zigbee2mqtt` and `mqtt` using docker

### part of my `docker-compose.yml`

```yaml
version: '3.9'
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    volumes:
      - /run/udev:/run/udev:ro
      - "./data/zigbee2mqtt:/app/data"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8080
    depends_on:
      - mosquitto
  
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./data/mosquitto/config:/mosquitto/config"
      - "./data/mosquitto/log:/mosquitto/log"
```

### zigbee2mqtt configuration.yaml

```yaml
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.6:1883'

# Serial settings
serial:
  port: /dev/ttyACM0

frontend:
  port: 8080

experimental:
  new_api: true
```

### zigbee2mqtt log

```log
info  2021-12-09 22:23:18: Logging to console and directory: '/app/data/log/2021-12-09.22-23-16' filename: log.txt
info  2021-12-09 22:23:18: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229)
info  2021-12-09 22:23:18: Starting zigbee-herdsman (0.13.176)
info  2021-12-09 22:23:19: zigbee-herdsman started (resumed)
info  2021-12-09 22:23:19: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210319,"transportrev":2},"type":"zStack3x0"}'
info  2021-12-09 22:23:19: Currently 0 devices are joined:
warn  2021-12-09 22:23:19: `permit_join` set to  `true` in configuration.yaml.
warn  2021-12-09 22:23:19: Allowing new devices to join.
warn  2021-12-09 22:23:19: Set `permit_join` to `false` once you joined all devices.
info  2021-12-09 22:23:19: Zigbee: allowing new devices to join.
info  2021-12-09 22:23:19: Connecting to MQTT server at mqtt://192.168.1.6:1883
info  2021-12-09 22:23:19: Connected to MQTT server
info  2021-12-09 22:23:19: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
warn  2021-12-09 22:23:19: Using experimental new availability feature
info  2021-12-09 22:23:19: Started frontend on port 0.0.0.0:8080
info  2021-12-09 22:23:19: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"c2b5229","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210319,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b00234c70d8","panID":6754},"permit_join":true,"version":"1.22.1"}'
```

seems `Zigbee2MQTT:info 2021-01-09 19:47:39: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload` didn't appear ❓ 

### Fronted network screenshot

![image](https://user-images.githubusercontent.com/3817355/145413257-67249a7e-e7ef-4231-843e-33315476f3fb.png)

### Fronted About

![image](https://user-images.githubusercontent.com/3817355/145413501-2c76ee95-6264-4cfb-bb4d-684c253f8e2e.png)

**Comment by nurikk** [comment]
> @Koenkk I meet same issue...
> 
> I start up `zigbee2mqtt` and `mqtt` using docker
> 
> ### part of my `docker-compose.yml`
> ```yaml
> version: '3.9'
> services:
>   zigbee2mqtt:
>     image: koenkk/zigbee2mqtt:latest
>     container_name: zigbee2mqtt
>     devices:
>       - /dev/ttyUSB0:/dev/ttyACM0
>     volumes:
>       - /run/udev:/run/udev:ro
>       - "./data/zigbee2mqtt:/app/data"
>     environment:
>       - TZ=Asia/Shanghai
>     ports:
>       - 8888:8080
>     depends_on:
>       - mosquitto
>   
>   mosquitto:
>     image: eclipse-mosquitto:latest
>     container_name: mosquitto
>     ports:
>       - 1883:1883
>       - 9001:9001
>     volumes:
>       - "./data/mosquitto/config:/mosquitto/config"
>       - "./data/mosquitto/log:/mosquitto/log"
> ```
> 
> ### zigbee2mqtt configuration.yaml
> ```yaml
> # Home Assistant integration (MQTT discovery)
> homeassistant: false
> 
> # allow new devices to join
> permit_join: true
> 
> # MQTT settings
> mqtt:
>   base_topic: zigbee2mqtt
>   server: 'mqtt://192.168.1.6:1883'
> 
> # Serial settings
> serial:
>   port: /dev/ttyACM0
> 
> frontend:
>   port: 8080
> 
> experimental:
>   new_api: true
> ```
> 
> ### zigbee2mqtt log
> ```
> info  2021-12-09 22:23:18: Logging to console and directory: '/app/data/log/2021-12-09.22-23-16' filename: log.txt
> info  2021-12-09 22:23:18: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229)
> info  2021-12-09 22:23:18: Starting zigbee-herdsman (0.13.176)
> info  2021-12-09 22:23:19: zigbee-herdsman started (resumed)
> info  2021-12-09 22:23:19: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210319,"transportrev":2},"type":"zStack3x0"}'
> info  2021-12-09 22:23:19: Currently 0 devices are joined:
> warn  2021-12-09 22:23:19: `permit_join` set to  `true` in configuration.yaml.
> warn  2021-12-09 22:23:19: Allowing new devices to join.
> warn  2021-12-09 22:23:19: Set `permit_join` to `false` once you joined all devices.
> info  2021-12-09 22:23:19: Zigbee: allowing new devices to join.
> info  2021-12-09 22:23:19: Connecting to MQTT server at mqtt://192.168.1.6:1883
> info  2021-12-09 22:23:19: Connected to MQTT server
> info  2021-12-09 22:23:19: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
> warn  2021-12-09 22:23:19: Using experimental new availability feature
> info  2021-12-09 22:23:19: Started frontend on port 0.0.0.0:8080
> info  2021-12-09 22:23:19: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"c2b5229","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210319,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b00234c70d8","panID":6754},"permit_join":true,"version":"1.22.1"}'
> ```
> 
> seems `Zigbee2MQTT:info 2021-01-09 19:47:39: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload` didn't appear ❓
> 
> ### Fronted network screenshot
> ![image](https://user-images.githubusercontent.com/3817355/145413257-67249a7e-e7ef-4231-843e-33315476f3fb.png)
> 
> ### Fronted About
> ![image](https://user-images.githubusercontent.com/3817355/145413501-2c76ee95-6264-4cfb-bb4d-684c253f8e2e.png)

it's misleading loading message, start adding devices and you'll see the data

**Comment by lumenghz** [comment]
> > @Koenkk I meet same issue...
> > I start up `zigbee2mqtt` and `mqtt` using docker
> > ### part of my `docker-compose.yml`
> > ```yaml
> > version: '3.9'
> > services:
> >   zigbee2mqtt:
> >     image: koenkk/zigbee2mqtt:latest
> >     container_name: zigbee2mqtt
> >     devices:
> >       - /dev/ttyUSB0:/dev/ttyACM0
> >     volumes:
> >       - /run/udev:/run/udev:ro
> >       - "./data/zigbee2mqtt:/app/data"
> >     environment:
> >       - TZ=Asia/Shanghai
> >     ports:
> >       - 8888:8080
> >     depends_on:
> >       - mosquitto
> >   
> >   mosquitto:
> >     image: eclipse-mosquitto:latest
> >     container_name: mosquitto
> >     ports:
> >       - 1883:1883
> >       - 9001:9001
> >     volumes:
> >       - "./data/mosquitto/config:/mosquitto/config"
> >       - "./data/mosquitto/log:/mosquitto/log"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### zigbee2mqtt configuration.yaml
> > ```yaml
> > # Home Assistant integration (MQTT discovery)
> > homeassistant: false
> > 
> > # allow new devices to join
> > permit_join: true
> > 
> > # MQTT settings
> > mqtt:
> >   base_topic: zigbee2mqtt
> >   server: 'mqtt://192.168.1.6:1883'
> > 
> > # Serial settings
> > serial:
> >   port: /dev/ttyACM0
> > 
> > frontend:
> >   port: 8080
> > 
> > experimental:
> >   new_api: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### zigbee2mqtt log
> > ```
> > info  2021-12-09 22:23:18: Logging to console and directory: '/app/data/log/2021-12-09.22-23-16' filename: log.txt
> > info  2021-12-09 22:23:18: Starting Zigbee2MQTT version 1.22.1 (commit #c2b5229)
> > info  2021-12-09 22:23:18: Starting zigbee-herdsman (0.13.176)
> > info  2021-12-09 22:23:19: zigbee-herdsman started (resumed)
> > info  2021-12-09 22:23:19: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210319,"transportrev":2},"type":"zStack3x0"}'
> > info  2021-12-09 22:23:19: Currently 0 devices are joined:
> > warn  2021-12-09 22:23:19: `permit_join` set to  `true` in configuration.yaml.
> > warn  2021-12-09 22:23:19: Allowing new devices to join.
> > warn  2021-12-09 22:23:19: Set `permit_join` to `false` once you joined all devices.
> > info  2021-12-09 22:23:19: Zigbee: allowing new devices to join.
> > info  2021-12-09 22:23:19: Connecting to MQTT server at mqtt://192.168.1.6:1883
> > info  2021-12-09 22:23:19: Connected to MQTT server
> > info  2021-12-09 22:23:19: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
> > warn  2021-12-09 22:23:19: Using experimental new availability feature
> > info  2021-12-09 22:23:19: Started frontend on port 0.0.0.0:8080
> > info  2021-12-09 22:23:19: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"c2b5229","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210319,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b00234c70d8","panID":6754},"permit_join":true,"version":"1.22.1"}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > seems `Zigbee2MQTT:info 2021-01-09 19:47:39: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload` didn't appear ❓
> > ### Fronted network screenshot
> > ![image](https://user-images.githubusercontent.com/3817355/145413257-67249a7e-e7ef-4231-843e-33315476f3fb.png)
> > ### Fronted About
> > ![image](https://user-images.githubusercontent.com/3817355/145413501-2c76ee95-6264-4cfb-bb4d-684c253f8e2e.png)
> 
> it's misleading loading message, start adding devices and you'll see the data

thanks for your quick response 😸 , I'll try it..,

**Comment by lumenghz** [comment]
@nurikk It becomes normal after I pair a device 😸 , maybe it's an enhancement point for that misleading message if no devices paired? And thanks for your help !

**Comment by nurikk** [comment]
> @nurikk It becomes normal after I pair a device 😸 , maybe it's an enhancement point for that misleading message if no devices paired? And thanks for your help !

Issue already addressed in dev branch and will be released in next year release

**Comment by ttjorvi** [comment]
I love a challenge but might be better to highlight this for new installations (or maybe I just did not see it). Been trying to fix my controller for a while now that was working fine.
