### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by makeitready** [nurikk/z2m-frontend#204]
Hey Guys, i build up my Zigbee2Mqtt Bridge with the Webside https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html

But now i am getting Errors if i want to run /opt/zigbee2mqtt/ npm start :
![npm7](https://user-images.githubusercontent.com/66097784/103180174-927d2700-4893-11eb-9b06-6db76d0db4a0.JPG)

The Log file shows this: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.16.2~prestart: zigbee2mqtt@1.16.2
6 info lifecycle zigbee2mqtt@1.16.2~start: zigbee2mqtt@1.16.2
7 verbose lifecycle zigbee2mqtt@1.16.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.16.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.16.2~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.16.2~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.16.2~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.16.2~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.16.2 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid zigbee2mqtt@1.16.2
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 4.19.97-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.16.2 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.16.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Can you please help me out? I am quite new and would like to see my bridge running...
Note: I set zigbee2mqtt to "running as a daemon" like in Step 5 of the Webside showen above.

Thanks!

**Comment by sjorge** [comment]
This is not related to the frontend, but should be reported at koenkk/zigbee2mqtt repo instead.

**Comment by makeitready** [comment]
> This is not related to the frontend, but should be reported at koenkk/zigbee2mqtt repo instead.
> 
> But the error is logical, as you start zigbee2mqtt as a service (`systemctl start zigbee2mqtt`), you cannot start it a 2nd time with `npm start`.
> 
> You can look at the logs using systemctl status zigbee2mqtt or journalctl.
> 
> Alternatively stop the zigbee2mqtt service before running npm start on the command prompt.

Thanks for your Answer. 

Well, i don't know why, but if i want to run npm start, i am getting the Error Reportet Above, and if i want to stop the Service with "systemctl stop zigbee2mqtt", i am only getting back "unknown maschine command"
![npm8](https://user-images.githubusercontent.com/66097784/103319220-4962d980-4a31-11eb-9ed7-76403c9692b0.JPG)


One line in the log file was red and repeating: 
 nmbd[403]:   become_local_master_browser: Error - cannot find server ZIGBEE2MQTT-BRIDGE-RPI3 in workgroup WORKGROUP on subnet 192.168.178.132

I dont know what this means and i wonder because the IP Adress is the one from the Raspberry 3.
Can you please help me out?

Thanks!

**Comment by makeitready** [comment]
Nobody any idea? ://
