### ISSUE TITLE
group page

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#207]
Ccurrently all groups are displayed on 1 page.
If you have many groups with many devices it is hard to find the group.

I'm thinking of a more friendly navigation
- Or a table list with the groups and then modals to change/view
- Or a sidebar navigation menu with the added groups

**Comment by nurikk** [comment]
I don't think current groups view needs any cosmetically changes, maybe @Hacker-CB has other opinion?

**Comment by Hacker-CB** [comment]
@timoline in which device are you using frontend? I mean on PC or on mobile phone?
I think current implementation for groups on PC is ok, may be just add option for sorting on the column click.
For the mobile - all parts, not only groups should to be chnaged for more comfort.

**Comment by timoline** [comment]
On a pc 
But let's think a little bigger.
(I give my example with some imaginary numbers)

How do you think it will work and layout looklike  with 500 devices and  30 to 50 groups...
;-)

**Comment by Hacker-CB** [comment]
> How do you think it will work and layout looklike with 500 devices and 30 to 50 groups...
I can't imagine zigbee network with 500 devices.
I had 140+ devices before and I have to split them to two networks to get stability on the zigbee layer.

**Comment by timoline** [comment]
It was just imaginary...
https://user-images.githubusercontent.com/4232995/95500677-d3aa1d00-09af-11eb-92c8-88e56573933d.png

I just saw your screenshot and I thought, this can be improved

**Comment by nurikk** [comment]
> It was just imaginary...
> https://user-images.githubusercontent.com/4232995/95500677-d3aa1d00-09af-11eb-92c8-88e56573933d.png
> 
> I just saw your screenshot and I thought, this can be improved

How ?

**Comment by timoline** [comment]
See my first post.

I'm thinking of a more friendly navigation

Or a table list with the groups and then modals to change/view
Or a sidebar navigation menu with the added groups

**Comment by timoline** [comment]
I know, I ask to much ....
But how you created the settings page, that is exactly how I think the group page should looklike ;-)
created groups in a menu on the left and editing the group on the right

**Comment by timoline** [comment]
it took a while you finally considered :-) lol

https://github.com/nurikk/zigbee2mqtt-frontend/commit/82ac7abeb874e35d3d77be56cbacb9243011d9a3
