### ISSUE TITLE
TypeError t.devices is undefined

### ISSUE THREAD

**Issue by jonnycastaway** [nurikk/z2m-frontend#2083]
### What happened?

Hi,
after updating to last dev branch my Device-List is empty. But z2m is runnning in the Background fine.

Here is the Errormessage:

Hello, you've found a bug. Congratulations!

Calm down
[Click here, and save this file](http://192.168.99.252:8080/#)
[Raise a github issue](https://github.com/nurikk/zigbee2mqtt-frontend/issues/new?template=bug_report.yaml&stacktracke=**Current+url**%3A+http%3A%2F%2F192.168.99.252%3A8080%2F%23%2F%0A**Previous+url**%3A+%0A%0A%0A**Error+type**%3A+TypeError%0A**Error+message**%3A+t.devices+is+undefined%0A%0A%0A%0AR6e%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A62%3A9910%0A%24%2F_%2F%3C%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-bd8c0c65.js%3A1%3A3785%0A_%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-bd8c0c65.js%3A1%3A3705%0A%24%2Fp%3C%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-bd8c0c65.js%3A1%3A3970%0AE5%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A41%3A23910%0Ape.useMemo%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A9%3A6208%0A%24%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-bd8c0c65.js%3A1%3A3958%0AbT%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A41%3A19531%0Atb%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A43%3A3143%0Ar3%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A43%3A44781%0Ae3%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A43%3A39758%0AITe%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A43%3A39684%0Aap%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A43%3A39534%0Acb%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A43%3A35900%0AY5%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A43%3A34849%0Aw%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A28%3A1555%0AQ%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A28%3A1914%0A%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A18%3A12066%0AFk%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A18%3A11806%0AXM%40http%3A%2F%2F192.168.99.252%3A8080%2Fassets%2Findex-e3646692.js%3A18%3A11870%0A), attach previously downloaded file
Take a screenshot of this page and attach to the issue
In the github issue write detailed description for the issue, how this happened? Steps to reproduce

TypeError
t.devices is undefined

R6e@http://192.168.99.252:8080/assets/index-e3646692.js:62:9910
$/_/<@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3785
_@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3705
$/p<@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3970
E5@http://192.168.99.252:8080/assets/index-e3646692.js:41:23910
pe.useMemo@http://192.168.99.252:8080/assets/index-e3646692.js:9:6208
$@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3958
bT@http://192.168.99.252:8080/assets/index-e3646692.js:41:19531
tb@http://192.168.99.252:8080/assets/index-e3646692.js:43:3143
r3@http://192.168.99.252:8080/assets/index-e3646692.js:43:44781
e3@http://192.168.99.252:8080/assets/index-e3646692.js:43:39758
ITe@http://192.168.99.252:8080/assets/index-e3646692.js:43:39684
ap@http://192.168.99.252:8080/assets/index-e3646692.js:43:39534
cb@http://192.168.99.252:8080/assets/index-e3646692.js:43:35900
Y5@http://192.168.99.252:8080/assets/index-e3646692.js:43:34849
w@http://192.168.99.252:8080/assets/index-e3646692.js:28:1555
Q@http://192.168.99.252:8080/assets/index-e3646692.js:28:1914
@http://192.168.99.252:8080/assets/index-e3646692.js:18:12066
Fk@http://192.168.99.252:8080/assets/index-e3646692.js:18:11806
XM@http://192.168.99.252:8080/assets/index-e3646692.js:18:11870

Also Dashboard and Groups are empty in Frontend.

### What browsers are you seeing the problem on?

Firefox

### Relevant stacktrace

```shell
**Current url**: http://192.168.99.252:8080/#/
**Previous url**: 


**Error type**: TypeError
**Error message**: t.devices is undefined



R6e@http://192.168.99.252:8080/assets/index-e3646692.js:62:9910
$/_/<@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3785
_@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3705
$/p<@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3970
useMemo@http://192.168.99.252:8080/assets/index-e3646692.js:41:25860
pe.useMemo@http://192.168.99.252:8080/assets/index-e3646692.js:9:6208
$@http://192.168.99.252:8080/assets/index-bd8c0c65.js:1:3958
bT@http://192.168.99.252:8080/assets/index-e3646692.js:41:19531
r3@http://192.168.99.252:8080/assets/index-e3646692.js:43:44006
e3@http://192.168.99.252:8080/assets/index-e3646692.js:43:39758
ITe@http://192.168.99.252:8080/assets/index-e3646692.js:43:39684
ap@http://192.168.99.252:8080/assets/index-e3646692.js:43:39534
cb@http://192.168.99.252:8080/assets/index-e3646692.js:43:35900
CD@http://192.168.99.252:8080/assets/index-e3646692.js:43:36704
Gn@http://192.168.99.252:8080/assets/index-e3646692.js:41:3283
Wt/<@http://192.168.99.252:8080/assets/index-e3646692.js:43:34230
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by jonnycastaway** [comment]
Back on 1.39.0-dev commit: [f97ad2e9](https://github.com/Koenkk/zigbee2mqtt/commit/f97ad2e9) all is running fine.

**Comment by mrmaximas** [comment]
Same problem
Show only fresh generated map and logs, nothing else 

![Screenshot 2024-07-25 at 11 28 13](https://github.com/user-attachments/assets/2e065146-8740-4923-a18d-a8f0bab088af)

**Comment by mrmaximas** [comment]
TypeError
undefined is not an object (evaluating 't.devices[e.ieee_address]')
R6e@http://192.168.88.10:8888/assets/index-e3646692.js:62:9964
@http://192.168.88.10:8888/assets/index-bd8c0c65.js:1:3786
map@[native code]
useMemo@http://192.168.88.10:8888/assets/index-e3646692.js:41:25861
$@http://192.168.88.10:8888/assets/index-bd8c0c65.js:1:3965
bT@http://192.168.88.10:8888/assets/index-e3646692.js:41:19532
r3@http://192.168.88.10:8888/assets/index-e3646692.js:43:44008
e3@http://192.168.88.10:8888/assets/index-e3646692.js:43:39758
ITe@http://192.168.88.10:8888/assets/index-e3646692.js:43:39684
ap@http://192.168.88.10:8888/assets/index-e3646692.js:43:39537
cb@http://192.168.88.10:8888/assets/index-e3646692.js:43:35902
CD@http://192.168.88.10:8888/assets/index-e3646692.js:43:36706
Gn@http://192.168.88.10:8888/assets/index-e3646692.js:41:3284
@http://192.168.88.10:8888/assets/index-e3646692.js:43:34232

**Comment by mrmaximas** [comment]
I tried rolling back to the main branch, it didn't help.

**Comment by jonnycastaway** [comment]
> I tried rolling back to the main branch, it didn't help.

Uh, not good.
I installed a Backup from my VM.
I never tried a "roll-back" on the live system.

**Comment by mrmaximas** [comment]
> > I tried rolling back to the main branch, it didn't help.
> 
> Uh, not good. I installed a Backup from my VM. I never tried a "roll-back" on the live system.

Finally i restoring everything from yesterday's time mashine backup.
