### ISSUE TITLE
Model link error.

### ISSUE THREAD

**Issue by SargonofAssyria** [nurikk/z2m-frontend#209]
zigbee2mqtt version 1.16.2-dev commit: 0c6406e
coordinator type zStack3x0
coordinator revision 20201113
frontend version 0.2.123

With the latest update of z2m a few devices lost there link to the device 'home' page because model changed.
Devices affected: SEA801-Zigbee/SEA802-Zigbee, WXKG02LM_rev1 and WXKG02LM_rev2

**Comment by nurikk** [comment]
This happened after this change
https://github.com/Koenkk/zigbee-herdsman-converters/commit/e27837e07ba2003190d09295f0f8e98acdeab7b8#diff-5520dd49755e0a353d3857b8963a91cb4b8d87a01b6b8eb7bb6cce1c180eac83

perhaps we need to redeploy https://www.zigbee2mqtt.io/ website

@Koenkk

**Comment by Koenkk** [comment]
Will be fixed with new z2m release (1 january).
