### ISSUE TITLE
Prioritize exposes tab order?

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#210]
Currently the tab order is:
`About, Bind, Reporting, State, Exposes, Clusters`

Maybe something like:
`About, Exposes, Bind, Reporting, State, Clusters`

About and Exposes are probably the ones used the most, Bind and Reporting are used to configure the device, so it makes sense to have these next.

State and Cluster are useful to explore mostly new devices, most information in State should be in the Exposes tab anyway. The cluster view comes in handy when figuring out what a new device does, but offers little value for day-to-day use, so having that at the end makes more sense to me.

**Comment by nurikk** [comment]
Can you implement this? @timoline

**Comment by timoline** [comment]
Exposes  About, Bind, Reporting, State, Clusters,

also fine?
I also think exposes will be the one most used

**Comment by sjorge** [comment]
I'd shift about to behind Reporting then, as then we have 3 tabs that can change the device and 3 with information
