### ISSUE TITLE
[Bug]: "Localise device images" breaks frontend

### ISSUE THREAD

**Issue by ov1d1u** [nurikk/z2m-frontend#2100]
### What happened?

I pressed on the "Localise device image" button out of curiosity. After that, none of my devices appear on the "Devices" tab:
<img width="1039" alt="Screenshot 2024-08-13 at 17 45 00" src="https://github.com/user-attachments/assets/be6b8b46-e1c5-4e92-b615-66e4de9fd19e">

and the Setting page is broken, too:

<img width="1002" alt="Screenshot 2024-08-13 at 17 44 13" src="https://github.com/user-attachments/assets/014b5801-5aff-46b5-83fe-3741bae96e53">

The table doesn't seems to be populated at all:
<img width="779" alt="Screenshot 2024-08-13 at 17 45 58" src="https://github.com/user-attachments/assets/9781ae47-4e99-4270-b440-f22a630c36a4">

Restoring the devices.yaml file from a backup fixed the issue. I'm attaching both the previous and after pressing the button versions of the devices.yaml file.

[devices-before.yaml.txt](https://github.com/user-attachments/files/16601265/devices-before.yaml.txt)
[devices-after.yaml.txt](https://github.com/user-attachments/files/16601266/devices-after.yaml.txt)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant stacktrace

```shell
Result of pressing the button:

Coordinator
living_sofa done
tradfri_remote init
zigbee_repeater init
cube_ovidiu init
cube_oana done
balcony_door init
hallway init
living_switch init
balcony init
bedroom init
bathroom init
leaksensor_kitchen init
kitchen init
balcony_sensor init
bathroom_window done
bedroom_powerstrip init
litter_sensor init
living_lamp_1 init
leaksensor_bathroom done
temperature_sensor_unused init
wiswitch_oana init
wiswitch_ovidiu init
rangehood_temp init
entrance_door_sensor done
danalock init
zigbee_repeater_2 done
kitchen_led_switch init
dorm_balcony_window_side done
0xa4c138f0a38bbacd init
water_fountain_general init
gas_sensor init
fluffy_heated_bed_button done
desk_lamp_switch init
bathroom_thermostat init
lightbar_bedroom init
bathroom_spray_button done
living_lamp_2 init
dorm_lamp init
kitchen_temp init
living_systems_cabinet init
living_smoke_alarm init
hallway_light_sensor init
dorm_smoke_alarm init
living_curtain_motor_left init
living_curtain_motor_right init
living_curtains_button done
fluffy_light error
bedroom_curtain_motor_left init
bedroom_curtain_motor_right init
bedroom_curtains_button init
bedroom_tv_speakers init
water_fountain_motion_sensor init
desk_plug init
living_light_sensor init
bedroom_door done
power_meter init
dorm_balcony_door done
dorm_balcony_window_top done
bathroom_motion_sensor init
water_dispenser init
bathroom_triswitch init
dorm_lamp_secondary init
bedroom_led_strip init
0xa4c1380b84e05152 init
plant_watering_system init
bathroom_door done
portable_lamp init
dorm_balcony init
goodbye_button init
kitchen_island_led init
headphones_lights init
litter done
fluffy_heated_bed init
leaksensor_centrala done
z_rain_sensor error
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by firstchair** [comment]
I encountered the same issue

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee2mqtt/pull/25299!

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
