### ISSUE TITLE
inconsistant cluster naming ?

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#214]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/379665/103318414-af019680-4a2e-11eb-8bed-0ad3042a1579.png">

@Koenkk I think these are pulled from z2m... actually maybe herdsmen?

Can we get them consistent somehow? Some are genXxx others are just Xxx (e.g. PowerCfg vs genBasic)

**Comment by sjorge** [comment]
Looks like it is pulled from https://github.com/nurikk/z2m-frontend/blob/978ee1f5ccac506e2a1bbd050ee4e280c30f5f83/src/components/cluster-picker/index.tsx#L7

Maybe we should just not map them?

**Comment by nurikk** [comment]
Man, don't be so fussy, it's just a label 😁

**Comment by sjorge** [comment]
Closing as it seems this is a highly personal for problem, 4 people I asked opinions about call me a dick for being so nit picky.
I tried to manually expand the clusterDescriptions but I couldn't get them to show up.

Closing.
