### ISSUE TITLE
Can’t remove reporting config

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#215]
Looks like we cannot currently remove configured reporting.

https://github.com/Koenkk/zigbee-herdsman/commit/b9de573de8b34a8ed20782435b6cefbda2f57b1f

Seems to indicate it is possible though.

**Comment by nurikk** [comment]
Can, pass maxRepIntval equal to 65535

**Comment by sjorge** [comment]
That seems to work, not super intuitive though.
