### ISSUE TITLE
binding interface sometimes doesn't list all bindings?

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#222]
https://user-images.githubusercontent.com/379665/103342556-1436a580-4a8a-11eb-8a5f-f0958c15d8a2.mov

Found this bug a while ago, but it's hard to reproduce. Finally managed to capture it on video.

**Comment by nurikk** [comment]
I've watched it three times, don't get where is the issue

**Comment by sjorge** [comment]
It doesn't list both bindings at the beginning.

It only lists EP3, after removing it... it lists EP4.

Both were bound and working, and were in the database.db.

After removing EP3... EP4 showed up.

**Comment by nurikk** [comment]
Can you try to reproduce the big and then you get it, download state from settings tab and attach it here?

**Comment by nurikk** [comment]
And I need more detailed (step by step explain), currently I don't get you

**Comment by sjorge** [comment]
Will download dump the state next time it happens.

The device has 3 bindings:
- ep1 -> coordinator (genOnOff, saMetering)
- ep3 > ep2 (genOn

**Comment by sjorge** [comment]
Now am I doubting my self it is a bug and not just me imagine things. Closing until I have it again and can dump the state.

Only happens every few weeks.

**Comment by sjorge** [comment]
[state.json](https://github.com/nurikk/z2m-frontend/files/5757730/state.json.txt)

Found another one device 0x001fee000000594d, there are 3 bindings, but only 2 are shown in the ui.

**Comment by sjorge** [comment]
Looks like there is a newish commit that might fix this, let me check again.

**Comment by sjorge** [comment]
Yep that commit fixed it.
