### ISSUE TITLE
Feature: Add Update this device button

### ISSUE THREAD

**Issue by svrooij** [nurikk/z2m-frontend#230]
I didn't know this frontend existed until I found it in the docs. It looks awesome, I think I can retire my old dashboard, but there is one thing missing.

I would like an `Update this device` button for all devices where there is an OTA update waiting.

If you would consider such an option, I can help building it if you want.

**Comment by nurikk** [comment]
He man, it's already there
![Uploading Screenshot 2020-12-31 at 18.06.08.png…]()

**Comment by svrooij** [comment]
I found it, didn't wait long enough to show the Update button. I was expecting that it would just use the `"update_available": true` in the state. And not a separate api call that force checks the OTA status.

**Comment by nurikk** [comment]
> I found it, didn't wait long enough to show the Update button. I was expecting that it would just use the `"update_available": true` in the state. And not a separate api call that force checks the OTA status.

It does use update_avaliable

**Comment by svrooij** [comment]
Sorry I didn't see it correctly.
