### ISSUE TITLE
zigbee2mqtt not running

### ISSUE THREAD

**Issue by juergen4mueller** [nurikk/z2m-frontend#2324]
### What happened?

zigbee2mqtt dont load properly in chrome browser.
After resuming MACOS from suspend mode and reload the homeassistant website I got that error.

[initialState.json.zip](https://github.com/user-attachments/files/18221006/initialState.json.zip)
![z2m_Error](https://github.com/user-attachments/assets/e2ca4224-5097-4d14-8a13-ec684a5e7bf4)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/wiUUNgBalCsoHJ8IdnMZVXM_F2nq44TwcwB7JFT6pR0/#/
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: Error
**Error message**: Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/wiUUNgBalCsoHJ8IdnMZVXM_F2nq44TwcwB7JFT6pR0/assets/index-c733cdf7.css



Error: Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/wiUUNgBalCsoHJ8IdnMZVXM_F2nq44TwcwB7JFT6pR0/assets/index-c733cdf7.css
    at HTMLLinkElement.<anonymous> (http://homeassistant.local:8123/api/hassio_ingress/wiUUNgBalCsoHJ8IdnMZVXM_F2nq44TwcwB7JFT6pR0/assets/index-1213f99f.js:61:9232)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
Let's continue in https://github.com/nurikk/zigbee2mqtt-frontend/issues/2325
