### ISSUE TITLE
Lo, I've found a bug

### ISSUE THREAD

**Issue by TomsnCo** [nurikk/z2m-frontend#2332]
### What happened?

![Capture d’écran 2024-12-23 à 12 20 27](https://github.com/user-attachments/assets/574ab479-f5fe-408a-b39f-21b5939e1ee7)

[initialState.json.zip](https://github.com/user-attachments/files/18228803/initialState.json.zip)

### What browsers are you seeing the problem on?

Safari

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.180:8080/#/
**Previous url**: 


**Error type**: TypeError
**Error message**: Importing a module script failed.
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment]
Can you try in incognito mode?

**Comment by TomsnCo** [comment]
Good evening, I tried private mode, the problem was solved,
For information, I emptied the cache and history of my browser, everything returned to normal,
Thank you for your feedback and sorry for the inconvenience,
Happy Holidays

**Comment by TomsnCo** [comment]
Good evening, I tried private mode, the problem was solved,
For information, I emptied the cache and history of my browser, everything returned to normal,
Thank you for your feedback and sorry for the inconvenience,
Happy Holidays
