### ISSUE TITLE
[Bug]: Availability is active even when it is turned off

### ISSUE THREAD

**Issue by leroyloren** [nurikk/z2m-frontend#2339]
### What happened?

I am using the latest development branch (2.0.0) and I am not using availability, which is disabled by default, but the column is still displayed in the frontend.

![obrazek](https://github.com/user-attachments/assets/17282edd-dd10-452d-82c7-8634b8de05e0)

)![dhtt](https://github.com/user-attachments/assets/b598b44b-d886-4612-b556-1bca4e665b08)

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Nerivec** [comment]
Looks like a display issue.

@Koenkk seems the change from boolean/object to object with `enabled` needs to be propagated somewhere in frontend so it doesn't display the column when `enabled: false`? Might want to check ha/frontend for the same kind of issue since they had the same change.

**Comment by Koenkk** [comment]
Fixed in https://github.com/nurikk/zigbee2mqtt-frontend/issues/2339, thanks for reporting!

**Comment by leroyloren** [comment]
Yes, that's fine, one more thing I noticed is that the Availability function cannot be deactivated via the Frontend, the Enabled field requires a checked.

![obrazek](https://github.com/user-attachments/assets/2f275cab-ce39-465c-8a4f-2301dbdb2fb0)

**Comment by Koenkk** [comment]
Fixed!

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
