### ISSUE TITLE
[bug] filter dropdown on log page items change postion

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#234]
https://user-images.githubusercontent.com/379665/103443415-5c5af100-4c5f-11eb-8223-e975a52cb07d.mov

Looks like it dynamically gets build based on the content of the log window? As sometimes ERROR is also present and sometimes it isn't.

**Comment by nurikk** [comment]
It's okay, this dropdown is rendered from error levels available in the buffer.

**Comment by nurikk** [comment]
Re-implemented this dropdown
