### ISSUE TITLE
(BUG) SEA801-Zigbee/SEA802-Zigbee not all functions and no converters

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#235]
Hello, the SEA801-Zigbee thermostat is missing some functions in the front end and no converters are available anywhere.
No matter which update arrow I press, there is always a message that no converter is available.
Can you fix it?

THX!

![sshot-1](https://user-images.githubusercontent.com/32480002/103453813-1002c600-4cde-11eb-933b-098d184cdad5.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/103453814-1133f300-4cde-11eb-8025-58e7c336cb49.jpg)

**Comment by nurikk** [comment]
This is definitely not an frontend issue. More appropriate places to raise the issue is [z2m](https://github.com/Koenkk/zigbee2mqtt/issues/new) issue tracker

**Comment by Koenkk** [comment]
Not a frontend issue indeed.
