### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by gh1973** [nurikk/z2m-frontend#2350]
### What happened?

Paired a new smart zigbee device - updated the thing - and later when opening zigbee2mqtt in HA, this error showed up...
[initialState.json](https://github.com/user-attachments/files/18275166/initialState.json)
![capture_241230_145257](https://github.com/user-attachments/assets/c0434293-69d6-4a09-b9b8-0078c7ebec44)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://nlmq1pgeuerd2ix2lbb2pv5tpchevsgy.ui.nabu.casa/api/hassio_ingress/xq4YhkwPXvSnwN4ElkN64CRMRkPRMb-jFUIXwq2Cgxg/#/
**Previous url**: https://nlmq1pgeuerd2ix2lbb2pv5tpchevsgy.ui.nabu.casa/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Failed to fetch dynamically imported module: https://nlmq1pgeuerd2ix2lbb2pv5tpchevsgy.ui.nabu.casa/api/hassio_ingress/xq4YhkwPXvSnwN4ElkN64CRMRkPRMb-jFUIXwq2Cgxg/assets/index-a7046605.js



TypeError: Failed to fetch dynamically imported module: https://nlmq1pgeuerd2ix2lbb2pv5tpchevsgy.ui.nabu.casa/api/hassio_ingress/xq4YhkwPXvSnwN4ElkN64CRMRkPRMb-jFUIXwq2Cgxg/assets/index-a7046605.js
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
thanks, fixed
