### ISSUE TITLE
TS0601_thermostat functions not fully in frontend

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#243]
Hello, I have the TS0601_thermostat, some settings are missing in the front end, can you please do it?

https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html#tuya-ts0601_thermostat

![sshot-2](https://user-images.githubusercontent.com/32480002/103549846-4be98700-4ea8-11eb-92c6-6fc6b87dab97.jpg)
![sshot-1](https://user-images.githubusercontent.com/32480002/103549847-4d1ab400-4ea8-11eb-9a4a-400cf7ec44cf.jpg)

State:

> {
    "auto_lock": "MANUAL",
    "away_mode": "OFF",
    "away_preset_days": 1,
    "away_preset_temperature": 15,
    "battery_low": false,
    "boost_time": 300,
    "child_lock": "UNLOCKED",
    "comfort_temperature": 20,
    "current_heating_setpoint": 22,
    "eco_temperature": 15,
    "force": "normal",
    "holidays": [
        {
            "hour": 6,
            "minute": 0,
            "temperature": 20
        },
        {
            "hour": 8,
            "minute": 0,
            "temperature": 15
        },
        {
            "hour": 11,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 12,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 17,
            "minute": 30,
            "temperature": 20
        },
        {
            "hour": 22,
            "minute": 0,
            "temperature": 15
        }
    ],
    "last_seen": "2021-01-04T15:11:51.640Z",
    "linkquality": 105,
    "local_temperature": 21.5,
    "local_temperature_calibration": -1,
    "max_temperature": 35,
    "min_temperature": 5,
    "position": 0,
    "preset": "manual",
    "system_mode": "auto",
    "update": {
        "state": "idle"
    },
    "update_available": false,
    "week": "5+2",
    "window_detection": "OFF",
    "window_detection_params": {
        "minutes": 73,
        "temperature": 115
    },
    "workdays": [
        {
            "hour": 6,
            "minute": 0,
            "temperature": 20
        },
        {
            "hour": 8,
            "minute": 0,
            "temperature": 15
        },
        {
            "hour": 11,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 12,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 17,
            "minute": 30,
            "temperature": 20
        },
        {
            "hour": 22,
            "minute": 0,
            "temperature": 15
        }
    ]
}

State:
`{
    "auto_lock": "MANUAL",
    "away_mode": "OFF",
    "away_preset_days": 1,
    "away_preset_temperature": 15,
    "battery_low": false,
    "boost_time": 300,
    "child_lock": "UNLOCKED",
    "comfort_temperature": 20,
    "current_heating_setpoint": 22,
    "eco_temperature": 15,
    "force": "normal",
    "holidays": [
        {
            "hour": 6,
            "minute": 0,
            "temperature": 20
        },
        {
            "hour": 8,
            "minute": 0,
            "temperature": 15
        },
        {
            "hour": 11,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 12,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 17,
            "minute": 30,
            "temperature": 20
        },
        {
            "hour": 22,
            "minute": 0,
            "temperature": 15
        }
    ],
    "last_seen": "2021-01-04T15:11:51.640Z",
    "linkquality": 105,
    "local_temperature": 21.5,
    "local_temperature_calibration": -1,
    "max_temperature": 35,
    "min_temperature": 5,
    "position": 0,
    "preset": "manual",
    "system_mode": "auto",
    "update": {
        "state": "idle"
    },
    "update_available": false,
    "week": "5+2",
    "window_detection": "OFF",
    "window_detection_params": {
        "minutes": 73,
        "temperature": 115
    },
    "workdays": [
        {
            "hour": 6,
            "minute": 0,
            "temperature": 20
        },
        {
            "hour": 8,
            "minute": 0,
            "temperature": 15
        },
        {
            "hour": 11,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 12,
            "minute": 30,
            "temperature": 15
        },
        {
            "hour": 17,
            "minute": 30,
            "temperature": 20
        },
        {
            "hour": 22,
            "minute": 0,
            "temperature": 15
        }
    ]
}`

.db

`{"id":32,"type":"EndDevice","ieeeAddr":"0x5c0272fffe8ef81d","nwkAddr":15661,"manufId":4098,"manufName":"_TZE200_ckud7u2l","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_ckud7u2l","powerSource":3,"zclVersion":3,"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1609769483120}
`

**Comment by nurikk** [comment]
I can't fix this, frontend is rendered using exposes property from device converter
