### ISSUE TITLE
Frontend can`t load devices. Error - "Loading devices takes too long time"

### ISSUE THREAD

**Issue by Utyff** [nurikk/z2m-frontend#249]
Z2M version 1.17.
I remove all devices and cleanup Z2M config. Add 3 new devices successfully. After I add Geiger sensor frontend can`t load device list. All other works good. I can see Zigbee Map, Home Assistant works with devices. There are not any errors in log-file. Problem only with device list.
I cleanup config and add devices again. After add Geiger sensor I get the same problem.

![z2m-dev](https://user-images.githubusercontent.com/13304142/104136506-b4a09a00-53a7-11eb-8903-1c2c6e025fcc.JPG)
![z2m-console](https://user-images.githubusercontent.com/13304142/104136513-bec29880-53a7-11eb-9b09-818f90e14f4a.png)
![z2m-map-3](https://user-images.githubusercontent.com/13304142/104136524-d26dff00-53a7-11eb-8f06-859ce1ec7f07.JPG)

**Comment by Utyff** [comment]
If I remove Geiger sensor UI working normally.
Something wrong with Geiger converter.
I think this error is the reason.

> error 2021-01-11 00:25:34: Failed to call 'Bridge' 'onMQTTConnected' (Error: Cluster 'msIlluminanceMeasurement' has no attribute '61441'
    at Object.getAttribute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/utils.js:84:19)
    at _configuredReportings.map (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:87:36)
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:83:43)
    at devices.zigbee.getDevices.map (/opt/zigbee2mqtt/lib/extension/bridge.js:512:60)
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/opt/zigbee2mqtt/lib/extension/bridge.js:484:50)
    at Bridge.onMQTTConnected (/opt/zigbee2mqtt/lib/extension/bridge.js:47:20))

**Comment by nurikk** [comment]
Can you try to switch to the latest dev branch? If it doesn't help, consider raising issue in main z2m repository

**Comment by Utyff** [comment]
I have updated the Geiger firmware to version 1.0.7 and now the UI is working good.
But new firmware have bugs.
LED always ON and radiation values to high and grow. It should not grow.
You made new firmware from different branch. It made as absolutely new version?

![geiger](https://user-images.githubusercontent.com/13304142/104327506-ec205b00-54fb-11eb-8cea-8f01a5e82835.JPG)

**Comment by DJTerentjev** [comment]
I have same issue. Have Geiger as well, but it was working fine up to 20 devises, then stop loading.

**Comment by nurikk** [comment]
Any errors in browser console?

**Comment by DJTerentjev** [comment]
Only warnings (same two times):
The resource at “http://192.168.1.56:8123/frontend_latest/core.94ddb68d.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.

**Comment by nurikk** [comment]
Can you send me a state file from settings page?

**Comment by DJTerentjev** [comment]
One more thing maybe it is linked some how. Before I start experience this issue I had 22 devices, but I could see only 20. Same time all devices were showing on the map.

**Comment by DJTerentjev** [comment]
> ?

Sure. Please let me know where I can found it.

**Comment by nurikk** [comment]
> > ?
> 
> Sure. Please let me know where I can found it.

Go to Settings and there is big blue button "Download state"

**Comment by DJTerentjev** [comment]
Please see the link: [https://pastebin.com/7kWUvZ1H](url)

**Comment by nurikk** [comment]
> Please see the link: [https://pastebin.com/7kWUvZ1H](url)

First of all try to switch to dev branch, then check that you don't have any errors during startup time

**Comment by DJTerentjev** [comment]
With dev branch all works good! Than you!

**Comment by nurikk** [comment]
Closing then
