### ISSUE TITLE
Logs not showing on version 1.17.0

### ISSUE THREAD

**Issue by pedrolamas** [nurikk/z2m-frontend#255]
Since I upgraded my zigbee2mqtt docker container to the latest 1.17.0, the logs on the frontend stopped showing...

![image](https://user-images.githubusercontent.com/85504/104307229-de041780-54c6-11eb-8938-adc31de68cb6.png)

Looking at the network logs on Edge browser, I can see the websock is working as expected:

![image](https://user-images.githubusercontent.com/85504/104307311-f8d68c00-54c6-11eb-8fe1-854d2c1794e8.png)

Not sure what I can send to help with this, I am using an nginx reverse proxy but everything else works fine, and as I said I can see that the websock is also working fine!

**Comment by nurikk** [comment]
Do you have any errors in browser console?

**Comment by pedrolamas** [comment]
None. I did check that and forgot to mention on the original post, sorry...

**Comment by nurikk** [comment]
I've tried to reproduce on latest dev and edge browser, everything works fine for me.

**Comment by pedrolamas** [comment]
I'll check the dev container then, and report back in 5 mins!

**Comment by pedrolamas** [comment]
Got dev and didn't work at first, but I see now that behavior changed: I had the log level set to "warning", once I changed it in the frontend to "debug" the logs started to show again!

So I assume that the frontend now follows the same settings in order to show logs or not?

**Comment by nurikk** [comment]
> Got dev and didn't work at first, but I see now that behavior changed: I had the log level set to "warning", once I changed it in the frontend to "debug" the logs started to show again!
> 
> So I assume that the frontend now follows the same settings in order to show logs or not?

Dropdown on logs page is only for filtering, it doesn't change logging settings. In your case you didn't have any warning messages

**Comment by pedrolamas** [comment]
Correct, but I have always had the logging state set to "warn" and in previous versions the log page showed the log messages (warning or not).

Now seems it will conform with that setting, and I'm fine with that!
