### ISSUE TITLE
can't run frontend

### ISSUE THREAD

**Issue by mojijafari** [nurikk/z2m-frontend#264]
Dear nurikk,

thank you very my for your kind effort, I appreicate it. However, I configured the configuration.yaml based on zigbee2mqtt.io 
but the webUI is not working. I tried some other ports but can't run it. Do you have any idea what the problem is? is there any other configuration?

**Comment by nurikk** [comment]
Hello, it's really hard to help with this amount of information. Kindly attach z2m and browser console logs as well as your configuration.yaml, and mode how'd you run z2m (docker, hass addon, vanilla installation, etc)

**Comment by dlopc** [comment]
Hi.
I also have problems with the frontend UI. I got it working was unstable and could not get it running back. Port 8080 is in use, so I trying to use 8089. When I open IPADDRESS:8089 I GET
`{"real_path": "", "method": "GET", "path": "/", "protocol_version": "HTTP/1.0", "request_version": "HTTP/1.1", "query": ""}`
**Environment:**

- Orange PI PC
- Openmediavault
- Docker
- Homeassistant reinstalled  from scratch few days ago (docker)
- Zigbee2mqtt (docker) reinstalled many times, seems to work (stopping container and modifying configuration.yaml)
- configuration.yaml as follows (just one device, it seems I have to detect them each time I reinstall zigbee, previously I had 3)
`homeassistant: false
permit_join: true
mqtt:
  base_topic: home/zigbee2mqtt
  server: 'mqtt://IPADDRESS'
serial:
  port: /dev/ttyACM0
experimental:
  new_api: true
  frontend_port: 8089
devices:
  '0x00158d0002f2514b':
    friendly_name: 'Puerta01'
`
Thanks for any help or any url I could have a look at.

**Comment by ChankyTheConqueror** [comment]
Hi sorry for hijacking this thread, im also experiencing the same problem:
Im running z2m on docker on a Raspberry Pi Model B Plus Rev 1.2, my docker-compose looks as follows:
-----------------------------------------------------------------------------------
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    platform: linux/arm/v6
    volumes:
      - /home/pi/zigbee2mqtt_data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0
    restart: always
    ports:
      - "8080:8080"
    links:
      - "mqtt:broker"
    privileged: true
    environment:
      - TZ=Europe/Vienna
--------------------------------------------------------------------- 
I have added the tag below on my configuration.yaml:
-----------------------------------------------------------------------
frontend:
  port: 8080
----------------------------------------------------------------------
when i call <host>:8080 i cant reach the frontend.
How can i debug this? any help is high appreciated

Thanks in advance!

**Comment by ChankyTheConqueror** [comment]
works now with:
![image](https://user-images.githubusercontent.com/64441284/107847274-7c4b0c00-6dea-11eb-868c-540c5a3c0915.png)

**Comment by dirkclemens** [comment]
i also can't get the frontend to run.

my configuration.yaml
```
...
frontend:
  port: 8888
  # Optional, default 0.0.0.0
  host: 127.0.0.1
...
```

this does not work when leaving it empty or default 0.0.0.0 and zigbee2mqtt at all wont't even start when setting "host" to 192.168.2.222 (which is actually the machine it is running on)

I am running Nginx in parallel, is any configuration needed for that? Using Chrome and Safari.

and this is the log
```
Zigbee2MQTT:info  2021-02-13 12:16:03: Logging to console and directory: 'data/log' filename: log.txt
Zigbee2MQTT:info  2021-02-13 12:16:04: Starting Zigbee2MQTT version 1.17.1-dev (commit #a63b6c3)
Zigbee2MQTT:info  2021-02-13 12:16:04: Starting zigbee-herdsman (0.13.68)
Zigbee2MQTT:info  2021-02-13 12:16:06: zigbee-herdsman started
Zigbee2MQTT:info  2021-02-13 12:16:06: Coordinator firmware version: '{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20190425,"transportrev":2},"type":"zStack30x"}'
Zigbee2MQTT:info  2021-02-13 12:16:06: Currently 8 devices are joined:
...
Zigbee2MQTT:info  2021-02-13 12:16:06: ThermostatMultiraum (0x5c0272fffe7f7e1e): TS0601_thermostat - TuYa Radiator valve with thermostat (EndDevice)
...
Zigbee2MQTT:info  2021-02-13 12:16:06: Started frontend on port 127.0.0.1:8888
Zigbee2MQTT:info  2021-02-13 12:16:07: Connecting to MQTT server at mqtt://192.168.2.222:1883
Zigbee2MQTT:info  2021-02-13 12:16:07: Connected to MQTT server
```

Thanks for supporting me :-)

**Comment by nurikk** [comment]
> i also can't get the frontend to run.
> 
> my configuration.yaml (I am running homebridge on port :8080 in parallel on this maschine).
> 
> ```
> ...
> frontend:
>   port: 8888
>   # Optional, default 0.0.0.0
>   host: 127.0.0.1
> ...
> ```
> 
> this does not work when leaving it empty or default 0.0.0.0 and zigbee2mqtt at all wont't even start when setting "host" to 192.168.2.222 (which is actually the machine it is running on)
> 
> I am running Nginx in parallel, is any configuration needed for that? Using Chrome and Safari.
> 
> and this is the log
> 
> ```
> Zigbee2MQTT:info  2021-02-13 12:16:03: Logging to console and directory: 'data/log' filename: log.txt
> Zigbee2MQTT:info  2021-02-13 12:16:04: Starting Zigbee2MQTT version 1.17.1-dev (commit #a63b6c3)
> Zigbee2MQTT:info  2021-02-13 12:16:04: Starting zigbee-herdsman (0.13.68)
> Zigbee2MQTT:info  2021-02-13 12:16:06: zigbee-herdsman started
> Zigbee2MQTT:info  2021-02-13 12:16:06: Coordinator firmware version: '{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20190425,"transportrev":2},"type":"zStack30x"}'
> Zigbee2MQTT:info  2021-02-13 12:16:06: Currently 8 devices are joined:
> ...
> Zigbee2MQTT:info  2021-02-13 12:16:06: ThermostatMultiraum (0x5c0272fffe7f7e1e): TS0601_thermostat - TuYa Radiator valve with thermostat (EndDevice)
> ...
> Zigbee2MQTT:info  2021-02-13 12:16:06: Started frontend on port 127.0.0.1:8888
> Zigbee2MQTT:info  2021-02-13 12:16:07: Connecting to MQTT server at mqtt://192.168.2.222:1883
> Zigbee2MQTT:info  2021-02-13 12:16:07: Connected to MQTT server
> ...
> Zigbee2MQTT:info  2021-02-13 12:16:59: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"a63b6c3","coordinator":{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20190425,"transportrev":2},"type":"zStack30x"},"log_level":"info","network":{"channel":12,"extendedPanID":"0x00124b0018ed325d","panID":6754},"permit_join":true,"version":"1.17.1-dev"}'
> ```
> 
> Thanks for supporting me :-)
don't bind to 127.0.0.1 unless you're clearly know what are you doing, stick to default 0.0.0.0 and you're on safe side

**Comment by dirkclemens** [comment]
> don't bind to 127.0.0.1 unless you're clearly know what are you doing, stick to default 0.0.0.0 and you're on safe side

sure, I am trying all combinations but with host: 0.0.0.0 I still can't get it to work. referring to the logs, the frontend seems to be started in my (gui less) ubuntu server box, but I can't open it in the browser from my iMac

```
Zigbee2MQTT:info  2021-02-14 14:10:28: Started frontend on port 0.0.0.0:8888
Zigbee2MQTT:info  2021-02-14 14:10:28: Connecting to MQTT server at mqtt://192.168.2.222:1883
Zigbee2MQTT:info  2021-02-14 14:10:28: Connected to MQTT server
Zigbee2MQTT:info  2021-02-14 14:10:28: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
```

**Comment by dirkclemens** [comment]
Update: quite simple solution for the port issue: 

configuration.yaml 
```...
frontend:
  port: 1881
...```

remove old docker images and then run a new docker image simply with the port on the command line like
`docker run -itd -p 1881:1881 --name=zigbee2mqtt --restart=always   ...   koenkk/zigbee2mqtt:latest-dev`

**Comment by dlopc** [comment]
I had a try yesterday I got it working. Not clear if because of new version or because of changes on configuration.yaml, I only changed the yaml. As follows:

before:
```
frontend:
  port: 8089
```
now:
```
frontend:
  port: 8058
  host: 0.0.0.0
```
