### ISSUE TITLE
frontent behind traefik edge router

### ISSUE THREAD

**Issue by dakky** [nurikk/z2m-frontend#275]
I want to proxy requests to the zigbee2mqtt container through traefik.

Used labels:
```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`mydomain.com`) && Path(`/zigbee2mqtt`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=websecure"
      - "traefik.http.routers.zigbee2mqtt.tls=true"
      - "traefik.http.routers.zigbee2mqtt.middlewares=zigbee2mqtt-auth"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.zigbee2mqtt-auth.basicauth.users=XXX:XXX"
```

when accessing the endpoint I get an 404 with this html body:
```
Cannot GET /zigbee2mqtt
```

I'm quite sure, this message comes from z2m. Is there something I need to configure to tell the app, that my webcontext ist `zigbee2mqtt` instead of `/` ?

**Comment by nurikk** [comment]
I have no idea how to configure this proxy, kindly refer to the official example for Nginx

**Comment by dakky** [comment]
it's imho not a problem of the reverse proxy. The problem seems to be, that the frontend realizes, that I have a request to the following URL: `ip:8080/zigbee2mqtt` and therefore complains, that there is no endpoint responsible for that context with the method GET.
A possible solution would be, the configure the app and tell her, that the content should be delivered from the `/zigbee2mqtt`instead of `/`
Can this be done (ideally via environment variable ;) )?

**Comment by CSchlipp** [comment]
If you add an additional path in the routers rule that is not supported by the service, attach a StripPrefix middleware: https://doc.traefik.io/traefik/middlewares/stripprefix/

That way, externally you can use the hostname with a path, whereas rowards z2m the path is stripped out again.

**Comment by dakky** [comment]
hmm stripprefix does not work here: there seem to be some absolute paths included?
When stripping the path, the app tries to load some content from / , which of course does not exist.

![grafik](https://user-images.githubusercontent.com/579584/108607257-91620500-73bf-11eb-816f-273d415d006e.png)

**Comment by svrooij** [comment]
I use a wildcard domain for all my separate services. Then you don’t have to do anything to the path. So for zigbee2mqtt I use zigbee.myhome.mydomain.nl and for node red I use red.myhome.mydomain.nl

This app uses websockets quite a lot, not sure if you have to configure them separate in traifik

**Comment by gislis2** [comment]
It may or may not apply to you.
Was getting 404 and 502 errors, depending on the configurations I made
Took the risk and disabled UFW (Ubuntu) and it worked instantly. Enabled UFW and it broke.

Try accessing the website and check your firewall logs. 

Ubuntu 
> sudo dmesg | grep '\[UFW'

And then look for corresponding port

**Comment by abishur** [comment]
Did anyone ever figure this out?  I'm looking to use traefik to access my zigbee2mqtt docker, but it fails to pull up the page.

**Comment by svrooij** [comment]
Yes I figured it out, will send my config this afternoon.

**Comment by abishur** [comment]
> Yes I figured it out, will send my config this afternoon.

Hey @svrooij not to be a pest, but do you have that config I could reference 😃

**Comment by svrooij** [comment]
@abishur i miss red the issue. As I already stated I'm using a wildcard cert and a subdomain for each service, that you dons have the mess with the folders.

Anyway I found this on Google, there seems to be a way to remove the prefix when you setup you reverse proxy. https://iceburn.medium.com/reverse-proxy-in-traefik-with-subdirectories-eef4261939e

**Comment by abishur** [comment]
@svrooij I'm doing the same thing using wildcard cert and a subdomain for each service.  

I created a zigbee2mqtt entry point using https and for the service I have it point at my http://ip:8080

Shoot, okay as I was typing this out I saw my issue.  I was pointing the service to httpS://ip:8080.  Once I pointed the service at http://ip:8080 it instantly came up!

Thanks for getting me to look more closely at it 🤣

**Comment by nurikk** [comment]
How do you guys configure your router? Use this nginx as example: 
This example demonstrates how to configure nginx to proxy on subfolder `/z2m`


```
server {
     listen       80;

    location /z2m {
        proxy_pass http://192.168.4.200:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /z2m/api {
        proxy_pass http://192.168.4.200:8080/api;
        proxy_set_header Host $host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```
Then open your browsers on `http://whatever/z2m/` and everything should work (**slash in the end  of url is important for this example** )
