### ISSUE TITLE
Yo! let's do it together!

### ISSUE THREAD

**Issue by Kepro** [nurikk/z2m-frontend#277]
Hi @nurikk, I was working on my dashboard last year, but yesterday I found that zigbee2mqtt finally includes some kind of frontend!

what do you think if "merge it"? like dashboard is WIP dashboard is now showing just basic information

![image](https://user-images.githubusercontent.com/1714370/105575125-73c26100-5d69-11eb-881a-ae468a43e709.png)

I will try to do fork from your repo if you are not working on some kind of dashboard by yourself

I want to do something like https://dribbble.com/search/smart%20home%20widgets%20web

I'm using react / redux / bootstrap 4 / fontAwesome / typescript but repo is in private gitlab for now

**Comment by nurikk** [comment]
Hi @Kepr, this will be very nice to have a dashboard in the frontend. My current tech stack is slightly different from yours, but I think it's not a big problem. Feel free to fork this repo and submit your changes.

**Comment by Kepro** [comment]
it's very similar :) btw did you have any issues like this?
```
[1] ERROR in ./node_modules/@rjsf/bootstrap-4/dist/bootstrap-4.esm.js 15:0-52
[1] Module not found: Error: Can't resolve 'react-bootstrap/InputGroup' in '/Users/peter.kasarda/Projects/z2m-frontend/node_modules/@rjsf/bootstrap-4/dist'
[1]  @ ./src/components/settings/index.tsx 33:0-37 243:32-36
[1]  @ ./src/index.tsx 36:0-58 63:48-69
```

I solve it with help https://github.com/rjsf-team/react-jsonschema-form/issues/2027

when I install `react-bootstrap@1.0.1`

**Comment by nurikk** [comment]
This is a very strange error, try to npm ci or npm install

**Comment by Kepro** [comment]
solve the error with the latest node version... I was using node 12
