### ISSUE TITLE
Security thingy

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#28]
Because there is no security on the frontend, I think it's not handy to show the bridge info on the settings page [RAW tab]
For dev purpose I understand, but security wise not very handy because the broker credentials are there in plain text.

![image](https://user-images.githubusercontent.com/680252/94924959-c0361800-04be-11eb-99a5-ef6aceaa4ced.png)

**Comment by nurikk** [comment]
Kindly refer to nginx setup to password protect your admin panel.
https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/frontend.md#nginx-proxy-configuration

**Comment by nurikk** [comment]
Removed mqtt password topic
