### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#280]
version 0.3.17

When I open exposes from this device
![image](https://user-images.githubusercontent.com/680252/105811389-dce5e680-5fac-11eb-830e-41d812b75f7b.png)

i get

![image](https://user-images.githubusercontent.com/680252/105811314-baec6400-5fac-11eb-8a32-70feffa982f2.png)

**Comment by nurikk** [comment]
Can you attach the state file?

**Comment by timoline** [comment]
[state.txt](https://github.com/nurikk/z2m-frontend/files/5871732/state.txt)

**Comment by timoline** [comment]
also this device
![image](https://user-images.githubusercontent.com/680252/105812102-e0c63880-5fad-11eb-88f4-f0fa0cbdb9dd.png)

**Comment by nurikk** [comment]
Thanks, fixed in latest dev
