### ISSUE TITLE
Map question

### ISSUE THREAD

**Issue by nanobra1n** [nurikk/z2m-frontend#285]
My map shows almost no links if only IsParent & IsAChild are checked:
![Zigbee2mqtt_-_Home_Assistant1](https://user-images.githubusercontent.com/15968173/106535243-cc110580-64c3-11eb-947a-bec009bf4d06.png)
They do show up when IsASibling is checked as well: 
![Zigbee2mqtt_-_Home_Assistant2](https://user-images.githubusercontent.com/15968173/106535284-e77c1080-64c3-11eb-9eaa-ca9223ce0c2e.png)
However certain devices will never show a connection (even if NoneOfTheAbove is checked):
![Zigbee2mqtt_-_Home_Assistant3](https://user-images.githubusercontent.com/15968173/106535431-36c24100-64c4-11eb-8235-ca9a17b1037d.png)
All devices that don't show a connection however work fine and publish lqi. 
Is this expected? What determines a device to be a child or parent? I would assume that the first case would show more connections between coordinator and other devices.
Log is here https://pastebin.com/yMJgu0Wv

**Comment by timoline** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/6067

**Comment by juslex** [comment]
Some problem here with conbee. In zzh works fine.

**Comment by nurikk** [comment]
Can you guys generate map using graphviz/plantuml and compare results?

https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgerequestnetworkmap

**Comment by nanobra1n** [comment]
Mine and @timoline & @juslex issues are different  (I don't use a conbee II but a slaesh stick and I *do* get a graph)
![Webgraphviz](https://user-images.githubusercontent.com/15968173/106834709-f0a3e380-6663-11eb-98e2-2cc069f0120a.png)
Input for better legibility is here: https://pastebin.com/0JXUxXWH

**Comment by juslex** [comment]
Conbe II network map on zig2mqtt front end. 
<img width="2464" alt="Captura de Tela 2021-02-03 às 23 49 58" src="https://user-images.githubusercontent.com/66561713/106839410-ea6e3100-667c-11eb-8859-212d633c1719.png">
<img width="2478" alt="Captura de Tela 2021-02-03 às 23 49 49" src="https://user-images.githubusercontent.com/66561713/106839419-f0641200-667c-11eb-81b2-3b808f3ebc24.png">

**Comment by juslex** [comment]
<img width="1892" alt="Captura de Tela 2021-02-04 às 00 05 56" src="https://user-images.githubusercontent.com/66561713/106839444-fe199780-667c-11eb-96c5-1624c4c2ebf2.png">

The input https://pastebin.com/aAW1Z4xh

**Comment by juslex** [comment]
Previous zzh network map in front end (I have added more devices since the date of this map)

![IMG_8221C12474ED-1](https://user-images.githubusercontent.com/66561713/106839997-10e09c00-667e-11eb-8892-d44c0e8e2569.jpeg)

**Comment by nurikk** [comment]
> Previous zzh network map in front end (I have added more devices since the date of this map)
> 
> ![IMG_8221C12474ED-1](https://user-images.githubusercontent.com/66561713/106839997-10e09c00-667e-11eb-8892-d44c0e8e2569.jpeg)

Gorgeous map :)

**Comment by juslex** [comment]
I updated to latest dev version today and the map on conbee remains the same.
<img width="1770" alt="Captura de Tela 2021-02-11 às 10 03 14" src="https://user-images.githubusercontent.com/66561713/107640401-fd6e9b80-6c50-11eb-94a7-51f96703b6fe.png">

**Comment by nanobra1n** [comment]
Can we get an explanation what exactly qualifies as a child/parent/sibling? In my understanding a child is an end device only connected to a router (the parent) or a router (in this case the child) connected to the coordinator (the parent in this case). A sibling is a router connected to other routers. The meaning of noneofheabove is unclear to me. If my limited understanding is correct (and it might not be) I would expect to be more connection lines if parent is checked from the coordinator. In my example (first picture) there is only one which I would only expect if all traffic would route only through that one router which I find very hard to believe. Also how does the color of the line play into this?

**Comment by sjorge** [comment]
Mine never look connected on the frontend, looks fine with graphviz though, I am using the source=true bit and everything seems to generally have a path from coordinator -> (0 or more routers) -> end device, with a few exception when I scan when the network is really busy.

My network is a whole not bigger though, don't think the render will be very useful at all for me so I never really cared much. (graphviz map is over 50mb sometimes hehe)
