### ISSUE TITLE
Device Options are not considered in device settings view

### ISSUE THREAD

**Issue by CSchlipp** [nurikk/z2m-frontend#286]
After tonight's update, I noticed that every device now carries its own settings page, nice!
However, I've noticed a small bug in here...

## Problem Description
I have some global "device_options" defined in z2m configuration.yaml that are valid for all devices. These settings are however not shown in the settings page of a single device.

## Current Behavior
configuration.yaml (Global config valid for all devices)
```
device_options:
  retain: true
  legacy: false
groups: groups.yaml
devices: devices.yaml
```

device.yaml (only device specific settings, e.g. debounce)
```
'0xdeadbeefc0febabe':
  friendly_name: '0xdeadbeefc0febabe'
  debounce: 60
```

In the raw settings-JSON, this translates to (shortened)
```
{
    "commit": "99274c7",
    "config": {
        "device_options": {
            "legacy": false,
            "retain": true
        },
        "devices": {
            "0xdeadbeefc0febabe": {
                "debounce": 60,
                "friendly_name": "0xdeadbeefc0febabe"
            }
        }
    }
}
```

The settings page is showing the device-specific config correctly. but omits the global settings:
![image](https://user-images.githubusercontent.com/4139563/106564594-b89a8480-652d-11eb-8815-c8adeaa5d2ff.png)

## Expected behavior
The settings page should show the global options as default values, but override it with the device specific config, if applicable.

**Comment by nurikk** [comment]
These options shouldn't be here, this tab represents only the current device specific settings

**Comment by CSchlipp** [comment]
Guess that depends on what information you expect from this page. My expectation would be that I can check what the actual setting of a device currently is. 
Right now, if e.g. the retain checkbox is unchecked, the user still has to keep the global retain defaults in mind and combine it to get the final value of this setting. 

"Merging" both options would display the correct state of the devices at all times. 
In the end, device_options do nothing more but define the default value of a setting (e.g. retain defaults to true). Therefore, in my option, the device settings page should not silently assume a different default value.
Hopefully, the following table explains it a bit better:
| `device_options` settings |      `device` settings    | displayed result | 
|:----------:|:-------------:|:---|
| undefined |  undefined |  If none is defined, fall back to and display z2mqtt defaults |
| defined |    undefined   |    if only global device_options are defined, show this as the default state for the inputs |
| defined | defined |     if both, global and device specific options are defined, show the device specific setting |
| undefined  |  defined |    if only device specific options are defined, show this state |

(Side effect: When saving device settings, a setting only needs to be persisted if it is different from the global device_options!)



**After all, probably one of the best arguments is a indeed a practical one:**
With the current behavior, it is not possible to override a "true"-setting in the global device_options flag for single devices with "false", as it is simply impossible to uncheck the checkbox.

**Comment by timoline** [comment]
Currently there is no way to change these global "device_options" (in the frontend) ?

**Comment by nurikk** [comment]
> Currently there is no way to change these global "device_options" (in the frontend) ?

Correct

**Comment by timoline** [comment]
ah ok, it will be in the future?

**Comment by nurikk** [comment]
Definitely
