### ISSUE TITLE
Force removing a device leads to an empty page.

### ISSUE THREAD

**Issue by TilmanK** [nurikk/z2m-frontend#29]
1. Open the page for a device. 
2. Remove it and select force remove (might happen without also).

A redirect to the device list would make more sense.

P.S.: Thanks for the great work :)

![image](https://user-images.githubusercontent.com/8856390/95013114-4fb60500-063e-11eb-8f73-326fe47fd51c.png)

**Comment by nurikk** [comment]
This is fine, as soon as you rejoin device you will see device data. This behaviour I like more since I'm zigbee firmware developer and perform many cycles join/leave during testing.
