### ISSUE TITLE
settings.schema.json titles

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#299]
Can we / I just change some titles in the schema, without breaking anything?

like:
Advanced settings -> Advanced 
Experimental options -> Experimental
Networkmap options -> Networkmap
MQTT settings -> MQTT 
Serial settings -> Serial

Because we already in Settings I think its not needed....  :-)

**Comment by nurikk** [comment]
Sure you can, just raise PR

**Comment by timoline** [comment]
Is it also possible to do a little reorganize in the settings?
I mean, advanced is pretty large, maybe we can move the logging options to its own menu-item?

**Comment by nurikk** [comment]
yes, you can do this in this file
https://github.com/nurikk/z2m-frontend/blob/master/src/components/settings/uiSchema.json

raise the PR and don't forget to attach screenshot with resulting changes

**Comment by timoline** [comment]
I'm not sure how to do this, is possible for you to create a little example?
(for example the logging options)

**Comment by timoline** [comment]
I just noticed that the description for a boolean is not working yet

![image](https://user-images.githubusercontent.com/680252/107140851-5ffc2a80-6925-11eb-8186-2943e4f77170.png)

**Comment by nurikk** [comment]
> I just noticed that the description for a boolean is not working yet
> 
> ![image](https://user-images.githubusercontent.com/680252/107140851-5ffc2a80-6925-11eb-8186-2943e4f77170.png)

yep, known issue https://github.com/rjsf-team/react-jsonschema-form/issues/2203

**Comment by timoline** [comment]
I wanted to change the networkmap (colors) with "format": "color"

In the playground it works fine
https://rjsf-team.github.io/react-jsonschema-form/

But when I add this to the settings.schema.json it just won't work, do you have any idea?

**Comment by nurikk** [comment]
> I wanted to change the networkmap (colors) with "format": "color"
> 
> In the playground it works fine
> https://rjsf-team.github.io/react-jsonschema-form/
> 
> But when I add this to the settings.schema.json it just won't work, do you have any idea?

No need to tinker with this options, they are from internal z2m map implementation. I’ll hide this options from UI
