### ISSUE TITLE
Implement unbinding from default_bind_group

### ISSUE THREAD

**Issue by ginkage** [nurikk/z2m-frontend#30]
What I'd like to see is the ability to one-click (or even zero-click) unbind for devices from the `default_bind_group`.
At the moment, you have to jump through some hoops, learn [how it all works](https://www.zigbee2mqtt.io/devices/E1743.html#binding) and manually send an MQTT message in order to make something like an IKEA Switch bind to a group of lights: you need to send a message to the topic `zigbee2mqtt/bridge/unbind/[DEVICE_FRIENDLY_NAME]` with payload `default_bind_group`. After that one message the rest works pretty much automagically from the GUI, so I think that this first unbind might as well be triggered by either clicking the "bind" button (for an arbitrary device or group), or have a dedicated button for it.

**Comment by nurikk** [comment]
Hello, can you rejoin your device (so it will have this default group bind) and then take a dump using the following command? Wesocat can be downloaded https://github.com/vi/websocat

`websocat ws://192.168.1.200:8080/api > data.log`

**Comment by ginkage** [comment]
[Here](https://pastebin.com/hvmwRNmf) you go.

**Comment by nurikk** [comment]
I don't  see any bindings, can we expose this default group bind in device information, so users can use unbind from ui? @Koenkk

**Comment by renne** [comment]
It would also be great to list bindings with the default group in the bindings list and default groups in the group list.

**Comment by Koenkk** [comment]
Fixed in latest dev, existing users need to reconfigure before this will show up.
