### ISSUE TITLE
Groups view crashes client if a device has been removed

### ISSUE THREAD

**Issue by nbostrom** [nurikk/z2m-frontend#31]
### Reproduce: 

1. Forcefully remove a device that is included in a zigbee group.
    (I don't know if "forcefully" matters. I had to remove a broken device)
2. Click the "Groups" menu link.
3. **The js client crashes**
4. Remove the device from the group in the config file and restart z2m.
5. Click the "Groups" menu link.
6. **Groups view renders just fine**

It might be a good idea to at least wrap every view in an ErrorBoundary so that an error won't crash the whole ui.

**Comment by nurikk** [comment]
We should remove device from group upon force removal, @Koenkk right?

**Comment by Koenkk** [comment]
Yes (zigbee-herdsman does this)

**Comment by Koenkk** [comment]
Should be fixed in latest dev branch
