### ISSUE TITLE
Power source of Xiaomi relays appear as unknown

### ISSUE THREAD

**Issue by McGiverGim** [nurikk/z2m-frontend#32]
I'm not too sure if this is correct, but for Xiaomi relays the power appears as unknown (question mark).

I have seen that:

https://github.com/nurikk/z2m-frontend/blob/7bf3f3db4f677b9c7e8edb60b548277d8240eb2f/src/components/power-source/index.tsx#L35-L38

My other routers contain `Mains (single phase)` so they appear ok, but the Xiaomi one contain `DC Source`. I don't know if we can simply add it to this `case` to fix the issue or the `DC Source` can be used for some battery powered devices.

**Comment by nurikk** [comment]
Done
