### ISSUE TITLE
Show number of bindings used/available per device in web-frontend

### ISSUE THREAD

**Issue by renne** [nurikk/z2m-frontend#35]
## Is your feature request related to a problem? Please describe
When creating bindings it's often not clear how many bindings can be created per devices and if there is any number of bindings left to use.

## Describe the solution you'd like
Display "n/m" in "Bind" -> "Select devices" -> "Devices" where "n" is the number of bindings in use and "m" the maximum number of bindings or the number of available bindings.

## Describe alternatives you've considered
MQTT-Get queries are too complicated and waste time.

**Comment by nurikk** [comment]
Bindings table size is defined in device firmware, during compilation and this information never exposed.

**Comment by renne** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/4757
