### ISSUE TITLE
Groups: sort by friendlyName

### ISSUE THREAD

**Issue by Hacker-CB** [nurikk/z2m-frontend#36]
I think that it will be better, if devices ins the "groups" tab will be sorted by friendlyName.

My "Groups" tab now looks like:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/4232995/95500677-d3aa1d00-09af-11eb-92c8-88e56573933d.png">

**Comment by nurikk** [comment]
maybe @timoline want's to resolve this issue? :)

**Comment by timoline** [comment]
I'm very honored, but my skills are way out of league...
To be honest, I see what's going on in the code, but I'm (still) not able to these changes

**Comment by timoline** [comment]
Is this solved already?

**Comment by olafvs** [comment]
Just a remark: You should now that in the backend the order of the group (the first device) is used for reporting brightness of the group itself. It will be harder to now what is going on when the order of the devices in a group changes.

Maybe it's an idea to add a column for order in the group as well, or mark the first item with a color.
