### ISSUE TITLE
Show number of groups used/available per device

### ISSUE THREAD

**Issue by renne** [nurikk/z2m-frontend#37]
## Is your feature request related to a problem? Please describe
When adding devices to groups it's often not clear how many groups can be added per device and if there is any number of group slots left to use.

## Describe the solution you'd like
Display "n/m" in "Groups" -> "Select device" where "n" is the number of groups in use and "m" the maximum number of groups or the number of available group slots on the device.

## Describe alternatives you've considered
MQTT-Get queries are too complicated and waste time.

**Comment by nurikk** [comment]
Can you point where I can get this data?

**Comment by renne** [comment]
Is there a solution?
