### ISSUE TITLE
Add set devices operation_mode, sensitivity

### ISSUE THREAD

**Issue by G1K** [nurikk/z2m-frontend#39]
Add support for setting additional parameters in devices. 
For example operation_mode for 
https://www.zigbee2mqtt.io/devices/QBKG04LM.html 
`{
  "operation_mode": {
    "button": "single"|"left"|"right", // Always use single for a single switch
    "state": "VALUE"
  }
}`
and 
https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html `{"operation_mode": "command"}` - needed for binding 

and for sensitivity DJT11LM https://www.zigbee2mqtt.io/devices/DJT11LM.html

**Comment by nurikk** [comment]
This is already in progress 
https://github.com/Koenkk/zigbee2mqtt/issues/4466
