### ISSUE TITLE
[suggestion] Clearify donation button

### ISSUE THREAD

**Issue by Zagitta** [nurikk/z2m-frontend#390]
Hello,

May I suggest you clarify the donation button under the settings page to mention it's for the development of the frontend?
As it stands currently it may come off as a donate button to the zigbee2mqtt project itself when using the homeassistant addon which enables the frontend per default and integrates it into the sidebar like this:
![image](https://user-images.githubusercontent.com/865977/111343957-38af2080-867c-11eb-949c-ca92c5c644a8.png)

For extra bonus points it would be nice of you to add a donate button to @Koenkk as well :-)

**Comment by nurikk** [comment]
Done
