### ISSUE TITLE
Immax 07703L radiator valve shows low battery warning in the web interface when the battery is full

### ISSUE THREAD

**Issue by fuxoft** [nurikk/z2m-frontend#393]
For Immax 07703L radiator valve (model id TS0601), flashing red battery icon and "battery LOW" is shown in the web interface device list and in the device details although the battery is full. "battery_low" indication is correctly shown as OFF, which should be interpreted as "battery is full" and not display the warning.

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by fuxoft** [comment]
OK, here it is

**Comment by nurikk** [comment]
fixed [in this pr](https://github.com/Koenkk/zigbee-herdsman-converters/pull/2390) not a frontend issue.
