### ISSUE TITLE
[feature] show indication if a device has interviewd succesfully or not

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#40]
devices already show up during the interview stage, it would be nice to indicate a device has not yet complete it's interview.

**Comment by nurikk** [comment]
yep, nice to have
<img width="220" alt="Screenshot 2020-10-12 at 06 58 32" src="https://user-images.githubusercontent.com/1525421/95692470-961bed00-0c58-11eb-87c6-38665d159b38.png">
