### ISSUE TITLE
Got error: o is undefined

### ISSUE THREAD

**Issue by jti989** [nurikk/z2m-frontend#415]
I have an error when accessing the Groups Tab in Z2M.
Last thing I know is that I added a Tuya device to Z2M and to an existing group. The device stopped working and I force-removed it from the device list.

I have downloaded the state.json file, but am not sure if it's safe to upload here. It has quite a lot info in it. The device in question is not listed in the devices section of the file.

**Current url**: https://my.domain.io/#/groups
**Previous url**: 

**Error type**: TypeError
**Error message**: o is undefined

84848/wr</t.prototype.render@https://my.domain.io/main.7c791b396724cd5681c7.js:1:99173
Ha@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:918059
za@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:917858
Hs@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:958773
_l@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944926
xl@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944854
Sl@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:944715
fl@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:941702
Vi/<@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891410
60053/t.unstable_runWithPriority@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:994763
Hi@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891187
Vi@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891357
Wi@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:891290
ll@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:939081
enqueueForceUpdate@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:895545
72408/g.prototype.forceUpdate@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:977225
d@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:1001090
i@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:999835
e/this.procsessBridgeMessage@https://my.domain.io/main.7c791b396724cd5681c7.js:1:12364
e/this.onMessage@https://my.domain.io/main.7c791b396724cd5681c7.js:1:13827
22003/h</e.prototype._callEventListener@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:990250
e/this._handleMessage/<@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:984020
e/this._handleMessage@https://my.domain.io/scripts/vendor.d2ddf849cc03b8f1b4ad.js:2:983990

**Comment by nurikk** [comment]
I can’t help you without a state file

**Comment by jti989** [comment]
Well, I found a solution:
I edited the configuration.yaml file from zigbee2mqtt and deleted the ID of the device from the group.
My issue is solved for now, although I believe there is a bug while handling deletion of devices (maybe the bug is in koenkk/zigbee2mqtt and not in the frontend itself).

Please feel free to close this if you believe I am wrong.
Even if I don't think the state.json will help solving this, I would be willing to send it to you (not upload it here) if you want.

**Comment by Koenkk** [comment]
@jti989 I've tried to reproduce this bug but failed to do. On version 1.18.1 I did:
- Pair a device
- Create a group
- Add device to group
- Force remove device
- Groups tab still loads ok

**Comment by jti989** [comment]
I tried to reproduce as well, with no luck. Have not had any updates since...
