### ISSUE TITLE
Show device type (router vs end device) on a column

### ISSUE THREAD

**Issue by ciotlosm** [nurikk/z2m-frontend#43]
Currently we have "power" column on the UI, however there are devices like QBKG03LM which are connected to main wire, but not to neutral and can't action as routers. I'm not sure if this is a bug that they show `?` for Power column. 

There is also a bug somewhere (still investigating) which shows devices like LLKZMK11LM with `?` on the Power column. Also this column seem inconsistent for these:

![Screenshot 2020-10-10 at 09 19 52](https://user-images.githubusercontent.com/7738048/95647653-d6a12c80-0ad9-11eb-8498-1ec7ca442118.png)

**Comment by nurikk** [comment]
Can you hover over ? Icon and send me what's the title? Better way is to point me where I can find exhaustive list of all available power source types.

https://github.com/nurikk/z2m-frontend/blob/babb6bbec55299a0ce4a3296462a3d63c9563fec/src/components/power-source/index.tsx#L35

**Comment by ciotlosm** [comment]
I found this in code: https://github.com/Koenkk/zigbee-herdsman/blob/e55f57311efc167c23394edd7263fcfc89c05830/src/zcl/definition/powerSource.ts#L1

But there seems to be a bug also somewhere (See below screenshots of same device type):

![Screenshot 2020-10-10 at 09 52 06](https://user-images.githubusercontent.com/7738048/95648248-6943ca80-0ade-11eb-8d78-b6889ff396ed.png)
![Screenshot 2020-10-10 at 09 52 13](https://user-images.githubusercontent.com/7738048/95648251-6b0d8e00-0ade-11eb-915c-c4d1d3d66541.png)
