### ISSUE TITLE
Frontend changes configuration to become invalid

### ISSUE THREAD

**Issue by Larsen-Locke** [nurikk/z2m-frontend#430]
When you remove a qos value in the settings of a device the line in configuration.yaml is changed from e.g. qos:1 to  qos: null.  (instead of removing the qos line)
This is an error as only numbers are allowed and will prevent zigbee2mqtt from starting.

**Comment by Dema** [comment]
This is not a frontend bug, frontend runs in the browser, it cannot change files.

Frontend just calls the api and tt sends `{qos:undefined}` when you clear the value. I've tried sending `null`, it still saves `qos: null` in `configuration.yaml`. This looks like a bug in zigbee2mqtt itself.

**Comment by Larsen-Locke** [comment]
Hi Dmitry,

 

thank you for your answer.

Should I raise an issue in zigbee2mqtt?

 

Regards

Von: Dmitry Olyenyov ***@***.***> 
Gesendet: Samstag, 10. April 2021 22:46
An: nurikk/z2m-frontend ***@***.***>
Cc: Larsen-Locke ***@***.***>; Author ***@***.***>
Betreff: Re: [nurikk/z2m-frontend] Frontend changes configuration to become invalid (#430)

 

This is not a frontend bug, frontend runs in the browser, it cannot change files.

Frontend just calls the api and tt sends {qos:undefined} when you clear the value. I've tried sending null, it still saves qos: null in configuration.yaml. This looks like a bug in zigbee2mqtt itself.

**Comment by Koenkk** [comment]
Indeed a zigbee2mqtt bug, but fixed this now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
