### ISSUE TITLE
Multiple types of links (176 / 36)

### ISSUE THREAD

**Issue by avvalex** [nurikk/z2m-frontend#431]
In the frontend's map it's explained that values with / represents multiple type of links. But what does that means exactly?
For example, the Sonoff ZBMINI "Luce Alex" has a LQI of 36, and apparently seems connected only with the coordinator. The link quality measurement is always around 28-39 (it lowers when the switch is on, maybe caused by EMI), nothing strange so far.
But also the other number changes, between 172 and 178. Where this number is taken from? Maybe one is the LQI from Coordinator to Sonoff and the other is the LQI from Sonoff to Coordinator?
Perhaps this should be better clarified in the guides.
Thanks!

<img width="1152" alt="113896842-97bf0b80-97ca-11eb-94d9-7020e7b86344" src="https://user-images.githubusercontent.com/60694870/113923661-17f46980-97e9-11eb-8ce2-3d9d1432ab59.png">

**Comment by nurikk** [comment]
In left bottom corner, there is help text. Have you read it?

**Comment by avvalex** [comment]
Yes, but i don't understand the meaning of "multiple type of links". Why are there multiple links between two devices?

**Comment by ahocquet** [comment]
I'm wondering the exact same thing. Why are there two LQI values on some lines whereas the LQI in the dashboard only gives one number ?

**Comment by davidjb** [comment]
Unstale

**Comment by soxhi8** [comment]
The existing tooltip is really not all that helpful. Is there any documentation it could link to?

**Comment by nurikk** [comment]
Hey guys, the map is more bells and whistles feature , knowing  details wouldn’t make any difference

**Comment by soxhi8** [comment]
> 
> 
> Hey guys, the map is more bells and whistles feature , knowing details wouldn’t make any difference

Hey, thanks for the answer! Just to elaborate a little: Most users might not know what to make of the "multiple types of links". If there is any external document that users could learn from, maybe the legend of the map could link to that. Or just omit the part about "multiple types of link", it might be more confusing than it helps. Nothing of high priority. But I came here with the same question, so at least @avvalex is not alone.

**Comment by mmschramm** [comment]
I am also wondering what "multiple types of links" could really mean here, and if it could help solving or explaining connection issues (probably someone could find out by looking at it in the source code).

**Comment by soxhi8** [comment]
I found some good documentation on the question over here: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/LQI-explained

> Hey guys, the map is more bells and whistles feature , knowing details wouldn’t make any difference

You are underselling the feature. For me it has been tremendously helpful for debugging reception issues. For example discovering routers that should have bi-directional connection (255/255), but only a show one-sided link. Also seeing which routers are connecting which devices over long distances has been great for building my network.

**Comment by erosha96** [comment]
> For example discovering routers that should have bi-directional connection (255/255), but only a show one-sided link.

Interesting. But what if I have THREE of numbers?

<img width="321" height="251" alt="Image" src="https://github.com/user-attachments/assets/191a3e63-1d77-4012-b524-f0a5d9a833e4" />
