### ISSUE TITLE
auth_token hash?

### ISSUE THREAD

**Issue by 877dev** [nurikk/z2m-frontend#438]
Hi,

Apologies if this is a generic issue, but I am wondering if the `auth_token` in `configuration.yaml` can be stored as a hash?
If so, which utility would be used to make the hash?

I tried with `mkpasswd` but the login box does not accept the password, only the hash, which kinda defeats the purpose.

Any pointers would be apprecaited!

**Comment by nurikk** [comment]
Hello, this is just a text string. No hashing supported.

**Comment by 877dev** [comment]
Hi. I see, thanks 👍
