### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by pdefoy** [nurikk/z2m-frontend#447]
Is there a plan to add authentication to the frontend? or did I miss it?
I looked around the different forums and could not find it.

Thanks

**Comment by svrooij** [comment]
@pdefoy I personally use nginx to expose some services to the internet. Nginx is famous for its fast reverse proxy.

you can also use nginx to check users. https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

Then you have to login to nginx before you can see the application. This way you can setup the same login for all services that the nginx server exposes to the world.

**Comment by pdefoy** [comment]
I did not know that. This is perfect, I already use nginx to reverse proxy through https. 
I will look into this authentication tonight. 

Thanks a lot  :)

**Comment by nurikk** [comment]
There is token based authentication implemented, check configuration documentation
