### ISSUE TITLE
Can't set Settings > Serial > adapter to null again (dev branche)

### ISSUE THREAD

**Issue by olafvs** [nurikk/z2m-frontend#449]
After setting the  adapter field, in the dev branch, to my adapter (zstack) it's not possible to go back to undefined (null).

**Comment by nurikk** [comment]
@Koenkk can you take a look please?

**Comment by Koenkk** [comment]
@olafvs can you provide the debug log when setting null? 

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by olafvs** [comment]
Here you are:

`Debug Received MQTT message on 'zigbee2mqtt/bridge/request/options' with data '{"options":{"serial":{"adapter":null,"disable_led":false,"port":"/dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_4F_25_0E-if00-port0"}},"transaction":"26m7a-81"}'
Error Request 'zigbee2mqtt/bridge/request/options' failed with error: 'serial.adapter should be equal to one of the allowed values'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{},"error":"serial.adapter should be equal to one of the allowed values","status":"error","transaction":"26m7a-81"}'`

**Comment by Koenkk** [comment]
@olafvs fixed now, can you confirm?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by olafvs** [comment]
I can now revert to null, by doing chosing the empty field in the dropdown (''). But there also appears a new option in the dropdown that explicitly says 'null'. By chosing this field the gui shows an error that does not appear in the logs.

**Comment by nurikk** [comment]
Using “null” as meaningful value looks hacky af, can we use something like “auto” for this purpose? @Koenkk

**Comment by olafvs** [comment]
Although at this point in time I think the average user of z2m knows what null is, it still is a developer/coding concept. If null in the background is translated to a best guess, I think it could be auto. Otherwise it could be something like unset, unknown, not set, .... 

In this specific case realize there are two options having the same meaning: '' and 'null'. Just one of those works: ''. So please also dump one of these options.

**Comment by Koenkk** [comment]
Added the `auto` type now, @olafvs can you check again.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by olafvs** [comment]
You made it go BOOM ;)

I don't have the gui anymore. But the service is running.

`sudo systemctl start zigbee2mqtt
pi@raspberrypi:/opt/zigbee2mqtt/data/log/2021-05-04.10-32-49 $ sudo systemctl status zigbee2mqtt
● zigbee2mqtt.service - zigbee2mqtt
   Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-05-04 19:27:42 BST; 802ms ago
 Main PID: 1887 (node)
    Tasks: 7 (limit: 2062)
   CGroup: /system.slice/zigbee2mqtt.service
           └─1887 npm

May 04 19:27:42 raspberrypi systemd[1]: Started zigbee2mqtt.
`

**Comment by Koenkk** [comment]
Cannot reproduce this

@nurikk do you know why the empty value is still there?

![image](https://user-images.githubusercontent.com/2892853/117061008-f4f2a200-ad21-11eb-95cb-09e14cc8cf8c.png)


```js
"adapter": {
  "type": ["string"],
  "enum": ["deconz", "zstack", "zigate", "ezsp", "auto"],
  "title": "Adapter",
  "requiresRestart": true,
  "description": "Adapter type, not needed unless you are experiencing problems"
}
```

**Comment by olafvs** [comment]
So when you do a new dev pull, your frontend still works? Ok that's strange.

**Comment by Koenkk** [comment]
Do a `git pull` + `npm ci`

**Comment by nurikk** [comment]
> Cannot reproduce this
> 
> @nurikk do you know why the empty value is still there?
> 
> ![image](https://user-images.githubusercontent.com/2892853/117061008-f4f2a200-ad21-11eb-95cb-09e14cc8cf8c.png)
> 
> ```js
> "adapter": {
>   "type": ["string"],
>   "enum": ["deconz", "zstack", "zigate", "ezsp", "auto"],
>   "title": "Adapter",
>   "requiresRestart": true,
>   "description": "Adapter type, not needed unless you are experiencing problems"
> }
> ```

This is empty default value, to get rid of it you should set default value


```json
{
    "type": "object",
    "required": [],
    "properties": {
        "adapter": {
            "type": "string",
            "enum": [
                "deconz",
                "zstack",
                "zigate",
                "ezsp",
                "auto"
            ],
            "default": "auto",
            "title": "Adapter",
            "requiresRestart": true,
            "description": "Adapter type, not needed unless you are experiencing problems"
        }
    }
}
```

Pro tip: you can always test schema in [react-jsonschema-form playground](https://rjsf-team.github.io/react-jsonschema-form/)

**Comment by Koenkk** [comment]
@nurikk thanks, added

**Comment by olafvs** [comment]
So finally figured it out. With the previous release there was the option of setting null. By chosing this it was in my configuration.yaml. After that the front end got stuck. Manually removing it fixed it.

I tested the auto feature and it does not cause any problems. Cannot test if it actually does it's magic, but i guess it still works. 

Going back and forward between auto and my adapter also works. Issue is closed.
