### ISSUE TITLE
Add/edit/delete scenes

### ISSUE THREAD

**Issue by renne** [nurikk/z2m-frontend#45]
I suggest
* Scenes table
  * Add new scene button
  * List of scenes
    * Edit button
    * Delete button
    * Delete checkbox
* Assignment/relation table
  * Add assignment/relation between scene and device or group button
  * List of Assignment/relations
      * Edit button
      * Delete button
      * Delete checkbox

**Comment by nurikk** [comment]
Currently there is no api to retrieve list of scenes, right? Without it I can't start implementing scenes

**Comment by nstadigs** [comment]
I think scenes support could be implemented without the ability to retrieve list of scenes.

First of all, in z2ms database there are identified by `${groupId}-${sceneId}`.

We could have a dedicated group view that looks similar to the dashboard view, but it would only show the entities in the group. It would also have a number input for the scene id and a "Store/Save" button. Changing the number input would send a `scene_recall` command to `zigbee2mqtt/${groupId}/set`. This would "display" the scene IRL. The user could then use the entity-boxes in the dashboard-like view to configure the scene. When done, pressing "Store" would send a "scene_store" command for the selected scene id.

If scene names gets implemented in the future we can add that to this view.

**Comment by nstadigs** [comment]
If you agree, I could try to implement this feature.

**Comment by nurikk** [comment]
I’m always welcome for any contributions. 
Perhaps we can also ask @Koenkk to implement better scenes API :)

**Comment by nstadigs** [comment]
I could be wrong, but I think that what's implemented in z2m is what's provided by the zigbee spec. If you would like names and lists you would have to store it in a database separate from zigbee. I mean, I think that this feature could be implemented by a client, outside of z2m. So I guess it depends on where z2m stands on the "user client" <-> "zigbee adapter" scale. Does this make sense?

**Comment by nurikk** [comment]
Api has to be implemented on Zigbee2MQTT side, also saving names and publishing scenes list with devices in it

**Comment by nstadigs** [comment]
When I said "client" I did not mean the z2m-frontend. I meant user-facing client apps, like home-assistant for example. z2m-frontend does not have it's own database, so I consider it a pure frontend for z2m. I do think that z2m should at least be able to provide a list of configured scene ids tho.

**Comment by nurikk** [comment]
Yes, this exactly what I wanted to say

**Comment by nstadigs** [comment]
@nurikk Thanks a bunch for implementing this! I really appreciate it :)
