### ISSUE TITLE
Device setting optimistic not ticked by default

### ISSUE THREAD

**Issue by olafvs** [nurikk/z2m-frontend#450]
When I look at any device the optimistic checkbox is not ticked, but I think by deault everything should be ticked because the default state is true.

**Comment by nurikk** [comment]
Seems fixed
<img width="211" alt="Screenshot 2021-06-20 at 00 14 06" src="https://user-images.githubusercontent.com/1525421/122648579-77adb000-d15c-11eb-96a2-57435f16ba93.png">
