### ISSUE TITLE
Frontend images are hosted on zigbee2mqtt.io

### ISSUE THREAD

**Issue by blaxer** [nurikk/z2m-frontend#457]
As a security and privacy measure, I do not allow my Z2M container to have access to the internet. And my browsers privacy plugins have identified that images in the frontend are hosted on zigbee2mqtt.io, could we please have the option to host these locally?

**Comment by nurikk** [comment]
Images are fetched by browser, not by container

**Comment by nurikk** [comment]
Duplicate of #457
