### ISSUE TITLE
[bug] cannot remove default bind from ikea on/off remote

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#46]
It shows up with the group I’d of 901, but it can’t be unbound.

I had to manually unbind it via mqtt, was able to bind via ui afterwards

**Comment by nurikk** [comment]
Hello, can you please share logs? How mqtt command you've used

**Comment by sjorge** [comment]
I didn’t save any logs, but the command is the one documented for the device

```
mosquitto_pub -t zigbee2mqtt/bridge/request/device/unbind -m '{"from": "0xbc33acfffea237f7", "to": "default_bind_group"}'
```

**Comment by sjorge** [comment]
default_bind_group is a group that does not exist but has some special meaning for z2m

**Comment by nurikk** [comment]
What's default group btw?

**Comment by sjorge** [comment]
> What's default group btw?

‘default_bind_group’

**Comment by Koenkk** [comment]
@sjorge last time I checked when not binding the device it will send commands to group 0, this causes problems since some devices are by default in this group.

**Comment by sjorge** [comment]
> @sjorge last time I checked when not binding the device it will send commands to group 0, this causes problems since some devices are by default in this group.

Ah that does sound familiar, some kind of power plug was listening to those commands on group 0 or something :(

**Comment by Koenkk** [comment]
@nurikk don't investigate further on this, this should be fixed from Zigee2MQTT. The solution is to set the name of this group to `default_bind_group`.
