### ISSUE TITLE
Z2M uses device images from zigbee2mqtt.io without CORP header or crossorigin attribute

### ISSUE THREAD

**Issue by mdegat01** [nurikk/z2m-frontend#461]
## What happened

I set my reverse proxy serving the Zigbee2MQTT UI to add the security header [COEP](https://developer.cdn.mozilla.net/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy) with the value `require-corp`. When I did I got errors for all the device images referenced in the UI. Seems the device images are all hosted at `https://www.zigbee2mqtt.io/images/devices/<device type>.jpg`. There are two issues here:
1) The `img` tags do not have a [crossorigin](https://developer.cdn.mozilla.net/en-US/docs/Web/HTML/Attributes/crossorigin) attribute. With a COEP policy set the browser won't even do a CORS check without this attribute so even though they return `Access-Control-Allow-Origin: *` there are still errors. Setting this attribute is recommended for all cross-origin img includes now.
1) Those images do not return a [Cross-Origin-Resource-Policy](https://developer.cdn.mozilla.net/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy) header with the value `cross-origin`. This is a newer, alternative way to tell the browser this asset can be embedded anywhere without a CORS check. If this header is set on the images then COEP accepts them with or without the `crossorigin` tag

## What did you expect to happen

Expected the images to be marked as `crossorigin` or have `Cross-Origin-Resource-Policy: cross-origin` and show up even when a `Cross-Origin-Embedder-Policy: require-corp` header is added.

**Comment by mdegat01** [comment]
Note that there is some overlap between this request and #457. I don't personally consider it an issue if the frontend pulls in device images from Z2M as long as they are done so in a way that satisfies the latest security measures. However if it is decided that Z2M should pull in device images and serve them up instead of having the browser reach out to zigbee2mqtt.io then that fixes this issue as well.

**Comment by nurikk** [comment]
cc @Koenkk

**Comment by Koenkk** [comment]
@nurikk if I understand correctly, these requests are made from the frontend right?

**Comment by nurikk** [comment]
all <img> tags are with `crossorigin` attribute, but there are still svg <image> tags on map

**Comment by Koenkk** [comment]
What do you mean with tags?

**Comment by nurikk** [comment]
> What do you mean with tags?

`<img src....>`

**Comment by Koenkk** [comment]
But this is part of the frontend code right? (I don't understand how this can be fixed from z2m)

**Comment by nurikk** [comment]
case is solved)) I'm closing this issue to make less confusion

**Comment by mdegat01** [comment]
Lol well I was confused by this conversation but I do see the `crossorigin=anonymous` attribute on all the images on the latest release so thanks! 👍
