### ISSUE TITLE
device settings-specific refresh itself

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#489]
When pressing the + button it lookslike the page refresh itself after a few seconds, so there is no way to press submit :-)

**Comment by weltmeyer** [comment]
Same happens on the reporting settings page.. cant set it as it refreshes and clears my selections before i am able to press "apply"

**Comment by timoline** [comment]
Also on bind page...

**Comment by JoachimEngelmann** [comment]
I have the same issue. The cause for this if z2m receives some zigbee packages. I can reproduce it with a zigbee button (Hue dimmer switch), open a mentioned menue item, press the button -> menue closes

**Comment by Claude2666** [comment]
I have the same problem. Running frontend   0.4.10.  When I try to update Reporting or Settings of a device, the page is automatically refreshed after a few seconds, clearing all fields I entered, making it impossible to update something.

**Comment by JoachimEngelmann** [comment]
Same issue in "Bind"

**Comment by nurikk** [comment]
Fixed in latest dev branch

**Comment by afoeder** [comment]
is this the same as #528?

**Comment by nurikk** [comment]
> is this the same as #528?

Yes

**Comment by Claude2666** [comment]
I can confirm that with frontend 0.4.15 it is working properly.

Thanks.

**Comment by timoline** [comment]
> I can confirm that with frontend 0.4.15 it is working properly.
> 
> Thanks.

How can you tell?
The device-specific page is under construction :-)

**Comment by Claude2666** [comment]
I just updated zibee2mqtt to the latest dev and it came with frontend 0.4.15  No the page is no longer refreshed.  I can enter values in the reporting tab without them being erased.

**Comment by smulle48** [comment]
The problem is still there on the Bind page
