### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by SAOPP** [nurikk/z2m-frontend#5]
Hi! Thanks for da job. I think the official container is needed.

**Comment by nurikk** [comment]
Hi, @SAOPP! Soon this admin interface will be incorporated into z2m and included in to default z2m installation

**Comment by SAOPP** [comment]
Awesome. It will be great! Thanks again, dope work.

**Comment by Koenkk** [comment]
This is included in the `latest-dev` image now, can be closed.

**Comment by tavalin** [comment]
@Koenkk are there any instructions on how to use this when using the `latest-dev` docker image?

**Comment by Koenkk** [comment]
@tavalin https://www.zigbee2mqtt.io/information/frontend.html
