### ISSUE TITLE
"Last seen" display/sorting broken in "Devices" tab (when using ISO 8601)

### ISSUE THREAD

**Issue by linuxrrze** [nurikk/z2m-frontend#500]
I found the option "Last seen" and enabled it - using "ISO_8601_local" for better readability.

However in the "Devices" tab I got lots of "Just now" entries (even for devices that had been offline for quite some time) and the sort order was kind of messed up (mixing "Just now" with real times).

Changing the setting to "epoch" fixed this (and also changed the offline devices from "Just now" to something like "1 month ago".

Looks like something's fishy when time format is "ISO 8601 (local)":
- Offline devices should not report "Just now" (by default)
- Sorting should result in the same ordering as it does with "epoch" timestamps

**Comment by nurikk** [comment]
Hi, @linuxrrze 
if you run `date` in your linux ssh terminal, what result it would give? Does result matches to your local(browser) time?
And if you visit this [link](https://webbrowsertools.com/timezone/) and search for `Time on Local Machine` does this number match?

**Comment by linuxrrze** [comment]
`date` reports:
Mi 5. Mai 12:24:24 CEST 2021

The above `link` reports:
Wed May 05 2021 12:24:38 GMT+0200 (Central European Summer Time)

(This is both on the client machine running the browser, not on the machine running zigbee2mqtt)

**Comment by nurikk** [comment]
date command has to be executed on same machine running Zigbee2mqtt (if it’s docker, you have to run date command Inside same docker container)

**Comment by linuxrrze** [comment]
`docker exec -ti docker-homeassistant bash`
bash-5.0# date
Wed May  5 13:27:36 CEST 2021

`Link` reports:
Wed May 05 2021 13:28:10 GMT+0200 (Central European Summer Time)
