### ISSUE TITLE
z2m-frontend as addon in hass?

### ISSUE THREAD

**Issue by bartplessers** [nurikk/z2m-frontend#506]
Hi,

I'm running Z2M as an addon in hass, so I can use the "build in" frontend.
However, I want to run the same frontend on other hass-instances on my network (thus without the zigbee component), connected to the same mqtt broker.
Is this possible?
On the other hass-instances, I run https://github.com/yllibed/Zigbee2MqttAssistant, but this has slightly different functionality and interface (and is not updated anymore).

So my question: can I run the same frontend as buildin to Z2M, but than on a standalone machine?

grtz
B

**Comment by nurikk** [comment]
Hello, fronted is part of Zigbee2MQTT, you just need to configure port in configuration.yaml and setup port mappings 
https://www.zigbee2mqtt.io/information/frontend.html

**Comment by nurikk** [comment]
This is currently not supported
