### ISSUE TITLE
Got error: The operation is insecure.

### ISSUE THREAD

**Issue by deryalex96** [nurikk/z2m-frontend#510]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

![50DAFD3A-478B-4EC2-8FA5-8729AADEA606](https://user-images.githubusercontent.com/53148736/117554411-c2b1af00-b057-11eb-9cfe-4bb90ad3b2e1.jpeg)

**Current url**: http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/#/
**Previous url**: 

**Error type**: SecurityError
**Error message**: The operation is insecure.

restoreState@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/main.22f9c9018f9c72dffcff.js:1:92144
componentDidMount@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/main.22f9c9018f9c72dffcff.js:1:92350
ds@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:1038183
kl@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:1055010
kl@[native code]
http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:1100695
Il@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:1051749
fl@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:1047860
fl@[native code]
http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:997342
http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:1100695
Vi@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:997288
Wi@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:997223
Oe@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:1068169
Zt@http://192.168.1.111:8123/api/hassio_ingress/LFJ9ydJojnY4-JzZ5DR3WyVdYL6RjzqDAAuXO4ky-vs/scripts/vendor.46f2f1bd08054c950eed.js:2:975927
Zt@[native code]

**Comment by nurikk** [comment]
`DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN`
