### ISSUE TITLE
More i18n

### ISSUE THREAD

**Issue by nurikk** [nurikk/z2m-frontend#515]
Hi, guys! Thanks a lot for your contributions! I've added more keys available for translations, feel free to raise a PR any time if you're interested

@Burki24 @NebzHB @muddy79

https://github.com/nurikk/z2m-frontend/commit/bbb43207b0ed053161a8b07f188b74a808b014ea

**Comment by Burki24** [comment]
Thanks for that.

how it will run, if we have more translations as in your en.json file? Do we need to expand both files? e.g. de.json AND en.json? Or do we need your update for additional keys in en.json?

greetings,
Burki24

**Comment by timoline** [comment]
Maybe this is something we/you can use, I used it before with other opensource projects
https://docs.transifex.com/projects/open-source-project

**Comment by Burki24** [comment]
The last additional language-changes had no effect on the frontend. All made changes to "device/xxx/exposes/ where not recognized. So there is no change if I switch from english to any other language. 

How can we fix that?

**Comment by NebzHB** [comment]
Hello @nurikk,

something strange :
![image](https://user-images.githubusercontent.com/28622481/120807651-78352c80-c548-11eb-9486-ccab93a4f72f.png)
"dans un instant" is nowhere in my translations... there is not even the word "instant" in it... do you know where it could come from ? and sometime i see "à l'instant" (better translation)... any idea ?

**Comment by NebzHB** [comment]
@nurikk do you know where this status come from ? and where could i translate it ?

**Comment by nurikk** [comment]
> Hello @nurikk,
> 
> something strange :
> ![image](https://user-images.githubusercontent.com/28622481/120807651-78352c80-c548-11eb-9486-ccab93a4f72f.png)
> "dans un instant" is nowhere in my translations... there is not even the word "instant" in it... do you know where it could come from ? and sometime i see "à l'instant" (better translation)... any idea ?

This comes from external library, and not available for customisation

**Comment by nurikk** [comment]
Hi guys, we've got special translation tool in our hands, translation became even easier

https://poeditor.com/projects/view?id=494809

**Comment by NebzHB** [comment]
thx @nurikk, i'm registred but that link is 404 do we need to subscribe to frontend translation or something ?

**Comment by nurikk** [comment]
> thx @nurikk, i'm registred but that link is 404 do we need to subscribe to frontend translation or something ?

Sorry, wrong link  https://poeditor.com/join/project?hash=Az88waAhPd
