### ISSUE TITLE
Routes not shown for Aqara ZNCZ12LM

### ISSUE THREAD

**Issue by TSKnuhtsen** [nurikk/z2m-frontend#523]
Hello;

When I ran Z2M: front_end - map function with [Ikea Smart Plugs](https://www.zigbee2mqtt.io/devices/E1603_E1702.html) as routers, I got beautiful graphs showing links from coordinator down to the end-device -- https://ibb.co/y59VvCD

I have since replaced my Ikea Smart Plugs with Aqara Smart Plugs (https://www.zigbee2mqtt.io/devices/ZNCZ12LM.html) and the graph functionality is essentially non-functional. For all routers, LQI query fails and produces graphs that look like these -- https://ibb.co/HNwnW04 && https://ibb.co/5TLnCPp

If this is because the Aqara Smart Plugs are too proprietary, I'll be okay with that and only use the dashboard, but I would love to have the 'map' functionality back. If there's anything I can do to help you accommodate these routers in the 'map' functionality, let me know and I'd be happy to assist.

Thanks again for all of your hard work and I look forward to any possible resolutions here!

**Comment by TSKnuhtsen** [comment]
**UPDATE**

My gateway / coordinator went down for two days due to a power outage and me not being able to get back to the facility due to weather concerns.

When I get to the facility, I power back on my gateway, I go to build map view and the routes are perfect! https://ibb.co/xG4rZjP

Any idea what could have caused this? Would love for this to be the normal :)

**Comment by nurikk** [comment]
Hi, this is not a frontend issue. Kindly raise a ticket tin z2m repo to get support
