### ISSUE TITLE
A few bug in the zigbee2mqtt web frontend

### ISSUE THREAD

**Issue by pawol** [nurikk/z2m-frontend#527]
Hi,
I got TRVs TS0601 and I noticed there is afew bugs in the zigbee2mqtt web frontend.
I use the latest zigbee2mqtt v1.18.3 + CC2531 with zStack12 20201127.
List of noticed bugs:

1. Firmware version and one's date is not shown in the OTA tab. Firmware update works well
2. Missing scheduler configuration in the "device dashboard". It is possible to program a scheduler by command like:
 
mosquitto_pub -h localhost -t 'zigbee2mqtt/termostat_w_salonie/set/schedule' -m '{"workdays": [{"hour": 6,"minute": 0,"temperature": 20},{"hour": 8,"minute": 0,"temperature": 21},{"hour": 12,"minute": 00,"temperature": 21},{"hour": 15,"minute": 00,"temperature": 21},{"hour": 17,"minute": 00,"temperature": 21},{"hour": 21,"minute": 00,"temperature": 19}]}'

mosquitto_pub -h localhost -t 'zigbee2mqtt/termostat_w_salonie/set/schedule' -m '{"holidays": [{"hour": 6,"minute": 0,"temperature": 20},{"hour": 8,"minute": 0,"temperature": 21},{"hour": 12,"minute": 00,"temperature": 21},{"hour": 15,"minute": 00,"temperature": 21},{"hour": 17,"minute": 00,"temperature": 21},{"hour": 21,"minute": 00,"temperature": 19}]}'

4. There are untitles switched in the "device dasboard"
5.  Two of untitled switches in the "device dashboard" control the same item "away mode" (simply doubled items)
6.  It is not possible to control parameters of "window detection" in any way - even via mqtt commands

**Comment by nurikk** [comment]
Hi, this is purely device converter imperfections. Kindly raise a ticket in zigbee-herdsman-converters repo
