### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by igiul667** [nurikk/z2m-frontend#55]
I recently rebooted my intel nuc, which is runnig hassio supervised, and zigbee devices were not working. I restarted home assistant and the zigbee addon many times but nothing changed. To figure out the issue i tries to access the zigbee2mqtt edge web interface but it is giving error 502. Trying to send zigbee commands gives error "MAC no ack"

**Comment by nurikk** [comment]
I believe something happened to your usb stick and z2m can't start. Try to unplug/plug and restart z2m

**Comment by igiul667** [comment]
Yeah, I tried doing that multiple times but nothing. From the logs evertthing seemed to work until the mack no ack error. I rebooted the system and it was not working still, but on the second reboot it started working again... not shure why.
