### ISSUE TITLE
Show device network address in hex form on zigbee map

### ISSUE THREAD

**Issue by grafalex82** [nurikk/z2m-frontend#555]
All zigbee related software (sniffers, configurators) work with network addresses in a hexadecimal form. Unfortunately network map generated by Z2M shows network address in a decimal form, which is very inconvenient while debugging network issues.
![image](https://user-images.githubusercontent.com/23584882/119697347-c4051900-be58-11eb-89a0-851337b2263f.png)

Would it be possible to display short network address in a hexadecimal form?

I even localized the line where this is printed (networkMap.js line 86) but unfortunately I do not know JavaScript and do not have development environment set up to fix/test with a reasonable effort. 

Can someone add a dec->hex conversion there, please?

**Comment by nurikk** [comment]
Hi, this is not part of frontend codebase, kindly raise a ticket in main z2m repo
