### ISSUE TITLE
UI seems to wrap in unsable ways with long list of presets

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#558]
Develoco   HESZB-120 shows add ui under expose, I'm assume because the initial list of buttons is to long.

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/379665/120203940-8c1b1e80-c228-11eb-883e-7378b8943501.png">

[state.json.zip](https://github.com/nurikk/z2m-frontend/files/6570788/state.json.zip)

**Comment by nurikk** [comment]
Fixed, thanks!
