### ISSUE TITLE
OTA progress shows unreplaced "remaining_time" string

### ISSUE THREAD

**Issue by syphernl** [nurikk/z2m-frontend#562]
During an OTA update a string "remaining_time" is shown, see the screenshot:

![image](https://user-images.githubusercontent.com/639906/120469358-834e5800-c3a2-11eb-8e64-d8a3423905b5.png)

Judging from the [code](https://github.com/nurikk/z2m-frontend/blob/master/src/components/ota-page/index.tsx#L30) it is supposed to show the time there, yet it doesn't.
The remaining time does show up from time to time in the popup in the lower right corner.

Z2M version: [1.19.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0)

**Comment by nurikk** [comment]
Thanks, fixed in latest commit
