### ISSUE TITLE
OTA  showing only reaming time variable when update

### ISSUE THREAD

**Issue by shirou93** [nurikk/z2m-frontend#575]
![image](https://user-images.githubusercontent.com/59237288/121137733-41f0f900-c837-11eb-8f3e-6d5a8b1f02fa.png)

front  0.4.16

**Comment by sym0nd0** [comment]
Also seeing this behaviour in 0.4.16.

![image](https://user-images.githubusercontent.com/55590428/121926870-513fdd00-cd36-11eb-8f16-1d544d349e79.png)

**Comment by nurikk** [comment]
Fixed quite a while ago...
