### ISSUE TITLE
Devices won't load (in front end) when MQTT broker can not be found

### ISSUE THREAD

**Issue by m-s-e** [nurikk/z2m-frontend#589]
Zigbee2MQTT version: 1.19.1 commit: 9bd46932
Coordinator type: zStack3x0
Coordinator revision: 20210120
Frontend version: 0.4.16

I use an MQTT broker on another Pi. the other day it died. I discovered that the frontend doesn't show any devices without a valid MQTT broker. Nothing displays in the front end, other than the menu system. No Logs. No Map.
You just get this error displayed in the frontend webpage: 

> Loading devices takes too long time. Consider reading documentation

As soon as i repaired the MQTT broker, the front end worked as expected.

**Comment by nurikk** [comment]
Hi, Zigbee2*MQTT* is tightly coupled with mqtt, internally it works as message bus. Currently it isn't possible to make it work without heavy refactoring. 
Maybe @Koenkk has plans for refactoring?))

**Comment by m-s-e** [comment]
that's what i figured, so maybe the documentation That you get the link for) could say that the front end doesn't work properly without a working connection to a functioning MQTT broker?
in the Z2M log that you can see via SSH, it does report that Z2M can't find the MQTT broker. could you use this error to give feedback on the frontend?

**Comment by Koenkk** [comment]
@m-s-e this should be fixed now, can you confirm?
