### ISSUE TITLE
Feature Request: Improve Add Device Dropdown

### ISSUE THREAD

**Issue by swissjon** [nurikk/z2m-frontend#590]
## Is your feature request related to a problem? Please describe
When adding devices to a group:
If have many devices, it is hard to find the device you are looking for in the dropdown 'Select Device'. They don't seem to be sorted.

## Describe the solution you'd like
1. Sort the devices alphabetically in the dropdown.
and/or
2. A search bar to find the device you want to add.

**Comment by nurikk** [comment]
Done -> Sort the devices alphabetically in the dropdown.
