### ISSUE TITLE
Feature Request: Dashboard Tab - Sort Alphabetically and Search Box 

### ISSUE THREAD

**Issue by swissjon** [nurikk/z2m-frontend#591]
## Is your feature request related to a problem? Please describe
Difficult to find the device you are looking for in the dashboard tab.

## Describe the solution you'd like
1. Sort the devices alphabetically
and/or
2. Add a search/filter text box at the top similar to the devices tab

Thanks.

**Comment by nurikk** [comment]
Done -> Sort the devices alphabetically
