### ISSUE TITLE
Refused to Connect - docker doesn't open port in net=host mode

### ISSUE THREAD

**Issue by smathev** [nurikk/z2m-frontend#592]
I have two different rpi's. Both running Zigbee2mqtt as routers to connect to my HomeAssistant-installation on a SuperMicro Server.

All this to say; on the one RPI I can easily connect to the Z2M-frontend and manipulate the devices connected to that RPI. However, on the other RPI, with the exact same installation and running the same os, the same docker-image, etc. it doesn't open any ports.

The command/file I use to run zigbee2mqtt-docker on both machines is as follows:
docker run -v /home/zigbee/.docker/configs/zigbee2mqtt/data:/app/data --net=host --device=/dev/ttyACM0 -e TZ=Europe/Copenhagen -v /run/udev:/run/udev:ro --privileged=true --name=zigbee2mqtt koenkk/zigbee2mqtt

My configuration-file for both machines:
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.88.250:1883'
  user: (specific user pr. RPI)
  password: (Specific passwork pr. RPI)
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
  host: 0.0.0.0
  auth_token: (Specific token pr. RPI)

But, no matter what I do - nothing happens on one of the RPIs.

I mean, it starts zigbee2mqtt fine, it connects to the MQTT-broker. But, it refuses to open a port.

On the working RPI, when I check netstat -nlp I get:
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
(among other listening-ports)
on the non-working RPI, when I check netstat -nlp I don't get any 8080 port that's open.

Any ideas or things I could do to troubleshoot this issue?

I'm not getting any errors during the start nor running of Zigbee2Mqtt - the only issue is - I can't reach the frontend to manipulate devices, etc.

Thanks in advance for any help!

**Comment by nurikk** [comment]
Hi, you should add `-p 8080:8080` parameter into your docker run arguments lists

https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose

**Comment by smathev** [comment]
Hi @nurikk .
Thanks for getting back to me.

Comments:
1. --net=host works on one RPI, but not the other.
2. I've already tried -p 8080:8080
3. --net=host and -p 8080:8080 wouldn't work together, as one tells the docker to use the hosts network (net=host) and not use an internal network, and the other tells it to expose the containers internal network to the hosts network (-p 8080:8080). 

At least that's what I've read and been told.

In summation, neither --net=host nor -p 8080:8080 works on one RPI, despite working on the other. And, the issue persists on the one RPI.

Any other ideas?

**Comment by nurikk** [comment]
Try changing port number, maybe other processes are using 8080, why don't use get rid of host networking and stick to `-p`?

**Comment by nurikk** [comment]
btw try to play around with `host: 0.0.0.0` since you're using host networking, maybe changing to your host ip would help.

**Comment by smathev** [comment]
@nurikk 

In netstat -nlp nothing is using port 8080.
I've tried 8181 also. 

But, the docker simply isn't opening a port on the host. 

Also tried changing host to my specific IP in configuration (frontend:) but still, nothing.

It's weird. I have it working on one RPI. I'm mirroring that setup, but it simply doesn't work.

But, after learning more about zigbee, I'm learning that I can't have two zigbee2mqtt-RPIs in the same house/network - reporting to the same mqtt-broker. So, in that regard it's a non issue, since I'm gonna have to repeat/router my way all the way through the house :/

**Comment by smathev** [comment]
Ah, might have been too quick... might just need two topics, to have 2 coordinators :)

So, the issue is still relevant :)

Sorry.

**Comment by nurikk** [comment]
I would recommend you to raise issue in main Zigbee2MQTT repo, there you might find more people to help with Docker

**Comment by smathev** [comment]
Ok, so your estimation is that it's a docker-issue, and not a frontend issue? :)
