### ISSUE TITLE
Got error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vladi1234** [nurikk/z2m-frontend#597]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

**Current url**: http://192.168.178.48:1890/#/device/0xcc86ecfffeb524ca/exposes
**Previous url**: http://192.168.178.48:1890/

**Error type**: TypeError
**Error message**: Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Zt (http://192.168.178.48:1890/main.aad233569289c685a2fe.js:1:49615)
    at ra (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1060595)
    at Us (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1112800)
    at El (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1100007)
    at _l (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099935)
    at Sl (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099798)
    at fl (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1096785)
    at http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046493
    at t.unstable_runWithPriority (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1156698)
    at Ui (http://192.168.178.48:1890/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046270)

------------------------------------------------------------------------------
This problem has existed since yesterday after the update.

![Bildschirmfoto vom 2021-06-25 12-53-03](https://user-images.githubusercontent.com/45510877/123414967-db006d80-d5b4-11eb-891b-f5953cbf2338.png)
![Bildschirmfoto vom 2021-06-25 11-56-46](https://user-images.githubusercontent.com/45510877/123415058-fff4e080-d5b4-11eb-9ffb-c4099d510856.png)

This problem has existed since yesterday after the update.
if I change 'exposes.enum' to 'exposes.text' then it's fine again. However, it is not recommended to use text in this case, according to Koenkk. Before the update was not like that.

**Comment by nurikk** [comment]
Hi, your exposes definition is incorrect, try use composite feature


`exposes.composite('programming_mode', 'programming_mode')
    .withFeature(exposes.text('monday', ea.STATE_SET)
    .withFeature(exposes.text('tuesday', ea.STATE_SET)
    //keep going
`

**Comment by vladi1234** [comment]
```
           exposes.composite('programming_mode', 'programming_mode')
                .withFeature(exposes.text('weekday', ea.STATE_SET))
                .withFeature(exposes.text('saturday', ea.STATE_SET))
                .withFeature(exposes.text('sunday', ea.STATE_SET))
```

That is a good idea, optically looks better, but it is too complicated to get all values in. I may have to change 'fromZigbee.js' and 'toZigbee.js'. Is it too difficult for me, or will you help me?



![Bildschirmfoto vom 2021-06-25 16-36-13](https://user-images.githubusercontent.com/45510877/123440874-8cae9700-d5d3-11eb-9cf8-dc2cb53c3c22.png)

**Comment by nurikk** [comment]
I can't do this for you, but I can help you with advice. Don't hesitate to raise a PR in https://github.com/Koenkk/zigbee-herdsman-converters

**Comment by vladi1234** [comment]
Why did this happen after the last update? Works fine before the update.

**Comment by nurikk** [comment]
Development lifecycle, sometimes we fix bugs, sometime we introduce new bugs :)
