### ISSUE TITLE
Order devices in dashboard

### ISSUE THREAD

**Issue by svrooij** [nurikk/z2m-frontend#603]
In the device list there is a way to sort devices based on name/batterylevel/vendor. It would be really nice if the dasboard where you can control them also **Sorts by name** or even better have the option to choose what to use for sorting.

Is that something that you think you'll be accepting a PR for?

**Comment by nurikk** [comment]
Hi, currently dashboard devices are sorted by friendly name. If you’re keen to implement dynamic sorting - always welcome. And it would be nice to refactor devices table sorting logic and use it in dashboard and devices pages

**Comment by svrooij** [comment]
I've installed version 1.19.1 of zigbee2mqtt and I don't see them sorted at the dashboard. Is this added lately and just not available yet in my frontend?

**Comment by nurikk** [comment]
> I've installed version 1.19.1 of zigbee2mqtt and I don't see them sorted at the dashboard. Is this added lately and just not available yet in my frontend?

Everything is in [dev branch](https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by svrooij** [comment]
Ok, I figured out that the ordering is implemented in version `0.4.22` with this commit https://github.com/nurikk/z2m-frontend/commit/5dfe8d0ca89a4926cf8da75319c69a2481741fee#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

And I'm running the production version with frontend 0.4.16 version so it isn't implemented there yet.
