### ISSUE TITLE
Cluster selector seems broken on reporting tab

### ISSUE THREAD

**Issue by sjorge** [nurikk/z2m-frontend#605]
<img width="570" alt="Screen Shot 2021-07-03 at 16 11 06" src="https://user-images.githubusercontent.com/379665/124356951-55feff00-dc19-11eb-8c96-d6e964685e4f.png">

This happens for all my devices with reporting configured.

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by nurikk** [comment]
Yep, just fixed in `0.4.31`
