### ISSUE TITLE
can not access frontend from docker

### ISSUE THREAD

**Issue by AutomanRJJ** [nurikk/z2m-frontend#653]
I am trying to set this up on something that is not going to eradicate access to usb devices (Synology DSM 7) by setting up an older workstation as a Fedora Linux with Docker running on it to house my Zigbee and Z-Wave interface.

I think its up and working but I can't get to the freaking frontend.  I have tried every conceivable configuration I can think of to get to the frontend.
I am running it inside of a docker running on Fedora linux on ip 10.0.0.70.  I know I can access other docker instances because I have portainer up and running in the docker system.
I have tried the default bridge network like portainer is on, and forwarding port 8080:8080.  I have even tried switching over to use the host network.  Firewall is enabled for port 8080 allowed through.
I have MQTT up and running in my Synology Docker instance that runs at 10.0.0.71 and that's where I have it configured to point to.

No matter what I do, I can not access the frontend from my windows system (currently IP of windows PC 10.0.0.30)  by going to http://10.0.0.70:8080 to try and get to the front end.  I get ERR_CONNECTION_REFUSED from Edge and Chrome.

Docker Image created 7/1/2021, version 1.20.0 (commit #41b67fd)
**Log in debug mode;**

Using '/app/data' as data directory
Zigbee2MQTT:debug 2021-07-09 15:05:21: Loaded state from file /app/data/state.json
Zigbee2MQTT:info  2021-07-09 15:05:21: Logging to console and directory: '/app/data/log/2021-07-09.15-05-20' filename: log.txt
Zigbee2MQTT:debug 2021-07-09 15:05:21: Removing old log directory '/app/data/log/2021-07-09.13-58-07'
Zigbee2MQTT:info  2021-07-09 15:05:21: Starting Zigbee2MQTT version 1.20.0 (commit #41b67fd)
Zigbee2MQTT:info  2021-07-09 15:05:21: Starting zigbee-herdsman (0.13.117)
Zigbee2MQTT:debug 2021-07-09 15:05:21: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/ttyUSB1"}}'
Zigbee2MQTT:debug 2021-07-09 15:10:21: Saving state to file /app/data/state.json
Zigbee2MQTT:debug 2021-07-09 15:15:21: Saving state to file /app/data/state.json
Zigbee2MQTT:debug 2021-07-09 15:20:21: Saving state to file /app/data/state.json
Zigbee2MQTT:debug 2021-07-09 15:25:21: Saving state to file /app/data/state.json
Zigbee2MQTT:debug 2021-07-09 15:30:21: Saving state to file /app/data/state.json

**configuration.yaml is as follows;**

# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://10.0.0.71:1883'
  # MQTT server authentication, uncomment if required:
  user: zigbee2mqtt
  password: ***NOYOB*****

# Serial settings
serial:
  port: /dev/ttyUSB1
  adapter: 'ezsp'

frontend:
  port: 8080
  host: 0.0.0.0

advanced:
  log_level: debug
  log_output:
    - console
    - file

  network_key:
    - 167
    - 246
    - 114
    - 207
    - 122
    - 43
    - 153
    - 33
    - 32
    - 22
    - 104
    - 57
    - 62
    - 97
    - 251
    - 100

**Comment by nurikk** [comment]
Hi, can you try another port? And make sure that tabs indents are correct.
Attaching complete startup log as a file  also will help

**Comment by AutomanRJJ** [comment]
Switched to 8090 on host network, firewall configured to enable that port, no change.

Here's the configuration.yaml, the last log and the state.json

I am using the HUSBZB-1 controller... somewhere in here I read to use that configure for adapter: ezsp

I am wondering if that might have it hung, not even initializing.  It doesn't even log into MQTT.

[Config_Logs.zip](https://github.com/nurikk/z2m-frontend/files/6795944/Config_Logs.zip)

**Comment by nurikk** [comment]
Your logs tells that z2m can't connect to mqtt, can you fix this first and then try again? And logs aren't complete

**Comment by AutomanRJJ** [comment]
ok, so thats the logs from Koenkk/zigbee2mqtt docker.  Maybe I need to take this conversation there instead.
