### ISSUE TITLE
device picture MFKZQ01LM

### ISSUE THREAD

**Issue by xrust83** [nurikk/z2m-frontend#688]
Please replace the picture of the xiaomi device MFKZQ01LM. it is not contrasting and poorly visible
![1](https://user-images.githubusercontent.com/58448955/126467034-64265c74-f50b-4127-af28-5f1178964b1a.jpg)
![2](https://user-images.githubusercontent.com/58448955/126467055-ec57db81-7db7-4a9d-affb-1053bc22bc90.jpg)
![3](https://user-images.githubusercontent.com/58448955/126467059-62589b7f-a796-412a-9356-1d70400d0753.jpg)
you can try these
![9651315-1](https://user-images.githubusercontent.com/58448955/126467181-2730cf4b-59c4-47b5-9c47-0987bc42f6ef.jpg)
![xiaomi-mi-smart-home-cube](https://user-images.githubusercontent.com/58448955/126467352-fca70284-eeae-448b-a4d2-6b0c5d10a66a.jpg)
Thank you

**Comment by nurikk** [comment]
Hello, frontend pull images from http://zigbee2mqtt.io/ website, kindly raise a PR in it's repository.

https://github.com/Koenkk/zigbee2mqtt.io/tree/master/docs/images/devices

**Comment by xrust83** [comment]
Thank you
