### ISSUE TITLE
Got error: Cannot read property 'ieee_address' of undefined

### ISSUE THREAD

**Issue by radokk** [nurikk/z2m-frontend#693]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

I wanted to open groups tab since 2 of my ikea bulb are not in list anymore and I can't control them. I was away for 2 weeks, just noticed I can't control them anymore. Since controllers are still in device list, I wanted to check if groups still exists. 

[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/6872918/initialState.json.zip)

![image](https://user-images.githubusercontent.com/60854491/126878137-641b2f75-35d3-4145-a6ee-8d4caf89f2b8.png)

**Current url**: http://192.168.1.30:8080/#/groups
**Previous url**: 

**Error type**: TypeError
**Error message**: Cannot read property 'ieee_address' of undefined

TypeError: Cannot read property 'ieee_address' of undefined
    at ma (http://192.168.1.30:8080/main.125c9bd8fa26692dd8b6.js:1:83823)
    at ra (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1060595)
    at Us (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1112800)
    at El (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1100007)
    at _l (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099935)
    at Sl (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099798)
    at fl (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1096785)
    at http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046493
    at t.unstable_runWithPriority (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1156698)
    at Ui (http://192.168.1.30:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046270)

**Comment by nurikk** [comment]
Hello, can you please attach your data/databases.db file?

After attaching database.db file try to switch to the latest dev branch, I’ve already made a workaround for this issue and @Koenkk tries to fix source of this issue

**Comment by radokk** [comment]
Hello, here is requested file. 
[database.zip](https://github.com/nurikk/z2m-frontend/files/6877910/database.zip)

I already fixed it. I rebooted z2m, then had to reset both bulbs (6x on/off). Once I permitted to join new devices, both bubls were discovered with it's name. I just had tu add those bulbs to groups.  It was kitchenbulb & bedroombulb. 

Hope this helps. I won't switch to dev, since I'm kind of newbie in z2m and related stuff. It's working and I don't want to change anything :)

**Comment by Koenkk** [comment]
@radokk is this the database.db after or before fixing the issue?

@nurikk do you know of what getting the `ieee_address` fails exactly?

**Comment by radokk** [comment]
That was version after fix. I restored 2 previous versions from my backup, before I arrived home a fixed that:

23.7.2021
[database.zip](https://github.com/nurikk/z2m-frontend/files/6888260/database.zip)

Older version 20.07.2021:
[database 20_07_2021.zip](https://github.com/nurikk/z2m-frontend/files/6888293/database.20_07_2021.zip)

I hope that can help.

**Comment by nurikk** [comment]
@Koenkk two devices are missing, but thery are in the groups


0x90fd9ffffe02c5f2 (bedroom_gr#4)
0x90fd9ffffeec31b1 (kitchen_gr#1)

**Comment by Koenkk** [comment]
@nurikk thanks, issue should be fixed now in the latest-dev.

**Comment by nurikk** [comment]
Thanks! Closing
