### ISSUE TITLE
Option box is rendered outside page

### ISSUE THREAD

**Issue by Koenkk** [nurikk/z2m-frontend#7]
When clicking the "gear" icon for a device the option menu is render outside the page:

![image](https://user-images.githubusercontent.com/2892853/92642455-7f444c80-f2e0-11ea-9954-369495ba6958.png)

When this menu is open it's possible to scroll right, revealing a white bar:

![image](https://user-images.githubusercontent.com/2892853/92642568-b0bd1800-f2e0-11ea-952b-d6bfae02a51a.png)

Browser: Chrome 85.0.4183.83 on MacOS

**Comment by nurikk** [comment]
Oh, yes. I was dreaming to get rid of this drop-down button. It cost me 100kb of junk js dependencies. Say buy to the dropdown, and sat hello to the 4 buttons panel
<img width="210" alt="Screenshot 2020-09-10 at 22 01 07" src="https://user-images.githubusercontent.com/1525421/92741698-766f7b80-f3b1-11ea-8206-c31fd4a9e1a3.png">
