### ISSUE TITLE
[Bug]: Range Slider and Input min, max and step issue

### ISSUE THREAD

**Issue by robertalexa** [nurikk/z2m-frontend#718]
### What happened?

In my example I will use the occupied_heating_setpoint to explain the behaviour.

For my testing range:
![image](https://user-images.githubusercontent.com/9019306/128333019-462c8ce8-8ac5-4b01-be3a-1d690afb0495.png)

![image](https://user-images.githubusercontent.com/9019306/128333325-34e7a2b7-535f-446a-9436-fba546379f22.png)

You would expect the Slider and the Input next to it to allow only the allowed values, yet that does not happen. There are 2 separate issues at play.

Slider.
The min and max values are set on the input range but not the step. Which means the step defaults to 1 value.
![image](https://user-images.githubusercontent.com/9019306/128333256-a31e618e-8fbd-4978-b110-ce2ea23791a0.png)

Input.
Min, max and step are completely missing from the input. That means the user can technically set any value.
![image](https://user-images.githubusercontent.com/9019306/128333603-0127128f-ccf3-434e-87db-96c82ed82bd8.png)

For my testing I am using Chrome, but because there are html attributes that are missing it will be happening on all browsers.

At the minute I am involved in some work with improving some devices, so I am left with very little time to try and look into this. If I finish my stuff and this was still not looked at, I will try to put a PR in. But if you have time before me to look into it that would be greatly appreciated.

Thanks

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### initialState.zip

I will not attach initialState.zip

**Comment by nurikk** [comment]
Fixed, thanks
