### ISSUE TITLE
Device missng on dashboard

### ISSUE THREAD

**Issue by kristofejro** [nurikk/z2m-frontend#723]
Hello,

One of my zigbee devices is not present on web dashboard.
It is present in Devices section (tab) but no on Dashboard section (tab)

![Devices](https://user-images.githubusercontent.com/15168170/128640610-de0bf7a0-153a-4ef1-ab2e-674fa30a10f6.JPG)
![Dashboard](https://user-images.githubusercontent.com/15168170/128640634-16c02731-17de-4073-b9d2-bbabc5bea185.JPG)

Maybe its not an issue with frontend but I need to ask at some place as a starter.
What can be the issue and how to solve it?

I am on Raspberry Pi 4 with:

- Zigbee2MQTT version - 1.21.0 commit: 70891eec
- Coordinator type - zStack3x0
- Coordinator revision - 20210708
- Frontend version - 0.5.18

Zigbe dongle is Elektrolama zzh (CC2652R)

I looks like this on Firefox and on Chrome

Thanks,
Kris

**Comment by nurikk** [comment]
Devices like switched aren’t displayed on the dashboard, since they don't have any meaningful features for display. Only sensors and controllable devices are shown on the dashboard

**Comment by kristofejro** [comment]
Thanks mate. It is information I was looking for.
