### ISSUE TITLE
[Bug]: New translate page with split error on "."

### ISSUE THREAD

**Issue by NebzHB** [nurikk/z2m-frontend#736]
### What happened?

![image](https://user-images.githubusercontent.com/28622481/129033928-87030a14-8f00-4471-ac7f-bfb6ffd76e7c.png)
example with "e.g."

### What browsers are you seeing the problem on?

Firefox

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Hi, this is fixed in latest dev branch

**Comment by NebzHB** [comment]
Ok thx !
