### ISSUE TITLE
iOS icon for homescreen

### ISSUE THREAD

**Issue by T-IOOO** [nurikk/z2m-frontend#741]
**Is your feature request related to a problem? Please describe.
Not really, but when adding a homescreen shortcut the icon will look like a screendump

**Describe the solution you'd like**
A fresh and well designed zigbee2mqtt icon!

**Describe alternatives you've considered**
There are workarounds for ios. For example "callmeicons" is a good alternative right now but not the solution

**Additional context**

![image](https://user-images.githubusercontent.com/59575587/129235176-de21d8da-2385-432d-ae72-abc53ce2544b.jpeg)

**Comment by nurikk** [comment]
Hi, can you share source image? 150x150?

**Comment by T-IOOO** [comment]
> Hi, can you share source image? 150x150?

Here you go!

![z2m-150x150](https://user-images.githubusercontent.com/59575587/129518037-38b68ea3-ae85-4692-8806-65350fc94e9a.png)

**Comment by nurikk** [comment]
done
