### ISSUE TITLE
[Bug]: Mistype in OTA screen

### ISSUE THREAD

**Issue by Masterz69** [nurikk/z2m-frontend#743]
### What happened?

![image](https://user-images.githubusercontent.com/15225823/129272440-a6c93cb9-0c20-458e-a55f-e305ed702a4a.png)

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
fixed, thanks
