### ISSUE TITLE
Device disappeared from the UI after rejoining

### ISSUE THREAD

**Issue by rindlerblabla** [nurikk/z2m-frontend#746]
### What happened?

One of my Frient smoke detectors left and rejoined the network this morning. Obviously those Frient/Develco devices behave like this when they loose contact with the network (?). After that it keep reporting to Home Assistant, it's still in the configuration, database and the state files, but is missing in the UI.

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
warn  2021-08-15 06:00:57: Device 'Brandvarnare ******' left the network
 6882 
 
info  2021-08-15 06:00:57: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Brandvarnare ******","ieee_address":"0x0015bc00310099f7"},"type":"device_leave"}'
 6883 
 
info  2021-08-15 06:00:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x0015bc00310099f7"},"type":"device_removed"}'
 6884 
 
debug 2021-08-15 06:00:57: Received Zigbee message from 'Brandvarnare ******', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 35 with groupID 0
 6885 
 
debug 2021-08-15 06:00:57: Device 'Brandvarnare ******' announced itself
```

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by rindlerblabla** [comment]
From state.json

 `"0x0015bc00310099f7": {
        "smoke": false,
        "battery_low": false,
        "supervision_reports": true,
        "restore_reports": true,
        "test": false,
        "temperature": 20.43,
        "voltage": 3000,
        "battery": 100
    }`

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by rindlerblabla** [comment]
@nurikk Didn't manage to attach it here. Did you get it by email?

**Comment by SargonofAssyria** [comment]
I have something similar. A device is visible in the network map, but not in the Device list.
The device is working normally from Domoticz.

**Comment by rindlerblabla** [comment]
True, same here. The device is still visible in the map as well.

**Comment by nurikk** [comment]
@Koenkk need your help here

**Comment by Koenkk** [comment]
@rindlerblabla could you provide the debug log starting in the working situation until it leaves and is not visible anymore in the frontend?

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by rindlerblabla** [comment]
@Koenkk The debug log from the moment when it left the frontend is overwritten, and I haven't repaired it since it is still working. However it went missing again yesterday evening. And the log from that moment looks like this. 

```
debug 2021-08-16 22:55:00: Received Zigbee message from 'Brandvarnare ******', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 35 with groupID 0
info  2021-08-16 22:55:00: MQTT publish: topic 'zigbee2mqtt/Brandvarnare ******', payload '{"battery":100,"battery_low":false,"last_seen":"2021-08-16T20:55:00.456Z","linkquality":42,"max_duration":null,"restore_reports":true,"smoke":false,"supervision_reports":true,"temperature":21.56,"test":false,"update":{"state":"idle"},"update_available":false,"voltage":3000}'
warn  2021-08-16 22:55:15: Device 'Brandvarnare ******' left the network
info  2021-08-16 22:55:15: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Brandvarnare ******","ieee_address":"0x0015bc00310099f7"},"type":"device_leave"}'
info  2021-08-16 22:55:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x0015bc00310099f7"},"type":"device_removed"}'
debug 2021-08-16 22:55:16: Received Zigbee message from 'Brandvarnare ******', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 35 with groupID 0
debug 2021-08-16 22:55:16: Device 'Brandvarnare ******' announced itself
info  2021-08-16 22:55:16: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Brandvarnare ******","ieee_address":"0x0015bc00310099f7"},"type":"device_announce"}'
info  2021-08-16 22:55:16: MQTT publish: topic 'zigbee2mqtt/Brandvarnare ******', payload '{"battery":null,"battery_low":false,"last_seen":"2021-08-16T20:55:16.270Z","linkquality":42,"max_duration":null,"restore_reports":true,"smoke":false,"supervision_reports":true,"temperature":null,"test":false}'
info  2021-08-16 22:55:16: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Brandvarnare ******"},"type":"device_announced"}'
info  2021-08-16 22:55:16: MQTT publish: topic 'zigbee2mqtt/Brandvarnare ******', payload '{"battery":null,"battery_low":false,"last_seen":"2021-08-16T20:55:16.270Z","linkquality":42,"max_duration":null,"restore_reports":true,"smoke":false,"supervision_reports":true,"temperature":null,"test":false}'
```

**Comment by rindlerblabla** [comment]
More info from the manual about the keeping alive function, https://www.develcoproducts.com/media/1742/smszb-120-technical-manual-smoke-alarm.pdf

> 6.2 Normal – Keep alive
The device is sending a “keep alive” message to the PAN coordinator every 15 minute to verify that the device is still connected to the network.

> 6.2.1 Network lost
> If no “keep alive” responses are received 5 times in a row (Worst case 1h15m), the devices will start scanning as specified in the table below.
> When the device is in scan mode the LED will flash once every second until it re-joins the network.
> According to the ZigBee specification TX is NOT allowed to be enabled all the time and a TX silent period has to be defined.

**Comment by Koenkk** [comment]
I'm not sure what they mean with "keep alive message", this is not something standard in Zigbee. Could you take a sniff of 20 minutes? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by rindlerblabla** [comment]
Unfortunately I don't have another stick than my production zzh. Will see if I can include @thestigh who has developed support for those Develco/Frient devices in this thread.

**Comment by TheStigh** [comment]
Hi,

Never seen this behavior, though I only use the "original" Develco SMSZB-120 (do have 7 installed).
Just to be sure - when you say disappeared from the UI, do you mean from the UI device list? 
What firmware version are you running (latest are 4.0.1), and what kind of coordinator adapter are you using?

The keep a live are part of iasZone and are not a "zigbee function".

Try to switch to Dev branch and see if the behavior are stable. I've done some updates in July and August of the SMSZB-120, like added `iasZone`, `iasWD`, `tz.warning_simple`, `current_firmware` attribute (easy triggering: `{"alarm": "START"}` / `{"alarm": "OFF"}`

**Comment by rindlerblabla** [comment]
Yes, I mean the UI device list. But today it is actually back. No idea why it was missing for days, and how it came back. Z2m haven't been restarted since the issue appeared.

Am on dev branch but haven't updated since latest PR regarding those Develco devices, but will do so. Think I am now closing this issue since the device reappeared. Will open it up again if it happen again. Do also have several Develco/Frient smoke/heat detectors and this is the only one which has gone missing.

**Comment by SargonofAssyria** [comment]
Still this is not solved. I had to change battery on this device: https://www.zigbee2mqtt.io/devices/JTYJ-GD-01LM_BW.html
It did not work properly after that, so I excluded the device. That went fine instantly.
I had a lot of trouble including it again. Only succeeded very near the controller (50cm)
This device sent normal message to my mqttserver and also responds to a 
`mosquitto_pub -h 127.0.0.1 -t zigbee2mqtt/ZolderSmoke/set -m "{\"sensitivity\": \"high\"}"`
because that value was null is is now 'high' So it seems that device is working properly.
It is visible with good linkquality in the map in zigbee2mqtt gui, but NOT visible in the device list of the gui.
When I press the button on the device normal mqtt message are send.
Also a serious side effect is that those messages are not processed anymore by the zigbee2mqtt plugin of stas-demydiuk
So no updates in Domoticz
These are the messages send by the device when I press the button (send 4 times)
`info  2021-08-19 13:39:58: MQTT publish: topic 'zigbee2mqtt/ZolderSmoke', payload '{"ac_status":false,"battery":100,"battery_low":false,"last_seen":"2021-08-19T13:39:58+02:00","linkquality":96,"restore_reports":false,"sensitivity":"high","smoke":false,"smoke_density":31,"supervision_reports":false,"tamper":false,"test":false,"trouble":false,"voltage":3085}'
info  2021-08-19 13:39:58: MQTT publish: topic 'zigbee2mqtt/ZolderSmoke', payload '{"ac_status":false,"battery":100,"battery_low":false,"last_seen":"2021-08-19T13:39:58+02:00","linkquality":102,"restore_reports":false,"sensitivity":"high","smoke":false,"smoke_density":31,"supervision_reports":false,"tamper":false,"test":false,"trouble":false,"voltage":3085}'
info  2021-08-19 13:39:58: MQTT publish: topic 'zigbee2mqtt/ZolderSmoke', payload '{"ac_status":false,"battery":100,"battery_low":false,"last_seen":"2021-08-19T13:39:58+02:00","linkquality":96,"restore_reports":false,"sensitivity":"high","smoke":false,"smoke_density":31,"supervision_reports":false,"tamper":false,"test":false,"trouble":false,"voltage":3085}'
info  2021-08-19 13:39:58: MQTT publish: topic 'zigbee2mqtt/ZolderSmoke', payload '{"ac_status":false,"battery":100,"battery_low":false,"last_seen":"2021-08-19T13:39:58+02:00","linkquality":99,"restore_reports":false,"sensitivity":"high","smoke":false,"smoke_density":31,"supervision_reports":false,"tamper":false,"test":false,"trouble":false,"voltage":3085}'
`

**Comment by SargonofAssyria** [comment]
Found out that the device is visible in the list of the plugin in Domoticz, and has a 'newer' last seen in that list.

**Comment by SargonofAssyria** [comment]
After 1 day of waiting if the devices does show up in the GUI ( it did not) I pulled the latest commit and ALL device are present in the GUI. The restart of the zigbee2mqtt service did the trick. Perhaps there should be a 'Refresh' button in the GUI, if the reason cannot be found.
B.t.w. "Last seen" is now updated in Domoticz too.

**Comment by z-x-f** [comment]
I have the same situation. After I rejoin the device, it does not appear in the UI, but the device reports the status in debug. If I restart z2m, it will appear in the UI immediately.

**Comment by Koenkk** [comment]
@z-x-f can you provide the debug logging of this?

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by z-x-f** [comment]
I just deleted a device and rejoin it, nothing happened in the UI, but the device has been added normally.
<pre><code>
info  2021-08-21 21:03:22: Removing device 'one_key_test' (block: false, force: false)
debug 2021-08-21 21:03:25: Clearing Home Assistant discovery topic for 'one_key_test'
info  2021-08-21 21:03:25: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/click/config', payload 'null'
info  2021-08-21 21:03:25: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/battery/config', payload 'null'
info  2021-08-21 21:03:25: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/action/config', payload 'null'
info  2021-08-21 21:03:25: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/voltage/config', payload 'null'
info  2021-08-21 21:03:25: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/linkquality/config', payload 'null'
info  2021-08-21 21:03:25: MQTT publish: topic 'zigbee2mqtt/one_key_test', payload ''
info  2021-08-21 21:03:25: Successfully removed device 'one_key_test' (block: false, force: false)
info  2021-08-21 21:03:25: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/remove', payload '{"data":{"block":false,"force":false,"id":"one_key_smallbedroom_test"},"status":"ok","transaction":"lmgn5-4"}'
debug 2021-08-21 21:03:25: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/click/config' with data ''
debug 2021-08-21 21:03:25: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/battery/config' with data ''
debug 2021-08-21 21:03:25: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/action/config' with data ''
debug 2021-08-21 21:03:25: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/voltage/config' with data ''
debug 2021-08-21 21:03:25: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/linkquality/config' with data ''
debug 2021-08-21 21:03:49: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"lmgn5-5","value":true}'
info  2021-08-21 21:03:49: Zigbee: allowing new devices to join.
info  2021-08-21 21:03:50: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"lmgn5-5"}'
debug 2021-08-21 21:03:58: Received Zigbee message from '0x00158d00010f1cb3', type 'attributeReport', cluster 'genBasic', data '{"modelId":"lumi.sensor_switch"}' from endpoint 1 with groupID 0
info  2021-08-21 21:03:58: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/click/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"icon":"mdi:toggle-switch","name":"0x00158d00010f1cb3 click","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_click_zigbee2mqtt","value_template":"{{ value_json.click }}"}'
info  2021-08-21 21:03:58: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"device_class":"battery","name":"0x00158d00010f1cb3 battery","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
info  2021-08-21 21:03:58: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"0x00158d00010f1cb3 action","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
info  2021-08-21 21:03:58: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/voltage/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"device_class":"voltage","enabled_by_default":false,"name":"0x00158d00010f1cb3 voltage","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
info  2021-08-21 21:03:58: MQTT publish: topic 'homeassistant/sensor/0x00158d00010f1cb3/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"enabled_by_default":false,"icon":"mdi:signal","name":"0x00158d00010f1cb3 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2021-08-21 21:03:58: Received Zigbee message from '0x00158d00010f1cb3', type 'attributeReport', cluster 'genBasic', data '{"appVersion":10}' from endpoint 1 with groupID 0
debug 2021-08-21 21:03:58: Received Zigbee message from '0x00158d00010f1cb3', type 'attributeReport', cluster 'genBasic', data '{"65282":[{"elmType":16,"elmVal":1},{"elmType":33,"elmVal":3042},{"elmType":33,"elmVal":424},{"elmType":36,"elmVal":[0,0]},{"elmType":33,"elmVal":201},{"elmType":32,"elmVal":86}]}' from endpoint 1 with groupID 0
debug 2021-08-21 21:03:58: Device '0x00158d00010f1cb3' announced itself
info  2021-08-21 21:03:58: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d00010f1cb3","ieee_address":"0x00158d00010f1cb3"},"type":"device_announce"}'
info  2021-08-21 21:03:58: MQTT publish: topic 'zigbee2mqtt/0x00158d00010f1cb3', payload '{"action":null,"battery":100,"linkquality":51,"voltage":3042}'
info  2021-08-21 21:03:58: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x00158d00010f1cb3"},"type":"device_announced"}'
debug 2021-08-21 21:03:58: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/click/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"icon":"mdi:toggle-switch","name":"0x00158d00010f1cb3 click","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_click_zigbee2mqtt","value_template":"{{ value_json.click }}"}'
debug 2021-08-21 21:03:58: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"device_class":"battery","name":"0x00158d00010f1cb3 battery","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
debug 2021-08-21 21:03:58: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/action/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"0x00158d00010f1cb3 action","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
debug 2021-08-21 21:03:58: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/voltage/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"device_class":"voltage","enabled_by_default":false,"name":"0x00158d00010f1cb3 voltage","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
debug 2021-08-21 21:03:58: Received MQTT message on 'homeassistant/sensor/0x00158d00010f1cb3/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00010f1cb3"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"0x00158d00010f1cb3","sw_version":"Zigbee2MQTT 1.21.0-dev"},"enabled_by_default":false,"icon":"mdi:signal","name":"0x00158d00010f1cb3 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d00010f1cb3","unique_id":"0x00158d00010f1cb3_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2021-08-21 21:03:58: Received MQTT message on 'zigbee2mqtt/bridge/config/groups' with data '1629551038066'
debug 2021-08-21 21:03:58: Received MQTT message on 'zigbee2mqtt/bridge/config/devices/get' with data '1629551038066'
info  2021-08-21 21:03:58: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[],"type":"groups"}'
debug 2021-08-21 21:03:58: Received Zigbee message from '0x00158d00010f1cb3', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
info  2021-08-21 21:03:59: MQTT publish: topic 'zigbee2mqtt/0x00158d00010f1cb3', payload '{"action":"hold","battery":100,"linkquality":48,"voltage":3042}'
info  2021-08-21 21:03:59: MQTT publish: topic 'zigbee2mqtt/0x00158d00010f1cb3', payload '{"action":"","battery":100,"linkquality":48,"voltage":3042}'
info  2021-08-21 21:03:59: MQTT publish: topic 'zigbee2mqtt/0x00158d00010f1cb3/action', payload 'hold'
info  2021-08-21 21:03:59: MQTT publish: topic 'zigbee2mqtt/0x00158d00010f1cb3', payload '{"action":null,"battery":100,"click":"long","linkquality":48,"voltage":3042}'
info  2021-08-21 21:03:59: MQTT publish: topic 'zigbee2mqtt/0x00158d00010f1cb3', payload '{"action":null,"battery":100,"click":"","linkquality":48,"voltage":3042}'
info  2021-08-21 21:03:59: MQTT publish: topic 'zigbee2mqtt/0x00158d00010f1cb3/click', payload 'long'
</pre></code>

**Comment by Koenkk** [comment]
Interesting, I think I know why it happens, if you can still reproduce this, can you also provide the herdsman debug logging of this?

**Comment by z-x-f** [comment]
I will try to reproduce the failure and provide herdsman debug logging.

**Comment by z-x-f** [comment]
@Koenkk I can reproduce the problem. When the device ZNCZ11LM is added to my zigbee network, the network becomes strange. The newly added device will not be prompted in the UI and will not appear. When I restart z2m, the new device will appear in the UI.
This is the debug log of herdsman: [herdsman_debug.log](https://github.com/nurikk/z2m-frontend/files/7033430/herdsman_debug.log)
The newly added device is <code>0x00158d000204ad5f</code>

**Comment by Koenkk** [comment]
I found the issue and fixed it, can you confirm?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by z-x-f** [comment]
@Koenkk After updating, adding a new device, the UI only prompts device 0x00158d000204ad5f joined, no other prompts, but it does not appear in the device list, and it does not appear until z2m is restarted. 
I tried to delete ZNCZ11LM, but to no avail, only to re-install, rejoin all devices, and not join ZNCZ11LM to ensure normal.

**Comment by Koenkk** [comment]
@z-x-f did another attempt, can you check again with latest-dev?

**Comment by z-x-f** [comment]
Yeah, it's normal now. Thank you very much.

**Comment by Loic691** [comment]
Hi
I have the same issue with 2 devices when I stopped Z2M.
With air monitor aqara and aqara vibration sensor.
They can join easily the device to the network in pairing mode and they stay online but they disapear from the list when i stoped z2m and relaunched it for different reason.

I must be to pair them again to  got them in the z2m UI.

Must i open a new issue for this ?
