### ISSUE TITLE
Got error: accessing groups page

### ISSUE THREAD

**Issue by stripemsu** [nurikk/z2m-frontend#773]
DESCRIBE HERE WHAT HAPPENED AND WHAT YOU EXPECTED TO HAPPEN

Work with ikea bulbes & switches. Added lamp to the group. Turn lamp on 6 times to reset it. Open 'groups' page and got this error (after lamp connects back groups page opens fine).

**Current url**: http://tinker.home:8080/#/groups
**Previous url**: http://tinker.home:8080/

**Error type**: TypeError
**Error message**: o is undefined
[initialState.json.zip](https://github.com/nurikk/z2m-frontend/files/7029748/initialState.json.zip)

ma@http://tinker.home:8080/main.125c9bd8fa26692dd8b6.js:1:83813
ra@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1060595
Us@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1112800
El@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1100009
_l@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099937
Sl@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1099798
fl@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1096785
Vi/<@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046493
60053/t.unstable_runWithPriority@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1156698
Ui@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046270
Vi@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046440
Wi@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1046373
Le@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1117319
Zt@http://tinker.home:8080/scripts/vendor.a0ef53a74e6d2443acda.js:2:1025079

**Comment by nurikk** [comment]
Hi, can you try to update to the latest dev branch and try again?
