### ISSUE TITLE
Fronted not working on rpi3b+ 

### ISSUE THREAD

**Issue by Altar82** [nurikk/z2m-frontend#785]
hello everyone, I have a problem with the fronted. I installed z2m as per official guide on rpi3b + with raspberry os lite clean.
This is my z2m config:

homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.188.10      <-------   this is ha server
  user: *******
  password: ********
serial:
  port: /dev/ttyAMA0           <---------  I have zigbee pihat
fronted:
  port: 8099
advanced:
  log_level: debug
  channel: 25
  pan_id: 50952
  network_key:
    - 126
    - 147
    - 12
    - 134
    - 245
    - 232
    - 20
    - 36
    - 131
    - 127
    - 51
    - 167
    - 94
    - 244
    - 167
    - 193
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
device_options:
  legacy: false

z2m starts, without errors, this is the log:

pi@raspberrypi:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.21.0-dev start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:debug 2021-08-28 15:24:44: Loaded state from file /opt/zigbee2mqtt/data/state.json
Zigbee2MQTT:info  2021-08-28 15:24:44: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-08-28.15-24-42' filename: log.txt
Zigbee2MQTT:debug 2021-08-28 15:24:44: Removing old log directory '/opt/zigbee2mqtt/data/log/2021-08-27.20-35-21'
Zigbee2MQTT:info  2021-08-28 15:24:45: Starting Zigbee2MQTT version 1.21.0-dev (commit #a9e47450)
Zigbee2MQTT:info  2021-08-28 15:24:45: Starting zigbee-herdsman (0.13.135)
Zigbee2MQTT:debug 2021-08-28 15:24:45: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[25],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":50952},"serialPort":{"path":"/dev/ttyAMA0"}}'
Zigbee2MQTT:info  2021-08-28 15:24:48: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2021-08-28 15:24:48: Coordinator firmware version: '{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20201010,"transportrev":2},"type":"zStack30x"}'
Zigbee2MQTT:debug 2021-08-28 15:24:48: Zigbee network parameters: {"channel":25,"extendedPanID":"0x00124b00042ad5a9","panID":50952}
Zigbee2MQTT:info  2021-08-28 15:24:48: Currently 0 devices are joined:
Zigbee2MQTT:warn  2021-08-28 15:24:48: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2021-08-28 15:24:48: Allowing new devices to join.
Zigbee2MQTT:warn  2021-08-28 15:24:48: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2021-08-28 15:24:48: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2021-08-28 15:24:48: Connecting to MQTT server at mqtt://192.168.188.10
Zigbee2MQTT:debug 2021-08-28 15:24:48: Using MQTT login with username: altar82
Zigbee2MQTT:info  2021-08-28 15:24:48: Connected to MQTT server
Zigbee2MQTT:info  2021-08-28 15:24:48: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'

But if i try to enter http://192.168.188.43:8099 i have :

ERR_CONNECTION_REFUSED

i tried to run netstat but i don't see port 8099 listening when z2m is running:

pi@raspberrypi: $ netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0    240 raspberrypi.fritz.b:ssh DESKTOP-QAKGUIG.f:65464 ESTABLISHED
tcp        0      0 raspberrypi.fritz:36144 47f46e248f9e4f9390:1883 ESTABLISHED
Active UNIX domain sockets (w/o servers)

i tried to format the sd and install all over again but it doesn't work.

Anyone can help me? any advice is welcome
TY

**Comment by nurikk** [comment]
your config `fronted:`
correct config `frontend:` fronte**n**d

**Comment by Altar82** [comment]
thanks, it was just that ....  fault of my age.. I'm getting old :D
ty so much
