### ISSUE TITLE
[Bug]: Cannot change retain setting.

### ISSUE THREAD

**Issue by salopette** [nurikk/z2m-frontend#786]
### What happened?

When I teach in a new device, the retain setting works.
But a short time later I can't change it.
It cannot be clicked.

![sshot-1](https://user-images.githubusercontent.com/32480002/131229867-bfab8084-a8bc-4ed5-af9f-c62ac85ae323.jpg)

### What browsers are you seeing the problem on?

Chrome

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks
