### ISSUE TITLE
In the map, what are "multiple types of links" w.r.t. Link Quality?

### ISSUE THREAD

**Issue by karwosts** [nurikk/z2m-frontend#829]
In the map, link quality is sometimes represented by two numbers instead of one (e.g. 45/110) . The help text says this is the link quality for "multiple types of links". 

Can you explain what is meant by this? I've tried reading the code, reading generic zigbee protocol articles, but I can't find any reference to what this actually means. If there is one high number and one low number, what can I interpret from that? Are the devices communicating on two frequencies? Multiple radios? Something else?

Thank you very much!

**Comment by nurikk** [comment]
No one knows, this is all you can get from reading documentation
