### ISSUE TITLE
Cannot change Debounce once it is set.

### ISSUE THREAD

**Issue by SargonofAssyria** [nurikk/z2m-frontend#847]
### What happened?

Change should be made and executed.
I change the debounce to 3 and want to set it back to 2.
The debounce field cannot be changed anymore.

### What browsers are you seeing the problem on?

Chrome and Edge

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
Fixed, thanks

**Comment by SargonofAssyria** [comment]
Tnx, it works. 👍
