### ISSUE TITLE
[Bug]: OTA percentage should be centred on progress bar

### ISSUE THREAD

**Issue by manfred-mp** [nurikk/z2m-frontend#954]
### What happened?

When updating firmware via OTA progress percentage is following actual progress. It should be entered to be visible all the time.

### What browsers are you seeing the problem on?

Safari

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by nurikk** [comment]
It's default bootstraps progress bar, if you know how to make it in center let me know

https://getbootstrap.com/docs/5.1/components/progress/
