### ISSUE TITLE
[Bug]: HS2WD-E 

### ISSUE THREAD

**Issue by Bartekn86** [nurikk/z2m-frontend#956]
### What happened?

![Bez tytułu](https://user-images.githubusercontent.com/69695376/137635624-af85edba-47ce-44b2-a87d-6cfcc81cfe7b.png)
![Bez tytułu](https://user-images.githubusercontent.com/69695376/137635646-1bfe1153-b263-4d36-97c3-e36cec66bced.png)
![Bez tytułu](https://user-images.githubusercontent.com/69695376/137635670-dcd80683-5dcf-43e3-9c8c-2b795a7d91a6.png)
[state.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7360383/state.json.zip)

could you have a look in the code please ?  
Data firmware
    2019.5.23
Producent
    HEIMAN
Model
    HS2WD-E

### What browsers are you seeing the problem on?

Firefox

### Did you donwload state.json.zip?

I will attach state.json.zip

**Comment by Bartekn86** [comment]
i think that is similar to https://github.com/nurikk/zigbee2mqtt-frontend/issues/863
except that, in domoticz i do not have any record of sirene

**Comment by nurikk** [comment]
Fixed, thanks

**Comment by Bartekn86** [comment]
hm...... strange, 
after update, there is no syrene on desktop :( and still there is "name" like in first screen, 
Could you look again into the code please ?
