### ISSUE TITLE
Ability to set base url for the front end application

### ISSUE THREAD

**Issue by yanshay** [nurikk/z2m-frontend#971]
**Is your feature request related to a problem? Please describe.**
I want to install Zigbee2mqtt under kubernetes and expose the frontend using ingress together with other applications, therefore I need the applications to be under /some-base-url.
This is for example doable with nod-red by setting a path prefix. 
Maybe it's supported already but I couldn't find anywhere including when searching the codebase.
If it is I'd appreciate if you could explain how it can be done.

**Describe the solution you'd like**
It should be possible to specify using configuration or environment variable that the application will be under some prefix url.

**Describe alternatives you've considered**
Couldn't find a way to do this at this time.

**Additional context**

**Comment by nurikk** [comment]
Hi, have you tried to configure [nginx](https://www.zigbee2mqtt.io/information/frontend.html#nginx-proxy-configuration)?

**Comment by yanshay** [comment]
If I get it right configuring nginx allows me to put zigbee2mqtt frontend under a different DNS name "zigbee2mqtt.mydomain.com", but if I want to put it under "homeassistant.mydomain.com/zigbee2mqtt" nginx alone can't take care of that, isn't that the case?
I know that in other react applications in order to support a base_url the app needs to allow configuring that also in the app, not just in nginx.

**Comment by nurikk** [comment]
Can you try to do whatever kubernetes kung fu you want and report any issue if happen?

**Comment by maxim-kukushkin** [comment]
Why was this issue closed? That's an absolutely valid request with an absolutely valid use case. It doesn't have to be Kubernetes.
People sometime need to run web-interfaces in a sub-path and all that's need is for the front end to support the path prefix.

I'm for one who needs to run the app in a subpath, keeping it inside a Docker compose setup

Needless to say the last response is quite harsh.

**Comment by lutierigb** [comment]
This is indeed a valid FR and lots of products support setting a base url so it can be hosted under a subpath. ie mydomain.com/zigbee2mqtt

This requests has nothing to do with k8s. It has more to do with the ability to run this behind a reverse proxy under a subpath instead of a subdomain as suggested in the official docs.

the existing `url` setting could be used for this purpose.

**Comment by hedefalk** [comment]
I'm having the same request. I tried putting zigbee2mqtt under "home.mydomain.com/zigbee2mqtt" using a reverse proxy. Unfortunately, the asset urls in the initial document does not use the "url" setting under frontend, I misunderstood @lutierigb  comment to mean it _did_ use the setting for this purpose :)

So to be ultra clear, I'm using a Traefik reverse proxy and initial page load works fine under home.mydomain.com/zigbee2mqtt, but the document href wont work:
```
<link rel="icon" type="image/x-icon" href="[assets/favicon.a8299d0b.ico](https://home.mydomain.com/assets/favicon.a8299d0b.ico)">
```

Must be https://home.mydomain.com/zigbee2mqtt/assets/favicon.a8299d0b.ico to work.

**Comment by lazynooblet** [comment]
@nurikk what would you need from us to assist on this issue? Or can you just clarify you are not interested

**Comment by nurikk-sa** [comment]
> @nurikk what would you need from us to assist on this issue? Or can you just clarify you are not interested

Hi there! If anyone can contribute this change it would be fantastic. I’m quite busy right now

**Comment by HalliHalloSchatz** [comment]
Need that fix.
I used zigbee2mqtt behind a reverse proxy in a subdirectory.

my.home.de/zigbee2mqtt

**Comment by FrozenGalaxy** [comment]
This issue still exists, no? Please re-open, I think @JamieMagee made a fix?
